### ISSUE TITLE
Gnome mpv ui with GTK3 headers bar CSD

### ISSUE THREAD

**Issue by serdotlinecho** [gnome-mpv/gnome-mpv#10]
Any plans to use or make gnome mpv with the GTK3 header bars in the future? I thought it will looks nice on GNOME desktop.

**Comment by gnome-mpv** [comment]
Yes. I'm still figuring out the design though.

**Comment by warmsun0220** [comment]
I think gnome-mpv can refer to the interface of totem.
It looks nice.

**Comment by rilian-la-te** [comment]
But what about XFCE and especially KDE? On KDE and XFCE (and boxes) headerbars look very weird:(

**Comment by gnome-mpv** [comment]
I plan to keep regular menu bar as an option.
