### ISSUE TITLE
not the whole translation

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#104]
not the whole translation
GNOME MPV last commit 7d59782a6ec659d2e2496ce2685eb1951c475abd
Last translate ru

translation
![2016-01-12 17-40-38](https://cloud.githubusercontent.com/assets/13280183/12266326/b34ae29e-b953-11e5-9e34-ce9d2da50579.png)
```
#: ../data/org.gnome-mpv.gschema.xml.in.h:1
msgid "Enable or disable dark theme"
msgstr "Включить / Отключить тёмный вариант темы"
```
no translation
![2016-01-12 17-40-46](https://cloud.githubusercontent.com/assets/13280183/12266347/c96ded64-b953-11e5-9d69-7027c326728c.png)

```
#: ../data/org.gnome-mpv.gschema.xml.in.h:2
msgid "Enable or disable client-side decorations"
msgstr "Включить / Отключить CSD"
```

**Comment by region51** [comment]
also without translation

Whether or not to make file chooser dialog remember last folder accessed
Load or don't load mpv configuration file
Load or don't load mpv input configuration file
Whether or not to redirect mpv log messages to console
Height of the window
URI of the last folder accessed
Width of the playlist
Show or not show the playlist
Width of the window

why?

**Comment by gnome-mpv** [comment]
Confirmed. I'm not sure why it's doing this though. I'll look into it.

**Comment by region51** [comment]
@gnome-mpv :+1:
