### ISSUE TITLE
AppData where the translation

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#105]
![h_1452687893_4846530_c36af0af18](https://cloud.githubusercontent.com/assets/13280183/12295226/c5216c5a-ba10-11e5-87f0-95ba7be5761c.png)
```
Where???
<_caption>The main window showing the application in action</_caption>
<_caption>The main window with CSD disabled</_caption>
<_caption>The main window with playlist open</_caption>
```
![h_1452688164_3417888_d4b0e56038](https://cloud.githubusercontent.com/assets/13280183/12295235/ce0c7e90-ba10-11e5-9240-4e369b843e09.png)

**Comment by gnome-mpv** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8312231/12295925/eb8236ec-ba36-11e5-95a5-430c82831873.png)

The translation works fine on my machine. Perhaps your appdata file is not properly updated? The file should have tags like this: `<p xml:lang="ru">Возможности:</p>`

As for the captions, I don't think gnome-software is using them. Pidgin has caption tags in its appdata file too and they're not showing up either.

**Comment by region51** [comment]
>The translation works fine on my machine. Perhaps your appdata file is not properly updated? The file should have tags like this: <p xml:lang="ru">Возможности:</p>

this is not my, no problems with the translation

>As for the captions, I don't think gnome-software is using them. Pidgin has caption tags in its appdata file too and they're not showing up either.

yes I mean it

**Comment by gnome-mpv** [comment]
>so it's not a problem?
Nope. Not a problem with gnome-mpv at least.

**Comment by region51** [comment]
OK.
