### ISSUE TITLE
Fedora rawhide lots of warning

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#110]
```
warning: 'g_option_group_unref' is deprecated: Not available before 2.44 [-Wdeprecated-declarations]
warning: 'g_list_model_get_type' is deprecated: Not available before 2.44 [-Wdeprecated-declarations]
```

Fedora rawhide more 
http://koji.russianfedora.pro/kojifiles/work/tasks/3818/63818/build.log

Fedora 22, 23 all right
http://koji.russianfedora.pro/kojifiles/work/tasks/3820/63820/build.log
http://koji.russianfedora.pro/kojifiles/work/tasks/3812/63812/build.log

what is the reason???

**Comment by gnome-mpv** [comment]
These warnings seem to be coming from within glib itself. I'm not exactly sure why, but I guess glib in rawhide is probably too new.

**Comment by region51** [comment]
`Fedora rawhide 2.47.5` so the problem is glib???

**Comment by region51** [comment]
Fedora rawhide glib2-2.47.4, gnome-mpv-0.6

normal
http://koji.russianfedora.pro/kojifiles/packages/gnome-mpv/0.6/3.fc24.R/data/logs/x86_64/build.log

**Comment by gnome-mpv** [comment]
Any errors when compiling gnome-mpv-0.7 with glib2-2.47.4 ?

**Comment by region51** [comment]
>glib2-2.47.4 ?

in rawhide repo glib2-2.47.5

**Comment by gnome-mpv** [comment]
Try compiling gnome-mpv-0.6 with glib2-2.47.5.

**Comment by region51** [comment]
>Try compiling gnome-mpv-0.6 with glib2-2.47.5

lots of warning
http://koji.russianfedora.pro/kojifiles/work/tasks/3824/63824/build.log

**Comment by gnome-mpv** [comment]
It's probably something that changed between glib2-2.47.4 and glib2-2.47.5 that caused the warnings then.

In any case, these are just deprecation warnings so they're not very harmful.

**Comment by region51** [comment]
OK.

**Comment by region51** [comment]
nice `glib2-devel-2.47.5-2.fc24` :+1: without warnings
http://koji.russianfedora.pro/kojifiles/work/tasks/5200/65200/build.log
