### ISSUE TITLE
Change application id

### ISSUE THREAD

**Issue by TingPing** [gnome-mpv/gnome-mpv#114]
For use with [xdg-app](https://wiki.gnome.org/Projects/SandboxedApps) (and dbus in general) you cannot have a `-` in the application id. I would propose something like `io.github.GnomeMpv` which follows the standards better (unless you have a better domain). Also the desktop file should match the application id. This change would break settings, file associations, and any users of the dbus interface though so I thought I would open an issue over it.

**Comment by gnome-mpv** [comment]
I left the old schema there so that the old settings can be copied to the new location. As for file association and the dbus interface, I don't think there's anything I can do. I don't think this would cause too much problem though.

**Comment by region51** [comment]
@gnome-mpv release gnome-mpv-0.8, may be removed old GSchema.

**Comment by gnome-mpv** [comment]
888edf5f74555805baae2e27981680a31c31d90c

**Comment by region51** [comment]
@gnome-mpv [link](https://github.com/gnome-mpv/gnome-mpv/blob/master/data/io.github.GnomeMpv.gschema.xml.in)
>Whether the settings has already been migrated from the previous version
???

**Comment by region51** [comment]
also it is necessary to remove translate in Zanata.

**Comment by gnome-mpv** [comment]
a090e79cfbd230cdd2aa822c7240509312a2ef6c

**Comment by region51** [comment]
@gnome-mpv hi, again ^^^
>may be removed old schema
>>Whether the settings has already been migrated from the previous version
>>>also it is necessary to remove translation in Zanata
