### ISSUE TITLE
Wayland and Toggle Playlist

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#115]
In Wayland does not work Toggle Playlist.
Any ideas?

Sorry for my bad English

**Comment by region51** [comment]
Also Wayland  double click fullscreen 
>failed to increment property 'fullsreen' by 1

![2016-02-06 14-48-32](https://cloud.githubusercontent.com/assets/13280183/12866512/68dd64ba-cce1-11e5-9424-1c62fba73ef1.png)

**Comment by gnome-mpv** [comment]
>In Wayland does not work Toggle Playlist.

It seems to work for me but sometimes this [GTK+
bug](https://bugzilla.gnome.org/show_bug.cgi?id=755051) confuses the window
resizing code so the playlist becomes really tiny -- sometimes just 1px wide. You should still be able to resize it though.

>Also Wayland, does not work double click fullscreen

06adf7e

**Comment by region51** [comment]
Yes indeed! 1px wide, this is very bad.

**Comment by gnome-mpv** [comment]
With 77ebef2, the playlist won't become smaller than 20px. The playlist may still resize itself from time to time though. Hopefully, when gtk 3.20 is released this won't be an issue anymore.
