### ISSUE TITLE
Audio CD

### ISSUE THREAD

**Issue by suedi** [gnome-mpv/gnome-mpv#117]
Is it possible to play an audio cd via gnome-mpv?

mpv can do it for sure, maybe it's not exposed in gnome-mpv
or simply I cannot figure out how to do it.

help?

**Comment by gnome-mpv** [comment]
Yes. First, open the `Open Location` dialog, either by using the menu or pressing Ctrl+L. Then type `cdda://` in the textbox and click `Open` or press enter. This also works for other protocols listed in `mpv --list-protocols`.

**Comment by suedi** [comment]
Yup it works but it is choppy.

If I add  `--cache` in preferences-->Extra MPV options the playback is smooth.

How about playlist? I don't mean with song names just the placeholders
to change song?

I know I can do like `cdda://1` for track 1

Is there no way to get to the next i.e. with an easy click?

**Comment by gnome-mpv** [comment]
When playing audio CDs, the tracks become chapters so you can go to the next/previous track by pressing the `@`/`!` key or using the next/previous button in the control bar.

**Comment by suedi** [comment]
Maybe I have an old version then?

I don't have next/previous button in the control bar only search buttons?
The shortcuts doesn't work either.

WIll compile latest git and get back...

**Comment by suedi** [comment]
...  tried the latest git

The same for me if I click ">>" button gnome-mpv searches a bit forward.

The shortcuts doesn't work

**Comment by gnome-mpv** [comment]
Does it work in plain mpv? The shortcuts should be the same.

**Comment by gnome-mpv** [comment]
Also, make sure you are using `cdda://` without any track number.

**Comment by suedi** [comment]
If I do 

`mpv cdda://1-10 /dev/sr0 --cache`

it plays the music but doesn't show a window like when playing movie so
no buttons to click?

*EDIT*

Saw your next comment

when trying `mpv cdda:// /dev/sr0 --cache`

I get no extra window however it seems to listen to shortcuts
when I try `@` I get message `(chapter unavailible)` in terminal

**Comment by gnome-mpv** [comment]
It seems that mpv is seeing the whole CD as one track, so either the CD doesn't have tracks information or there's a bug in mpv that causes it not to see the tracks. If you can see the tracks with another player, I suggest you file a bug with mpv.

You can use `--force-window` to get a window, but it probably won't make a difference.

**Comment by suedi** [comment]
VLC could change the track.

Thanks for your help.

closing...
