### ISSUE TITLE
Drag and drop subtitles error

### ISSUE THREAD

**Issue by dyskette** [gnome-mpv/gnome-mpv#118]
When playing a video file, if I drag and drop a subtitle file (srt) from nautilus to gnome-mpv, the program shows an error saying: `Playback was terminated abnormally. Reason: no audio or video data played.` While in a terminal it says `** Message: [cplayer] No video or audio streams selected.`.

**Comment by gnome-mpv** [comment]
Loading subtitles by DnD is not yet implemented. For now, you can load subtitles using the `Load External..` menu item under `Subtitle Track` (There needs to be a video loaded for it to appear).
