### ISSUE TITLE
warning _FORTIFY_SOURCE

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#120]
%configure --enable-debug

```
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
```

This is bad???

**Comment by region51** [comment]
configure.ac

`AX_APPEND_COMPILE_FLAGS([-O0 -g -fsanitize=address])`

Both pairs can be compiled without warnings

`AX_APPEND_COMPILE_FLAGS([-O1 -g -fsanitize=address])`
`AX_APPEND_COMPILE_FLAGS([-O2 -g -fsanitize=address])`

**Comment by gnome-mpv** [comment]
>This is bad???
No. It should work fine if you compile without the debugging flag.

**Comment by region51** [comment]
>because it might interfere with debugging.

OK.
