### ISSUE TITLE
Window size should auto adjust to video size

### ISSUE THREAD

**Issue by mc4man** [gnome-mpv/gnome-mpv#121]
As it stands now the player always open next video at the size of previous one. To get 'normal' size with subsequent files that are a different rez one must continually go View > pick one, typically "Normal Size" here.

**Comment by gnome-mpv** [comment]
You can enable that feature by putting `--autofit=100%` in `Extra MPV options`.

**Comment by mc4man** [comment]
Thanks for info

**Comment by mc4man** [comment]
Actually just tried, does nothing & if it did should produce a window that fills the screen size. 
Seems gnome-mpv doesn't use any window related options anyway, like window-scale=, windows always open at last previous size

**Comment by gnome-mpv** [comment]
The only window-related option that's used by gnome-mpv at the moment is just `--autofit` though I plan to add support for the other options later. It seems to work properly for me though.

Can you compile the latest version from git and post the log messages here? You can enable logging by running gnome-mpv like this `G_DEBUG_MESSAGES=all gnome-mpv`.

**Comment by region51** [comment]
@mc4man 
>Window size should auto adjust to video size

fixed gnome-mpv-07... 512e9344467529d291f62b99c6d24fc61400fb5f

**Comment by mc4man** [comment]
Yes, that commit fixes this, vids open at their size.
One little thing would be that if gnome-mpv is *not* open when opening a vid of different size than prior then there is a quick flash of a 'window' @ prior size, then vid opens at proper size.
Really minor, just thought i'd mention.

If you know offhand - does this commit depend on any commits after 0.7 'release' that Debian is using?

**Comment by mc4man** [comment]
I see it does, no matter. Working fine other than that little flash deal, thanks.

**Comment by gnome-mpv** [comment]
512e934 just adds some debugging messages. It's probably 32427d5 that actually fixes the issue. The commit applies cleanly on top of v0.7.

**Comment by region51** [comment]
@gnome-mpv 8d2541f72599cd9f8396134125e6caa355ea12e1
>Window size should auto adjust to video size

It does not work for me

**Comment by region51** [comment]
gnome-mpv-07 ... 512e9344467529d291f62b99c6d24fc61400fb5f  worked

**Comment by gnome-mpv** [comment]
@region51: Make sure that you have `--autofit` set in either extra mpv options or external config file. The option is now required for autofitting to happen at all. Previously, it just autofits to the actual video size if no option is provided.

**Comment by region51** [comment]
@gnome-mpv I do not understand, I do not speak English.
You can  show the video?

**Comment by gnome-mpv** [comment]
![screenshot from 2016-03-03 00-07-55](https://cloud.githubusercontent.com/assets/8312231/13468300/8c1ebc24-e0d4-11e5-9a0d-985886dc4303.png)

Putting `--autofit=100%` in the box restores the old behavior.

**Comment by region51** [comment]
@gnome-mpv does not work
>Window size should auto adjust to video size

video 6.72 МБ https://www.dropbox.com/s/96mfcn1p1trz9n0/gnome-mpv.mkv?dl=0

**Comment by region51** [comment]
@gnome-mpv working
>Window size should auto adjust to video size

video 4.72 МБ https://www.dropbox.com/s/o1qr6lvb3npwq2d/GnomeMpv.mkv?dl=0

**Comment by gnome-mpv** [comment]
You need to put `--autofit=100%` in the text box like in my screenshot for it to work. There wasn't anything in the text box in your video.

In any case, I made `--autofit=75%` a default option (587de19) so autofitting should work without any extra settings now.

**Comment by mc4man** [comment]
Well yesterday was testing 512e934 & it worked fine with either the extra option of 
--autofit=
or
--window-scale=1.0
(note the autofit uses an empty string

With today’s 4280bb2 nothing is needed as an extra option, works fine

(- the only exception to that is only in an ubuntu sesssion, only if csd is disabled & only when the window merges into the unity panel. In that case any subsequent opened vid opens maximized. However this corner case is not unknown & not specific to gnome-mpv

Would note that at least here changes to gnome-mpv's extra settings requires a log out/in to take affect.

**Comment by gnome-mpv** [comment]
>Well yesterday was testing 512e934 & it worked fine with either the extra option of
>--autofit=
>or
>--window-scale=1.0
>(note the autofit uses an empty string

>With today’s 4280bb2 nothing is needed as an extra option, works fine

d40fa0c should have made `--autofit` necessary. Do you have an external mpv config file? `--autofit` can be set from a config file as well.

 >Would note that at least here changes to gnome-mpv's extra settings requires a log out/in to take affect.

Did you see this behavior in an Ubuntu session? Everything in the preferences dialog (except csd) should take effect immediately upon saving.

**Comment by region51** [comment]
I do not understand 
default mpv normal https://www.dropbox.com/s/ep1t0q0mvy6xjbb/mpv.mkv?dl=0
default gnome-mpv bad https://www.dropbox.com/s/96mfcn1p1trz9n0/gnome-mpv.mkv?dl=0

in MPV done correctly by default

**Comment by mc4man** [comment]
No, don't have anything related in mpv.conf
What I do notice now is i'm getting 2 gschemas, seems the io one is taking precedence but the gui was showing the org one. Was this intended or a screw up on my part? - 
Ex.
/usr/share/glib-2.0/schemas/io.github.GnomeMpv.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome-mpv.gschema.xml

**Comment by region51** [comment]
@mc4man https://github.com/gnome-mpv/gnome-mpv/issues/114
>The old GSchema is left installed for settings migration.

**Comment by gnome-mpv** [comment]
@region51: I mean the behavior of the `--autofit` option. Right now, gnome-mpv behaves like `mpv --autofit=75% video_file.mkv` by default, but mpv appears to be using `--window-scale=1`. That option is not available in gnome-mpv yet (I'm working on it). I'll make that the default once I'm done.

**Comment by region51** [comment]
>but mpv appears to be using --window-scale=1. That option is not available in gnome-mpv yet (I'm working on it). I'll make that the default once I'm done.

Now it is clear.

**Comment by mc4man** [comment]
Yeah, I see that now, finally dawned on me that nothing was being 
written to the old gschema
Otherwise sorry for any confusion *I* caused. It turns out first thing 
yesterday I did a make install of the master (/usr/local) & forgot to 
remove it. So naturally after installing todays master via a package, 
(/usr) it also *appeared* to work fine. Have since cleared out the whole 
mess to recheck.
So as of yesterday's master (512e934) vids opened at native size, no 
options needed,  as of today's master they open at last used size.

Again sorry for some of the bs comments.

**Comment by gnome-mpv** [comment]
I finished implementing `--window-scale`. The previous default option `--autofit=75%` has also been replaced with `--window-scale=1 --autofit-larger=75%`. The new default behavior is to play video at native size, unless the video is taller/wider than 75% of the screen, in which case gnome-mpv will resize the video so that it fits within 75% of screen width/height.

**Comment by mc4man** [comment]
Can truly say now that it  works as intended, by default windows open at native size.
Thanks
