### ISSUE TITLE
[Feature request]:Drag'n'Drop of playlist

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#122]
It would be nice
![2016-03-27 14-52-39](https://cloud.githubusercontent.com/assets/13280183/14065279/1ba240e0-f42c-11e5-9ecf-b140e94fec66.png)

**Comment by gnome-mpv** [comment]
Do you mean that gnome-mpv should start playing the item dropped onto the video area from the playlist?

**Comment by region51** [comment]
@gnome-mpv yes.

**Comment by region51** [comment]
@gnome-mpv any news?
PS. Very tough task?

**Comment by gnome-mpv** [comment]
It requires handling playlist reordering manually rather than letting gtk do it. It's probably not difficult but might be tedious.
