### ISSUE TITLE
wayland: Indent 5px on menu 

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#123]
Wayland
![2016-02-27 23-15-10](https://cloud.githubusercontent.com/assets/13280183/13375129/ab4216ca-dda8-11e5-8616-a9dc28e2fd43.png)
5px indent ???
![r](https://cloud.githubusercontent.com/assets/13280183/13375134/ce3f2b9a-dda8-11e5-81b8-9cb0d9a63185.png)
xorg everything is fine
![2016-02-27-231615_1280x1024_scrot](https://cloud.githubusercontent.com/assets/13280183/13375130/c032884e-dda8-11e5-8fc0-15ce7cf09b5b.png)
Sorry for my bad English.

**Comment by gnome-mpv** [comment]
This is probably a GTK bug since it also happens with gnome-terminal.

**Comment by gnome-mpv** [comment]
I just tested with gtk-3.19.10 and it seems that the bug has already been fixed in that version.
