### ISSUE TITLE
[Feature request]: add tooltip

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#126]
there is
![2016-03-02 14-00-33](https://cloud.githubusercontent.com/assets/13280183/13458850/ed9d2390-e080-11e5-823a-714384ad2661.png)
tooltip no
![1](https://cloud.githubusercontent.com/assets/13280183/13458916/3c80ac34-e081-11e5-9d43-dbc314536394.png)
![2](https://cloud.githubusercontent.com/assets/13280183/13458918/3fe00474-e081-11e5-88c9-a610e0695cf7.png)
![3](https://cloud.githubusercontent.com/assets/13280183/13458924/434521c6-e081-11e5-9089-6e38a0f1f7c8.png)
![4](https://cloud.githubusercontent.com/assets/13280183/13458926/46888dbe-e081-11e5-906d-2f87822b4275.png)

**Comment by region51** [comment]
Also disable client-side decorations
![5](https://cloud.githubusercontent.com/assets/13280183/13459068/2b920d4a-e082-11e5-9c02-d389a34dde25.png)

**Comment by region51** [comment]
@gnome-mpv :+1: 
![2016-03-02 16-15-05](https://cloud.githubusercontent.com/assets/13280183/13461411/35711e68-e092-11e5-9f11-6cfa197ebb09.png)

**Comment by region51** [comment]
@gnome-mpv why Rewind? 
>gtk_widget_set_tooltip_text(box->rewind_button, _("Rewind"));

can backward

**Comment by region51** [comment]
@gnome-mpv In full screen mode does not work
![2016-03-02 16-30-49](https://cloud.githubusercontent.com/assets/13280183/13461739/7e6f8ecc-e094-11e5-9693-fb0b154068f9.png)

**Comment by gnome-mpv** [comment]
ca74296

**Comment by region51** [comment]
@gnome-mpv Full!screen :+1:

**Comment by region51** [comment]
here you can?
![2016-03-02 20-00-31](https://cloud.githubusercontent.com/assets/13280183/13467982/abcd1502-e0b1-11e5-9beb-45f4c1683587.png)

**Comment by gnome-mpv** [comment]
It's possible, but most gnome applications don't have any tooltips for buttons in header bar so I'm not sure if I should put them there. I'm not sure what the tooltip text should be for the first and the last buttons either.

**Comment by region51** [comment]
@gnome-mpv in eog there is fullscreen tooltip
![2016-03-12 19-39-27](https://cloud.githubusercontent.com/assets/13280183/13724081/9e22a828-e88a-11e5-8671-d024dde15045.png)

**Comment by gnome-mpv** [comment]
ebf6596
