### ISSUE TITLE
I can not find translation

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#127]
```
#: ../src/application.c:516
msgid "Playing"
msgstr "Воспроизведение"
```
@gnome-mpv where it is in the player? I can not find

**Comment by gnome-mpv** [comment]
The string "Playing" is the reason provided when inhibiting automatic sleep. If you leave the system idle long enough while a file is playing, there will be a notification telling you why the system hasn't gone to sleep yet with "Playing" given as the reason.

**Comment by region51** [comment]
it's clear to me
