### ISSUE TITLE
add thanks

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#128]
It would be nice to see a author, translation ...
![2016-03-03 14-47-39](https://cloud.githubusercontent.com/assets/13280183/13493580/e6441d04-e14f-11e5-9856-dbab640715f1.png)
example
![2016-03-03 14-51-37](https://cloud.githubusercontent.com/assets/13280183/13493592/f36f2da2-e14f-11e5-91a8-044f9d330de2.png)
![2016-03-03 15-12-10](https://cloud.githubusercontent.com/assets/13280183/13493972/861d2ef4-e152-11e5-87ad-35350bbf785d.png)

**Comment by region51** [comment]
@gnome-mpv it's good :+1: 
![2016-03-04 12-18-23](https://cloud.githubusercontent.com/assets/13280183/13523024/0968ef6c-e204-11e5-84c5-12ecdccac557.png)
PS. can you add "mailto:" e-mail link
![2016-03-04-122137_1280x1024_scrot](https://cloud.githubusercontent.com/assets/13280183/13523138/ab42a53a-e204-11e5-97b5-bf7990e734e2.png)

**Comment by gnome-mpv** [comment]
I added the email for you. It will appear next time Zanata is synced. You can also change this later by modifying "translator-credits" in Zanata.

**Comment by region51** [comment]
@gnome-mpv Thank you
![2016-03-04 15-30-08](https://cloud.githubusercontent.com/assets/13280183/13527180/44c35d62-e21e-11e5-9322-815271d5063e.png)
