### ISSUE TITLE
question: playlist icons

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#131]
Pause
![pause](https://cloud.githubusercontent.com/assets/13280183/13556138/4e41c0f6-e3e3-11e5-95ba-0cfa9beb94ef.png)
You can do so? 
![pause1](https://cloud.githubusercontent.com/assets/13280183/13556140/5da3b400-e3e3-11e5-9c0b-87f8920de3bc.png)
Example
http://screenshots.ubuntu.com/screenshots/t/totem/67_large.png
Sorry for my bad English.

**Comment by gnome-mpv** [comment]
Yes.

**Comment by region51** [comment]
also press _Stop_, in playlist _Play_ icon
![1](https://cloud.githubusercontent.com/assets/13280183/13756491/2cffd9d8-ea31-11e5-821b-ea7e8ccdbba9.png)

**Comment by gnome-mpv** [comment]
It's actually not supposed to be a play button, just something to show which file is currently playing. Maybe it would be better to just change the icon to something else.

**Comment by gnome-mpv** [comment]
2f1b5b4 removes the 'icon' and use bold text to indicate current entry instead. This should be less confusing and also more space-efficient.
