### ISSUE TITLE
Small problem with the playback

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#133]
@gnome-mpv Hi
Fedora 23, gnome-mpv v.last git commit
Video 2.61 MB https://www.dropbox.com/s/96mfcn1p1trz9n0/gnome-mpv.mkv?dl=0
Video 2.16 MB https://www.dropbox.com/s/o1qr6lvb3npwq2d/GnomeMpv.mkv?dl=0
Sorry for my bad English.

**Comment by gnome-mpv** [comment]
I don't see anything wrong with either of those videos.

**Comment by region51** [comment]
@gnome-mpv after double click video does not play automatically

**Comment by region51** [comment]
@gnome-mpv does not work

**Comment by region51** [comment]
example Baka MPlayer
The mpv based media player
3.02 MB https://www.dropbox.com/s/5wbmkf9fp1g1ypv/Baka-MPlayer.mkv?dl=0

**Comment by gnome-mpv** [comment]
5df95ee

**Comment by region51** [comment]
@gnome-mpv 5df95ee8fcb4db8ed6cfca5c73cafdcb99f14583 :+1:
