### ISSUE TITLE
why is?

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#136]
What for??? awful, disfigure :-1: 
![2016-03-09-123806_1280x1024_scrot](https://cloud.githubusercontent.com/assets/13280183/13631129/1626fb42-e5f4-11e5-8243-a38cf0be3bc5.png)
Sorry for my bad English.

**Comment by region51** [comment]
PS. IMHO, radio button
must be identical
![1](https://cloud.githubusercontent.com/assets/13280183/13631449/c0699960-e5f5-11e5-9b04-c6fb1329be17.png)
![2](https://cloud.githubusercontent.com/assets/13280183/13631453/c3b98710-e5f5-11e5-915a-3d86ae7d30d4.png)
![3](https://cloud.githubusercontent.com/assets/13280183/13631455/c7229c2a-e5f5-11e5-8150-6620d52ab943.png)
![4](https://cloud.githubusercontent.com/assets/13280183/13631456/ca1cb5d2-e5f5-11e5-8c0c-67c8f8c130c2.png)
Sorry for my bad English.

**Comment by gnome-mpv** [comment]
This is added automatically by gtk based on GAction type of `playlist_toggle`, which was changed recently. I agree it looks a little bit unpleasant.

**Comment by region51** [comment]
>I agree it looks a little bit unpleasant.

it's necessary remove

**Comment by region51** [comment]
^^^ checkbutton, radiobutton???

**Comment by region51** [comment]
@gnome-mpv 
>PS. IMHO, checkbutton, radiobutton
>>must be identical

![2](https://cloud.githubusercontent.com/assets/13280183/13638251/7f20f0a8-e61c-11e5-8421-f129846b3197.png)
--> example
![1](https://cloud.githubusercontent.com/assets/13280183/13638254/84572d12-e61c-11e5-86dc-6eb6b20f4583.png)

**Comment by gnome-mpv** [comment]
It would probably require too much work to do that in gnome-mpv. A better place to implement this would be in gtk itself.

**Comment by region51** [comment]
Hm, I am understand.
Thanks for fast reply.
