### ISSUE TITLE
Playlist problem's

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#137]
@gnome-mpv ???
gnome-mpv-0.7-2.20160307git5df95ee :+1: 
normal https://www.dropbox.com/s/tcbrcxftojin31o/gnome-mpv-normal.mkv?dl=0
gnome-mpv last commit :-1: 
bad https://www.dropbox.com/s/acc3u06ucnp6jqb/gnome-mpv-bad.mkv?dl=0

**Comment by region51** [comment]
@gnome-mpv a new problem
gnome-mpv v.last git commit
How reproducible:

* in the playlist two file
* start playing the second file+press stop+Double-click on the second file

**Comment by region51** [comment]
after pressing stop, should not stand out in bold text

**Comment by gnome-mpv** [comment]
e70ba93abfbf6168af05bb4c7c829df08971cfa9
d3a0e5efd1becd0eb8a234820f634ff01f2d9102

**Comment by region51** [comment]
@gnome-mpv :+1: :+1:

**Comment by region51** [comment]
@gnome-mpv a new problem
Video 3.22MB https://www.dropbox.com/s/96mfcn1p1trz9n0/gnome-mpv.mkv?dl=0
will play the first file?

**Comment by gnome-mpv** [comment]
That's intentional.

**Comment by region51** [comment]
>That's intentional.

what for?

**Comment by gnome-mpv** [comment]
It makes it easy to go back to the beginning of the playlist, which can be difficult otherwise for large playlists; you'd need to scroll all the way back to the top of the playlist and double click the first entry. Going back back to the beginning of a file can always be done easily with the seek bar so making the stop button do that doesn't make it much more convenient.

**Comment by region51** [comment]
@gnome-mpv 
double click mouse _Brooklyn.Nine.Nine.S03E18.avi_
_Brooklyn.Nine.Nine.S03E15.avi_ becomes one second bold text ???
![2016-03-15 16-47-56](https://cloud.githubusercontent.com/assets/13280183/13779947/73021f16-eace-11e5-849c-75bdc3683366.png)

**Comment by gnome-mpv** [comment]
Not quite sure what you mean, but Brooklyn.Nine.Nine.S03E18.avi should become bold after you double click on it and Brooklyn.Nine.Nine.S03E15 would no longer be bold.

**Comment by region51** [comment]
@gnome-mpv but the first file is included for 1 second.
it can be seen in the screenshot
>in header bar one second Brooklyn.Nine.Nine.S03E15.avi ???

**Comment by gnome-mpv** [comment]
bdafa402e31d0f5743e917c61c8d329d1dab6704

**Comment by region51** [comment]
@gnome-mpv You can do so? keyboard control playlist
example https://www.dropbox.com/s/5wbmkf9fp1g1ypv/Baka-MPlayer.mkv?dl=0

**Comment by gnome-mpv** [comment]
Already possible with `<` and `>` (same as mpv).

**Comment by region51** [comment]
>Already possible with < and > (same as mpv).

I do not mean it

**Comment by gnome-mpv** [comment]
You mean moving the highlighted row?

**Comment by region51** [comment]
>Already possible with < and > (same as mpv).

I understood
input.conf
```
> playlist-next                        # skip to next file
< playlist-prev                        # skip to previous file
```
Shift+>
Shift+<

**Comment by region51** [comment]
@gnome-mpv player :+1:

**Comment by region51** [comment]
@gnome-mpv keyboard control 
how to play the selected file?

**Comment by region51** [comment]
@gnome-mpv a new problem
gnome-mpv v.last git commit
How reproducible:
* play video+press pause
* double click mouse another file

**Comment by region51** [comment]
one more problem
* add file in playlist+press pause
* add another file in playlist

file will automatically start to play

**Comment by gnome-mpv** [comment]
> how to play the selected file?
Not possible with keyboard yet.

**Comment by gnome-mpv** [comment]
>@gnome-mpv a new problem
>gnome-mpv v.last git commit
>How reproducible:
>
>    play video+press pause
>    double click mouse another file
>
>or
>
>    play video+press pause
>    < and > (same as mpv).

Not sure what the problem is here. Should the new playlist entry start playing automatically?

**Comment by gnome-mpv** [comment]
>one more problem
>
>    add file in playlist+press pause
>    add another file in playlist
>
>file will automatically start to play

8e7ca3e

**Comment by region51** [comment]
@gnome-mpv 
>
* play video+press pause
* double click mouse another file

fixed
>
* add file in playlist+press pause
* add another file in playlist

fixed

* play video+press pause
* < and > (same as mpv).
https://www.dropbox.com/s/96mfcn1p1trz9n0/gnome-mpv.mkv?dl=0 ??? :-1: 

also one more problem gnome-mpv v.last git commit
* add file in playlist

pause??? :-1:

**Comment by region51** [comment]
@gnome-mpv one more problem

* add file in playlist+Delete
* add file in playlist

pause?

**Comment by gnome-mpv** [comment]
cc84ded72b567932cb2d9b468f2d738a89349463

**Comment by region51** [comment]
@gnome-mpv  cc84ded72b567932cb2d9b468f2d738a89349463

not fixed

**Comment by gnome-mpv** [comment]
581960bbfdc31eed1f4f398559b5abe834888428
