### ISSUE TITLE
pause reset

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#138]
Fedora 23, gnome-mpv v.last git commit
Video 4.92 MB https://www.dropbox.com/s/96mfcn1p1trz9n0/gnome-mpv.mkv?dl=0
or
Vide0 0.98 MB https://www.dropbox.com/s/o1qr6lvb3npwq2d/GnomeMpv.mkv?dl=0
I don't speak English :-1: 
?

**Comment by gnome-mpv** [comment]
I don't see what's wrong here.

**Comment by region51** [comment]
@gnome-mpv play video+press Pausa/Stop+open Preferences+press Save
or
Enable client-side decorations
or
Enable dark theme
or
Remember last file's location

**Comment by region51** [comment]
@gnome-mpv Now
play video+press stop+open preferences+press save
or ^^^

**Comment by gnome-mpv** [comment]
e81f973
