### ISSUE TITLE
playlist size

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#139]
gnome-mpv v.last git commit
Toggle Playlist :-1: 
![2016-03-10 13-35-34](https://cloud.githubusercontent.com/assets/13280183/13666944/2ebd1700-e6c5-11e5-9636-30d6412eeb1b.png)
what for?

**Comment by gnome-mpv** [comment]
It's broken. I'm working on it.

**Comment by region51** [comment]
@gnome-mpv does not work

**Comment by gnome-mpv** [comment]
Video please.

**Comment by region51** [comment]
@gnome-mpv 
>Video please.

gnome-mpv-07 [link](https://www.dropbox.com/s/44ep854hxj0fvd1/gnome-mpv-0.7.mkv?dl=0) 50/50 
gnome-mpv last commit [link](https://www.dropbox.com/s/dnk6u10ugi8a6nq/gnome-mpv-last-commit.mkv?dl=0) :-1: 

example baka-mplayer 
>The libmpv based media player

baka-mplayer [link](https://www.dropbox.com/s/5wbmkf9fp1g1ypv/Baka-MPlayer.mkv?dl=0) :+1: 
and fullsreen 
baka-mplayer [link](https://www.dropbox.com/s/sbgj7gh2cxgqxhm/baka-mplayer-fs.mkv?dl=0) :+1:

**Comment by gnome-mpv** [comment]
Does ae96a2d fix the problem?

**Comment by region51** [comment]
@gnome-mpv yes.

**Comment by region51** [comment]
@gnome-mpv question
Playlist in Fullscreen no longer supported?

**Comment by gnome-mpv** [comment]
It's disabled at least for now. I might reimplement it in a different way.
