### ISSUE TITLE
Still some words didn't  add multi-language support

### ISSUE THREAD

**Issue by warmsun0220** [gnome-mpv/gnome-mpv#14]
![2015-02-06 17 10 21](https://cloud.githubusercontent.com/assets/5374125/6076832/579dbd0e-ae23-11e4-88e5-e440f30c0c2e.png)

as shown in the figure:
MPV Configuration
Keybindings
Miscellaneous

sorry for my poor english

**Comment by gnome-mpv** [comment]
Actually, those strings has already been marked for translation. See: https://github.com/warmsun0220/gnome-mpv/blob/16a8ad84975d54754b7f7d1f086ea7e692ffabf7/po/zh_CN.po#L262-272

**Comment by warmsun0220** [comment]
This is my negligence.  Close this issue.
