### ISSUE TITLE
memory leak???

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#141]
memory use climbs at a pretty fast rate.
![2016-03-11 16-57-58](https://cloud.githubusercontent.com/assets/13280183/13704172/9708fdd8-e7ab-11e5-9674-1286a15344f9.png)
-->
![2016-03-11 17-03-58](https://cloud.githubusercontent.com/assets/13280183/13704177/9c11a9f6-e7ab-11e5-94c7-86ea1307b53c.png)
...

**Comment by region51** [comment]
It seems problem in Toggle fullscreen. This is problem gnome-mpv or mpv?

**Comment by gnome-mpv** [comment]
This happens with any programs, not just gnome-mpv and mpv, and it's only the memory usage for gnome-shell that increases, so it's probably gnome-shell that causes this. The memory usage should go down after a while when the garbage collector starts freeing the memory.
