### ISSUE TITLE
question about player

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#147]
start player
![2016-03-17 22-45-59](https://cloud.githubusercontent.com/assets/13280183/13859185/4432c5de-ec93-11e5-8d6a-cb55cb49daa8.png)
stop+delete file
![2016-03-17 22-46-22](https://cloud.githubusercontent.com/assets/13280183/13859193/556d2bfa-ec93-11e5-8f11-8477d55358ef.png)
this is normal?

**Comment by gnome-mpv** [comment]
It's probably better to disable the volume button in this situation too.

**Comment by region51** [comment]
@gnome-mpv Playlist is empty, no files. why pause?

**Comment by gnome-mpv** [comment]
When the playlist empty, nothing can possibly be playing, so being paused makes sense to me.

**Comment by region51** [comment]
Got it!
