### ISSUE TITLE
active/inactive toggle fullscreen icon

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#148]
in eog no file, toggle fullscreen inactive
![2016-03-18 15-03-31](https://cloud.githubusercontent.com/assets/13280183/13877302/e81562b0-ed1a-11e5-9f0e-3a7417d47bb9.png)
gnome-mpv no file, toggle fullscreen active
![2016-03-18 15-01-16](https://cloud.githubusercontent.com/assets/13280183/13877305/ed6bf6e8-ed1a-11e5-9869-1117d2c6bcd8.png)

Maybe it's worth to try, do you agree?

**Comment by gnome-mpv** [comment]
I don't think it's a good idea. There are reasons why you might want to enter fullscreen mode even when there are no file loaded. For example, in multi-monitor setup, you might want to keep gnome-mpv fullscreened in one monitor while loading files from another.

**Comment by region51** [comment]
OK
