### ISSUE TITLE
Not save window size

### ISSUE THREAD

**Issue by varlesh** [gnome-mpv/gnome-mpv#149]
Overview Description:
When if you open any videos window Gnome-MPV always change size.
Program ignore this options on mpv.conf:
`geometry=50%:50%`
Maybe better add option for lock size window or another variant?

Version:
gnome-mpv-git  0.7.r182.g8e79f42-1
Archlinux x86_64 Gnome DE

**Comment by varlesh** [comment]
Preview bug:
https://youtu.be/Bi5GPQeSy4M

**Comment by gnome-mpv** [comment]
`geometry` has not been implemented in gnome-mpv yet. For now, you can disable auto-resize using `autofit=0`.

**Comment by varlesh** [comment]
Oh, sorry i don't know this :) Thx, working fine!
