### ISSUE TITLE
[Feature request]: opensubtitle support

### ISSUE THREAD

**Issue by sevachka** [gnome-mpv/gnome-mpv#151]
It would be awesome if there could be opensubtitle support (like within VLC or Totem/gnome-video).

**Comment by gnome-mpv** [comment]
I added a new tab in preferences dialog that allows loading lua scripts. Here are a few lua scripts that uses [subliminal](https://github.com/Diaoul/subliminal) to load subtitles from multiple sources, including opensubtitle.org:
- https://github.com/directorscut82/find_subtitles 
- https://gist.github.com/selsta/ce3fb37e775dbd15c698

**Comment by PKBuzios** [comment]
> I added a new tab in preferences dialog that allows loading lua scripts. Here are a few lua scripts that uses [subliminal](https://github.com/Diaoul/subliminal) to load subtitles from multiple sources, including opensubtitle.org:
> 
>     * https://github.com/directorscut82/find_subtitles
> 
>     * https://gist.github.com/selsta/ce3fb37e775dbd15c698

The find_subtitles script is kicking-in on every start when it should only run after pressing "s"
Could this be a gnome-MPV specific error?

**Comment by gnome-mpv** [comment]
>The find_subtitles script is kicking-in on every start when it should only run after pressing "s"
>Could this be a gnome-MPV specific error?

No, this is [done intentionally](https://github.com/directorscut82/find_subtitles/blob/master/find_subtitles.lua#L64) by the author of the script.
