### ISSUE TITLE
saving the video's current state (pause)

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#152]
Steps to Reproduce:
1. play video
2. press pause
3. Shift+q

Actual Results: playback will resume at the last position

Expected Results: There should be a pause, as the default mpv

Fedora 23, gnome-mpv-0.7-2.20160318git8e79f42

Sorry for my bad English.

**Comment by nado** [comment]
That’s not the default mpv, at least not on my laptop. Default config for mpv is to not save any vide position but start them from the beginning AFAIK.

**Comment by region51** [comment]
@nado  no configuration file mpv, default mpv, press pause + Shift+q

**Comment by nado** [comment]
Oh, right, I never used the Shift. Sorry.
