### ISSUE TITLE
[BuildFail] Autogen

### ISSUE THREAD

**Issue by nado** [gnome-mpv/gnome-mpv#153]
Hi,

Overview Description:
I cant build gnome-mpv on my gentoo, i tried with the ebuild and filed an issue for the repo (https://github.com/rilian-la-te/lxde-gtk3-overlay/issues/1).

Steps to Reproduce:
1. git clone
2. ./autogen.sh

Actual Results:
```
configure.ac:34: error: macro APPSTREAM_XML is not defined; is a m4 file missing?
/usr/share/aclocal/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
configure.ac:34: the top level
autom4te-2.69: /usr/bin/m4 failed with exit status: 1
aclocal-1.15: error: echo failed with exit status: 1
```
Expected Results:
Build success

Version: latest (commit https://github.com/gnome-mpv/gnome-mpv/commit/39dd07fcf1b12fecd4de40fa7e24ecfe84bdc780)

Additional Information:
I dont know what is causing that, so ask and I’ll give whatever info you need.

**Comment by region51** [comment]
>configure.ac:34: error: macro APPSTREAM_XML is not defined; is a m4 file missing?

appstream-glib (build)

**Comment by nado** [comment]
Oh, ok anyway gtk+3-3.20 is not yet in the repos. I’ll come back when they’ll be updated.
I will already update the ebuild for appstream-glib which is also not in the dependencies.
