### ISSUE TITLE
Add a new language for translation in Zanata

### ISSUE THREAD

**Issue by fitojb** [gnome-mpv/gnome-mpv#154]
Hi,

I’d like to start translating gnome-mpv into Catalan. However, I haven’t been able to do so since Zanata’s UI is so confusing. [Apparently](https://zanata.atlassian.net/browse/ZNTA-366) I’ve got to request somebody else to add the language, which is acceptable and all, but Zanata *should let me request the addition from its very UI*, as Transifex does—I shouldn’t need to nag project maintainers for this. So, if you can, can you please add Catalan somehow so I can start the translation?

Thanks.

**Comment by gnome-mpv** [comment]
Added.

https://translate.zanata.org/webtrans/translate?project=gnome-mpv&iteration=master&localeId=ca&locale=en#view:doc;doc:gnome-mpv

**Comment by fitojb** [comment]
Thanks!
