### ISSUE TITLE
Do not use intltools with .gschema.xml files

### ISSUE THREAD

**Issue by xuzhen** [gnome-mpv/gnome-mpv#156]
https://wiki.gnome.org/HowDoI/GSettings
>There are several examples in the wild of projects that use .gschema.xml.in files. This is almost always wrong. You should absolutely never use intltool or itstool-based XML "translation merging" functionality with schema files. It is also typically unnecessary to use expansions such as @GETTEXT_PACKAGE@, as these things are not configurable by the user (and shouldn't be).

**Comment by gnome-mpv** [comment]
I suspect that this information is out of date. It's probably saying that you shouldn't have intltool treat gsettings schemas as XML files. intltool >= 0.50 has support for gsettings schemas so it should work properly.

**Comment by gnome-mpv** [comment]
I asked on IRC, and I was told that it is okay to use intltool to only extract strings but not merge them back.
