### ISSUE TITLE
Screensaver (screen blanking after idle time) is not inhibited when using wayland

### ISSUE THREAD

**Issue by razerraz** [gnome-mpv/gnome-mpv#158]
Overview Description:

Actualy, nothing prevent screen blanking when using mpv on wayland
Since mpv developpers seems to refuse adding dbus deps (the only actual way to inhibit screen blanking on wayland), it should be a good idea to let gnome-mpv take care of that.
I have plans if my schedule permit so to contribute, adding the thing using GDBus.
Thanks to tell what you think of that

Steps to Reproduce:
1. launch gnome-mpv
2. wait idle time
3. 

Actual Results:
the screen go blank
Expected Results:
screensaver should be inhibited
Version:
all
Additional Information:
none

**Comment by gnome-mpv** [comment]
This has already been implemented some time ago, but it's broken right now. I'm working on fixing it.

**Comment by intagger** [comment]
So, what is the status of the issue?

**Comment by razerraz** [comment]
It has been fixed long time ago, at least for me

**Comment by noam09** [comment]
I'm currently experiencing an issue which is quite the opposite. When a fullscreen video has finished playing, GNOME-MPV remains in fullscreen mode, and this prevents sleep/suspend/screensaver. 
Is there a way to control this or should I open a separate issue? I'm pretty sure this issue only appeared during the past couple months, but I may be mistaken.

**Comment by gnome-mpv** [comment]
> I'm currently experiencing an issue which is quite the opposite. When a fullscreen video has finished playing, GNOME-MPV (also on Wayland) remains in fullscreen mode, and this prevents sleep/suspend/screensaver.

This is normal. gnome-mpv does not automatically exit fullscreen mode when the file finishes. However, this shouldn't prevent the machine from suspending.

> Is there a way to control this or should I open a separate issue? I'm pretty sure this issue only appeared during the past couple months, but I may be mistaken.

There is no built-in mechanism to do that yet, but you can get the same effect with the following Lua script.

````
require 'mp'

function handle_idle_active(name, value)
	if mp.get_property_bool(name)
	then
		-- WARNING: This mechanism should not be considered stable yet.
		-- It may change from version to version.
		mp.commandv('script-message', 'gmpv-action', 'leave-fullscreen')
	end
end

mp.observe_property('idle-active', bool, handle_idle_active)
````

**Comment by noam09** [comment]
I will keep testing to understand what's preventing suspend, it's odd because the screen lock/screensaver really does kick in despite gnome-mpv remaining fullscreen, so I'm not quite sure what could be causing it.
Anyway, the Lua script for exiting fullscreen when the video finishes is a great help in itself, so thank you!
