### ISSUE TITLE
missing translation

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#161]
_Add Lua Script_
???

**Comment by region51** [comment]
@gnome-mpv is there some more
![screenshot from 2016-05-10 21-55-18](https://cloud.githubusercontent.com/assets/13280183/15158847/5e63d15a-16fa-11e6-9fff-c238ebd88957.png)

No/Yes

**Comment by region51** [comment]
@gnome-mpv 
P.S. can add + tooltip?

**Comment by region51** [comment]
@gnome-mpv ping??? ^^^
P.S. Thank you in advance.

**Comment by gnome-mpv** [comment]
Seems to work fine on my machine.

![2016-05-11-155008_1680x1050_scrot](https://cloud.githubusercontent.com/assets/8312231/15175375/2c3b46ea-1790-11e6-87c6-a4abda88b26f.png)

Those buttons are standard gtk buttons, so translations will come directly from gtk. You might be missing some translation files for gtk.

**Comment by region51** [comment]
hmmm

**Comment by region51** [comment]
@gnome-mpv :+1:  everything is fine.
i'm stupid .
