### ISSUE TITLE
mpv version >= 0.17 in dependencies do not correspond to the API version requirement

### ISSUE THREAD

**Issue by xuzhen** [gnome-mpv/gnome-mpv#168]
In configure.ac, mpv API version requirement is >= 1.20
In https://github.com/mpv-player/mpv/blob/master/DOCS/client-api-changes.rst, API version 1.20 correspond to mpv 0.12.0

**Comment by gnome-mpv** [comment]
The latest client API version in stable release of mpv is 1.20, so that's the highest I can require for now. gnome-mpv depends on some changes introduced in mpv >= 0.17 to work properly though.

**Comment by region51** [comment]
_In the next release will be client library >=1.21_
