### ISSUE TITLE
[Feature request] Better UX in playlists

### ISSUE THREAD

**Issue by paulcarroty** [gnome-mpv/gnome-mpv#170]
Overview Description: 
Gmpv shows only links in playlist menu, which is not readable and hard to understand which stream you need to play. Names by default will be looks really better.

Steps to Reproduce:
1. Open playlist
2. Press F9

Actual Results: 
![screenshot from 2016-05-21 14-13-01](https://cloud.githubusercontent.com/assets/1550705/15448088/4815a4ce-1f5f-11e6-807d-8a3126a018b5.png)

Expected Results: Names of playlist media

Version: 0.9

Part of playlist:

```
#EXTINF:-1,MAXXI TV
http://46.149.185.7:8000/play/ch033
#EXTINF:-1,Football 1
http://46.149.185.7:8000/play/ch086
#EXTINF:-1,Fox HD
http://46.149.185.7:8000/play/ch121
#EXTINF:-1,Viasta Sport HD
http://46.149.185.7:8000/play/ch093
#EXTINF:-1,A-ONE
http://46.149.185.7:8000/play/ch102
#EXTINF:-1,TV 1000 Megahit HD
```

**Comment by region51** [comment]
https://github.com/gnome-mpv/gnome-mpv/issues/31

**Comment by region51** [comment]
@gnome-mpv hi
![screenshot from 2016-05-21 21-44-24](https://cloud.githubusercontent.com/assets/13280183/15450171/95aa2ff0-1f9d-11e6-8a4b-c2138d509516.png)
gnome-mpv (0a75dc838731827e7dd8c39c45279822dc59467f)
???

**Comment by region51** [comment]
Oops, sorry
![screenshot from 2016-05-21 21-55-50](https://cloud.githubusercontent.com/assets/13280183/15450216/f035ac3c-1f9e-11e6-9ec0-c7a80f3aaad4.png)
@gnome-mpv :+1:
