### ISSUE TITLE
[Feature request]: Ellipsis character (…) for long text

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#172]
Show ellipsis if names of playlist are too wide
![screenshot from 2016-05-24 10-51-48](https://cloud.githubusercontent.com/assets/13280183/15498177/2e1280ca-21a7-11e6-920d-60d876b02507.png)
Maybe it's worth to try, do you agree?
P.S. Sorry for my bad English.

**Comment by gnome-mpv** [comment]
No. That doesn't seem very useful, and it'll probably take a lot of work to implement.

**Comment by region51** [comment]
@gnome-mpv OK.
