### ISSUE TITLE
ERROR:gmpv_video_area.c:269:gmpv_video_area_get_xid: assertion failed: (window)

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#173]
-gnome-mpv version: (04efbc3f1090a69eb33615af601846718599e821)
-gtk version: 3.18.9
-linux distribution: F23

```
[maxim@localhost ~]$ G_MESSAGES_DEBUG=all gnome-mpv
(gnome-mpv:8813): Gtk-DEBUG: Connecting to session manager
**
ERROR:gmpv_video_area.c:269:gmpv_video_area_get_xid: assertion failed: (window)
Aborted (core dumped)

```

**Comment by region51** [comment]
@gnome-mpv reason :-1: :-1: :-1: :
![screenshot from 2016-05-24 13-20-13](https://cloud.githubusercontent.com/assets/13280183/15500686/8827f63e-21b2-11e6-891b-6d11fccc9fa6.png)

**Comment by gnome-mpv** [comment]
If you triggered this bug in previous versions, you can get gnome-mpv working again by resetting the GSettings keys `playlist-width` and `width`:

````
gsettings reset io.github.GnomeMpv.window-state playlist-width
gsettings reset io.github.GnomeMpv.window-state width
````

**Comment by region51** [comment]
@gnome-mpv I know
