### ISSUE TITLE
missing translation (unrecognized file format)

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#174]
![screenshot from 2016-05-24 22-46-06](https://cloud.githubusercontent.com/assets/13280183/15517651/971423bc-2201-11e6-9e26-641127b77122.png)
?

**Comment by gnome-mpv** [comment]
That string comes directly from mpv so translation would have to be done in mpv.

**Comment by region51** [comment]
>so translation would have to be done in mpv.

This is bad.
