### ISSUE TITLE
Control buttons

### ISSUE THREAD

**Issue by ElvisPresly** [gnome-mpv/gnome-mpv#175]
Can be to increase the size of control buttons? Or to give such chance in settings, for example: small, big, average?

**Comment by region51** [comment]
or hide all controls

**Comment by gnome-mpv** [comment]
@region51: 18c715ab82183110c26e20110746977ac5080d83

**Comment by gnome-mpv** [comment]
@ElvisPresly: This would be better done using a theme. You can adjust the size of the buttons to some extent by changing the amount of padding. The theme can also be loaded on a per-application basis using the `GTK_THEME` environment variable.
