### ISSUE TITLE
Problem with sound pointer in gnome-mpv

### ISSUE THREAD

**Issue by behroozramezani** [gnome-mpv/gnome-mpv#180]
Overview Description:
Hello
I have Arch Linux and Cinnamon when ever I'm using gnome-mpv the sound pointer is diable so I can not control volume from application
Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Version:0.7

Additional Information:

**Comment by gnome-mpv** [comment]
The volume button will be enabled once you open a file.

**Comment by region51** [comment]
@gnome-mpv 
>The volume button should be enabled once you open a file.

This problem was in version 0.7

>Arch Linux
>>Version:0.7

why 0.7???
https://aur.archlinux.org/packages/gnome-mpv
https://aur.archlinux.org/packages/gnome-mpv-git

**Comment by gnome-mpv** [comment]
>I confirm. This problem was in version 0.7
>#124

The bug should have already been fixed then.
