### ISSUE TITLE
Support watching multiple videos at the same time

### ISSUE THREAD

**Issue by razerraz** [gnome-mpv/gnome-mpv#181]
Overview Description:
It is impossible to load another instance of gnome-mpv, with one already loaded.
Steps to Reproduce:
1. Load a first instance by double clicking a video in nautilus
2. Double click another video in nautilus
3.

Actual Results:
The second video selected will be loaded in the first instance of gnome-mpv
Expected Results:
Having the two videos in two separate gnome-mpv windows 
Version:
0.9 (git version)
Additional Information:
mpv-git, archlinux, wayland

**Comment by TingPing** [comment]
I'd like that a dialog pops up in the existing window asking what to do, open a new window or open an existing window with a checkbox for *"Do this every time"* or such.

**Comment by gnome-mpv** [comment]
I put a new option to control this in preferences instead of a dialog box. The default is to only allow single instance.

**Comment by razerraz** [comment]
well done, working perfectly
thanks a lot !
By the way default fullscreen mode support you implement recently is well appreciated too ;)
Chears

**Comment by region51** [comment]
@gnome-mpv hi, please add translation
>Allow multiple instances

![screenshot from 2016-05-29 11-58-13](https://cloud.githubusercontent.com/assets/13280183/15632274/16e6504c-2595-11e6-8b0d-0aa26043aa31.png)

**Comment by gnome-mpv** [comment]
@region51: Done.

**Comment by region51** [comment]
@gnome-mpv Thanks!

**Comment by region51** [comment]
@gnome-mpv please sync translation in git.
