### ISSUE TITLE
Add support of handling mouse clicks

### ISSUE THREAD

**Issue by warmsun0220** [gnome-mpv/gnome-mpv#19]
Do you have any plans to add support of handling mouse clicks, such as：“Double click to go full screen” and “one click to pause”?

**Comment by gnome-mpv** [comment]
Yes. That should be doable.

**Comment by gnome-mpv** [comment]
Mouse clicks can now be bound using input.conf. There are also two new default bindings. Double clicking the left button will toggle fullscreen. Single clicking the right button will play/pause the file.

**Comment by warmsun0220** [comment]
Thank you！
