### ISSUE TITLE
Hide playlist by default

### ISSUE THREAD

**Issue by gnul** [gnome-mpv/gnome-mpv#194]
When I open a video with this the playlist is toggled on every time for some reason. Can I add a command to preferences extra MPV options field or something to hide it on starting the program by default?

Version: 0.7-1

**Comment by gnome-mpv** [comment]
Try v0.9. If you're using Ubuntu, you can install it from this [PPA](https://launchpad.net/%7Exuzhen666/+archive/ubuntu/gnome-mpv).

**Comment by gnul** [comment]
Yes the update fixed the issue, thanks.
