### ISSUE TITLE
on screen controller display (OSC)

### ISSUE THREAD

**Issue by Joseph65** [gnome-mpv/gnome-mpv#196]
mpv actually has its own controllers
![screenshot from 2016-06-25 15-13-57](https://cloud.githubusercontent.com/assets/12629965/16358925/3e523e76-3ae8-11e6-84d1-84e67b775dc4.png)

it would be nice if there be an option to display the OSC instead of the below controls.
similar to totem.

**Comment by gnome-mpv** [comment]
Done. You can use Ctrl+H to hide the default controls and put `--osc` in `Extra MPV Options` to enable mpv's OSC.

**Comment by Joseph65** [comment]
Are you going to update the ppa at https://launchpad.net/~xuzhen666/+archive/ubuntu/gnome-mpv
to reflect this changes

**Comment by TingPing** [comment]
@Joseph65 You can see releases here: https://github.com/gnome-mpv/gnome-mpv/releases

So when one comes out one could expect the PPA to be updated though it is not an official repo.

**Comment by Joseph65** [comment]
i just build and installed it and CTRL+H hides the controls but --osc doesn't toggle the osc
i put --osc on the extra mpv options

**Comment by gnome-mpv** [comment]
@Joseph65: Make sure your mpv version is 0.17 or newer.

**Comment by Joseph65** [comment]
im using mpv 0.18.0
~$ mpv --version
mpv 0.18.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Jun 26 12:02:37 UTC 2016
ffmpeg library versions:
   libavutil       55.26.100
   libavcodec      57.46.100
   libavformat     57.40.101
   libswscale      4.1.100
   libavfilter     6.46.102
   libswresample   2.1.100
ffmpeg version: N-80640-gf573acc

**Comment by region51** [comment]
@Joseph65 --osc=yes
![screenshot from 2016-07-10 21-55-43](https://cloud.githubusercontent.com/assets/13280183/16715467/15f6ef96-46e9-11e6-9b50-0861285d234b.png)

**Comment by gnome-mpv** [comment]
@Joseph65: Rebuild from git master again then run `G_MESSAGES_DEBUG=all gnome-mpv` and post the output here.

**Comment by Joseph65** [comment]
** INFO: Single instance negotiation is disabled

(gnome-mpv:18798): Gtk-WARNING **: Theme parsing error: gtk.css:1158:19: negative values are not allowed.
(gnome-mpv:18798): Gtk-DEBUG: Connecting to session manager

(gnome-mpv:18798): Gtk-WARNING **: Theme parsing error: gtk.css:1158:19: negative values are not allowed.
** (gnome-mpv:18798): DEBUG: Applying default option --osd-level=1
** (gnome-mpv:18798): DEBUG: Applying default option --softvol=yes
** (gnome-mpv:18798): DEBUG: Applying default option --force-window=yes
** (gnome-mpv:18798): DEBUG: Applying default option --input-default-bindings=yes
** (gnome-mpv:18798): DEBUG: Applying default option --audio-client-name=gnome-mpv
** (gnome-mpv:18798): DEBUG: Applying default option --title=${media-title}
** (gnome-mpv:18798): DEBUG: Applying default option --autofit-larger=75%
** (gnome-mpv:18798): DEBUG: Applying default option --window-scale=1
** (gnome-mpv:18798): DEBUG: Applying default option --pause=no
** (gnome-mpv:18798): DEBUG: Applying default option --ytdl=yes
** (gnome-mpv:18798): DEBUG: Applying default option --osd-bar=no
** (gnome-mpv:18798): DEBUG: Applying default option --input-cursor=no
** (gnome-mpv:18798): DEBUG: Applying default option --cursor-autohide=no
** (gnome-mpv:18798): DEBUG: Applying default option --softvol-max=100
** (gnome-mpv:18798): DEBUG: Applying default option --config=yes
** (gnome-mpv:18798): DEBUG: Applying default option --screenshot-template=gnome-mpv-shot%n
** (gnome-mpv:18798): DEBUG: Applying default option --config-dir=/home/user/.config/gnome-mpv
** INFO: Loading config file: /home/user/Downloads/apps/mpv/mpv.conf
** INFO: Loading input config file: /home/user/Downloads/apps/mpv/input.conf
** (gnome-mpv:18798): DEBUG: Using temporary input config file: /tmp/.UKCJKY
** INFO: Loaded input config file: /home/user/Downloads/apps/mpv/input.conf
** (gnome-mpv:18798): DEBUG: Applying extra mpv options: --osc=yes --loop inf --ytdl-format best
** (gnome-mpv:18798): DEBUG: Applying option --osc=yes
** (gnome-mpv:18798): DEBUG: Applying option --loop=inf
** (gnome-mpv:18798): DEBUG: Applying option --ytdl-format=best
** (gnome-mpv:18798): DEBUG: Attaching mpv window to wid 0x280003a
** INFO: Using mpv 0.14.0
** (gnome-mpv:18798): DEBUG: Setting volume to 100.000000
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "idle"
** (gnome-mpv:18798): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:18798): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:18798): DEBUG: Adding property: CanSeek
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:18798): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:18798): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:18798): DEBUG: Adding property: CanSeek
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "speed"
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "playlist-count"
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:18798): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:18798): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:18798): DEBUG: Adding property: CanSeek
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "fullscreen"
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "pause"
** INFO: Loading file (append=FALSE, update=TRUE): <PLAYLIST_ITEMS>
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "track-list"
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "idle"
** (gnome-mpv:18798): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:18798): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:18798): DEBUG: Adding property: CanSeek
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:18798): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:18798): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:18798): DEBUG: Adding property: CanSeek
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "speed"
** (gnome-mpv:18798): DEBUG: Received mpv property change event for "playlist-count"
** INFO: Terminating mpv

**Comment by gnome-mpv** [comment]
> ** INFO: Using mpv 0.14.0

It's using mpv 0.14.0. Try installing libmpv from this PPA (https://launchpad.net/~mc3man/+archive/ubuntu/xerus-media) and recompile.

**Comment by Joseph65** [comment]
fixed thanks
![screenshot from 2016-07-12 17-06-34](https://cloud.githubusercontent.com/assets/12629965/16785379/54451ac8-4853-11e6-956a-41a1cb50b2b1.png)

**Comment by emanuelserpa** [comment]
hey @gnome-mpv, thanks for your work.

anyway, it's possible to disable the floating controls in fullscreen too?

**Comment by gnome-mpv** [comment]
> anyway, it's possible to disable the floating controls in fullscreen too?

It's not yet possible, but I plan to implement it.
