### ISSUE TITLE
Flatpak Builds

### ISSUE THREAD

**Issue by TingPing** [gnome-mpv/gnome-mpv#197]
Sorry you don't seem to have a contact email so I'd just thought I'd let you and the community know that I made a flatpak repo including gnome-mpv.

The build file is here if you want to host your own or improve it: https://github.com/TingPing/flatpak-packages/blob/master/io.github.GnomeMpv.json

I am hosting it on my server so any users can run this to grab builds:

```sh
wget https://dl.tingping.se/keys/tingping.gpg
flatpak --user remote-add --gpg-import=tingping.gpg tingping https://dl.tingping.se/flatpak/ 
flatpak --user install tingping io.github.GnomeMpv
```

This allows users to install the latest versions without needing a modern distro for example. The sandboxing is not ideal and does have a few problems still but it might have its uses.

**Comment by region51** [comment]
@TingPing 
>Sorry you don't seem to have a contact email

gnome-mpv@openmailbox.org

**Comment by gnome-mpv** [comment]
Thank you. I added the instructions for Flatpak in README.
