### ISSUE TITLE
No volume control by mouse wheel

### ISSUE THREAD

**Issue by MichSt** [gnome-mpv/gnome-mpv#198]
Overview Description:
Volume control

Steps to Reproduce:
Bind keys ~/.config/mpv/input.conf
MOUSE_BTN3 add volume 2
MOUSE_BTN4 add volume -2

Actual Results:
No result but other buttons work

Expected Results:
))))

Version:
Gnome-mpv 0.9, Fedora 24, Gnome 3.20.2

**Comment by gnome-mpv** [comment]
This has already been fixed in 04efbc3f1090a69eb33615af601846718599e821.
