### ISSUE TITLE
"autofit" option has no effect

### ISSUE THREAD

**Issue by Hapoofesgeli** [gnome-mpv/gnome-mpv#20]
I use the "autofit=50%x50%" option in the config file but it seems to have no effect in gnome-mpv as seen in the screenshot.
![mpv-gnome](https://cloud.githubusercontent.com/assets/9002310/6711952/47391724-cd9f-11e4-8eee-c69de5c5bc5b.png)

**Comment by gnome-mpv** [comment]
I added support for `autofit`, but `autofit-larger`, `autofit-smaller`, and `geometry` are not yet implemented.

Note that this requires git version (https://github.com/mpv-player/mpv/commit/81a63545a031fdb5ca9fc459e59c9f4b02992511) of mpv to work.
