### ISSUE TITLE
Disabling csd causes segfault

### ISSUE THREAD

**Issue by mc4man** [gnome-mpv/gnome-mpv#202]
Overview Description:
Seen in Ubuntu 16.04
Steps to Reproduce:
1.Disable csd in preferences, restart gmpv
2.
3.

Actual Results:
segfaults
Expected Results:
should run without csd
Version:
git master
Additional Information:
Caused by commit 8db459a

**Comment by gnome-mpv** [comment]
This seems to be triggered by running inside Unity. I'll revert the commit for now.
