### ISSUE TITLE
Mouse scroll seeking not working on Wayland

### ISSUE THREAD

**Issue by francoism90** [gnome-mpv/gnome-mpv#207]
Overview Description:
How to enable mouse seeking scrolling?

Steps to Reproduce:
1. Add ~/.config/mpv/input.conf to Preferences, Keybindings
2. input.conf:
```
MOUSE_BTN0 ignore                      # don't do anything
MOUSE_BTN0_DBL cycle fullscreen        # toggle fullscreen on/off
MOUSE_BTN2 cycle pause                 # toggle pause on/off
MOUSE_BTN3 seek 10
MOUSE_BTN4 seek -10
MOUSE_BTN5 add volume -2
MOUSE_BTN6 add volume 2

AXIS_UP    seek 10
AXIS_DOWN  seek -10
AXIS_LEFT  seek 5
AXIS_RIGHT seek -5
```
3. Open video, no mouse buttons is working

Actual Results:
No mouse actions are working

Expected Results:
Seeking with the mouse scroll

Version:
Git (gnome-mpv-git)

Additional Information:
Arch Linux

Thanks :)

**Comment by gnome-mpv** [comment]
Run `G_MESSAGES_DEBUG=all gnome-mpv` and post the output here.

**Comment by francoism90** [comment]
@gnome-mpv  http://pastebin.com/GJSVtr40

Thanks :)

**Comment by francoism90** [comment]
Many thanks! It now works without any issues on Wayland (properly should told you)? :D

Is there anything that can be done on the interface resize when changing videos?

**Comment by gnome-mpv** [comment]
>Is there anything that can be done on the interface resize when changing videos?

You can disable that by putting `--autofit=0` in `Extra MPV options`.

**Comment by francoism90** [comment]
Thanks that did the trick. ```----geometry``` isn't working for me, although I've set this mpv.conf. Will try on the command line instead. :)

**Comment by gnome-mpv** [comment]
`--geometry` hasn't been implemented yet so it won't work. I'll work on it later.

**Comment by francoism90** [comment]
Ok, thanks and keep up the good work! :)

**Comment by gnome-mpv** [comment]
`--geometry` has been implemented in 44ed349a6d0bb93ea15de6c58143e3969004b7a1.

**Comment by francoism90** [comment]
Many thanks, going to test and let you know. :)

**Comment by francoism90** [comment]
@gnome-mpv Unfortunately the same bug happens again on `celluloid-git` (Wayland).

Do I need to open a new bug or can this be re-opened? :)

Thanks!

**Comment by gnome-mpv** [comment]
>Do I need to open a new bug or can this be re-opened? :)

It would be better to open a new issue.
