### ISSUE TITLE
Thank you for moving to gtk_headerbar()!

### ISSUE THREAD

**Issue by cjbayliss** [gnome-mpv/gnome-mpv#21]
G'day!

Thank you for moving to gtk_headerbar(). I love GNOME MPV, and now that it uses GTK Headerbar, it couldn't be better. GTK Headerbars work better on small (13in) HiDPI screens then the old window way.

I just wanted to say thank you, and couldn't find a better way of contacting.

Please continue to keep it simple!
Christopher

**Comment by gnome-mpv** [comment]
You're welcome!
