### ISSUE TITLE
Youtube playlists

### ISSUE THREAD

**Issue by ClashHexmen** [gnome-mpv/gnome-mpv#210]
Hi,
would it be possible to either display the video titles instead of "ytdl://sdhkjasdsabd" when a Youtube playlist is added or at least include an option to show an index in playlist, so that the user knows which item is number xx? In a playlist with 100+ items it is very hard to find a specific video right now.
Thanks!

**Comment by gnome-mpv** [comment]
mpv doesn't fetch the title of a video until it's played, so title of videos that hasn't yet been played will be unavailable. It should be possible to load the title of playlist entries in the background, but it's probably not going to be very easy to implement.

**Comment by gnome-mpv** [comment]
There seems to have been a change in mpv and/or youtube-dl, so titles will now be displayed when playing youtube playlists.
