### ISSUE TITLE
No cover notifications

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#213]
-gnome-mpv version: (50f3fcd0ca454b431dff75fb94d93830cc6f181c)
-gtk version: gtk3-3.20.8-1.fc24.x86_64
-linux distribution: F24

![screenshot from 2016-08-13 15-49-31](https://cloud.githubusercontent.com/assets/13280183/17643295/4ce20488-616e-11e6-9df3-c4df99589a80.png)

**Comment by region51** [comment]
P.S. lollypop
![screenshot from 2016-08-13 15-48-51](https://cloud.githubusercontent.com/assets/13280183/17643296/6a92e42a-616e-11e6-95ac-70da483d4be1.png)

**Comment by gnome-mpv** [comment]
This is not doable yet since mpv doesn't provide a way to access cover art data. See https://github.com/mpv-player/mpv/issues/3006.

**Comment by region51** [comment]
i got it!
