### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by wb9688** [gnome-mpv/gnome-mpv#214]
I'd like to contribute a Dutch translation, how could I do that?

**Comment by gnome-mpv** [comment]
I've just added [Dutch](https://translate.zanata.org/webtrans/translate?project=gnome-mpv&iteration=master&localeId=nl&locale=en-US#view:doc;doc:gnome-mpv) to Zanata. To start translating, you'll need to create an account on Zanata and [join a language team](http://docs.zanata.org/en/release/user-guide/languages/language-team/#join-a-language-team). After joining a team, you can go to [gnome-mpv's repo](https://translate.zanata.org/iteration/view/gnome-mpv/master) on Zanata to start translating. You can find more detailed instructions [here](http://docs.zanata.org/en/release/user-guide/translator-guide/).
