### ISSUE TITLE
Flatpak version theming bug

### ISSUE THREAD

**Issue by ahloiscreamo** [gnome-mpv/gnome-mpv#222]
The flatpak version of Gnome mpv have theming issues.

how do i remove the flatpak repo and the application completely?(fedora 24).thanks

**Comment by TingPing** [comment]
```sh
flatpak --user uninstall io.github.GnomeMpv
flatpak --user remote-delete tingping`
```

**Comment by ahloiscreamo** [comment]
Ok thanks TingPing
