### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by gyeben** [gnome-mpv/gnome-mpv#223]
Hi! I would like to contribute a Hungarian translation.

**Comment by gnome-mpv** [comment]
I've added Hungarian to Zanata: https://translate.zanata.org/webtrans/translate?project=gnome-mpv&iteration=master&localeId=hu&locale=en-US#view:doc;doc:gnome-mpv

Please follow the instructions [here](http://docs.zanata.org/en/release/user-guide/translator-guide/) to start translating.
