### ISSUE TITLE
Support for Portuguese (Brazil)

### ISSUE THREAD

**Issue by israelfaustino** [gnome-mpv/gnome-mpv#228]
Hello!
I'd like to ask the team to add Brazilian Portuguese  to the Zanata page. I'd love to help with the translation.

**Comment by gnome-mpv** [comment]
Thank you. I've added Brazilian Portuguese to Zanata. You can find gnome-mpv's page [here](https://translate.zanata.org/iteration/view/gnome-mpv/master?dswid=-122). Follow the instructions [here](http://docs.zanata.org/en/release/user-guide/translator-guide/) to start translating.
