### ISSUE TITLE
[opengl-cb] retrieving framebuffer depth: OpenGL error INVALID_OPERATION.

### ISSUE THREAD

**Issue by simonbcn** [gnome-mpv/gnome-mpv#230]
Arch linux 64 bits
GNOME Shell 3.22.1
mpv installed from sources git version git-0af8811
gnome-mpv installed from sources git version (compiled now)

When I start gnome-mpv it shows in console: `** Message: [opengl-cb] retrieving framebuffer depth: OpenGL error INVALID_OPERATION.`

Why `gnome-mpv` doesn't use `wayland` video output?

**Comment by TingPing** [comment]
> Why gnome-mpv doesn't use wayland video output?

The opengl output works on all platforms and is generally recommended. Even the docs for the wayland output call it a fallback for opengl.

**Comment by gnome-mpv** [comment]
@simonbcn: Does `mpv --vo=opengl --idle --force-window` produce the same error message?

**Comment by simonbcn** [comment]
Yes, it fails too. I suppose the error is in mpv then.
