### ISSUE TITLE
Support Meson build system

### ISSUE THREAD

**Issue by TingPing** [gnome-mpv/gnome-mpv#231]
This is just more of a question of if you would be interested in this. [Meson](http://mesonbuild.com/) is a relatively new build system that has been gaining some buzz in the Gnome community.

Some of the pros:
- Extremely fast
- Simple and less error prone language
- Portable to Windows
- Less historical baggage

Some of the cons:
- Depends upon Python3 and Ninja
- Change in workflow

If you are interested I could pretty quickly port it and it would be possible to support both build systems
at the same time. Just wanted to know if I would be wasting my time.

**Comment by gnome-mpv** [comment]
Sounds interesting, but I would prefer to wait until at least one core GNOME package switched to Meson before changing our build system.

**Comment by TingPing** [comment]
K. GStreamer officially supports it and I personally am working on Gnome-Builder supporting it. Maybe around next release cycle.

**Comment by TingPing** [comment]
So it has been a few months, Meson has had a few polishing releases and a dozen projects have added support for it: https://github.com/mesonbuild/meson/wiki/Users

Interested in me making a PR for this?

**Comment by gnome-mpv** [comment]
Yes. Please go ahead and submit a pull request.

**Comment by TingPing** [comment]
To be clear you would want to keep AutoTools around right, If so I'll have to modernize its gettext usage also.

**Comment by gnome-mpv** [comment]
If it's not too much work, I think it would be good to keep autotools around for a while.

**Comment by TingPing** [comment]
Implemented in 7a4917ec3962a3edff51e53743c11ade0d32e3a0
