### ISSUE TITLE
vo=wayland doesn't work

### ISSUE THREAD

**Issue by simonbcn** [gnome-mpv/gnome-mpv#233]
Arch Linux 64 bits
GNOME Shell 3.22.1
gnome-mpv-git 0.10.r28.gfb83651-1 (installed from [AUR package](https://aur.archlinux.org/packages/gnome-mpv-git/))
mpv-git 44074.ga6da4fa-1(installed from [AUR package](https://aur.archlinux.org/packages/mpv-git/))

I have set in mpv.conf: `vo=wayland` and I have set the same in `Extra MPV options` in the preferences dialog.
I have executed gnome-mpv from console in debug mode and this is the relevant part of output:
```
....
** INFO: Loaded input config file: /home/juan/.mpv/input.conf
** (gnome-mpv:17740): DEBUG: Applying extra mpv options: --vo=wayland
** (gnome-mpv:17740): DEBUG: Applying option --vo=wayland
** (gnome-mpv:17740): DEBUG: Attaching mpv window to wid 0xffffffff
** INFO: Using mpv git-a6da4fa
** INFO: The chosen vo is wayland but the display is not X11; forcing --vo=opengl-cb and resetting
** INFO: Terminating mpv
....
```
Wayland output doesn't need X11.

**Comment by gnome-mpv** [comment]
This is intentional. `mpv` doesn't provide a way to embed its window in Wayland, so `opengl-cb` is needed for embedding.
