### ISSUE TITLE
it doesn't respect "keep-open=no"

### ISSUE THREAD

**Issue by simonbcn** [gnome-mpv/gnome-mpv#234]
Arch Linux 64 bits
GNOME Shell 3.22.1
gnome-mpv-git 0.10.r28.gfb83651-1 (installed from [AUR package](https://aur.archlinux.org/packages/gnome-mpv-git/))
mpv-git 44074.ga6da4fa-1(installed from [AUR package](https://aur.archlinux.org/packages/mpv-git/))

I have set in mpv.conf: `keep-open=no` and I have set the same in `Extra MPV options` in the preferences dialog but `gnome-mpv` remains open when the playback ends.

**Comment by mc4man** [comment]
Sure it does, keep-open is in relation to the video, not the window. The default is no anyway. To see pass the extra option --keep-open=yes
In mpv the psuedo-gui window is kept open by idle=yes, the default being idle=once

**Comment by simonbcn** [comment]
`gnome-mpv` doesn't respect that parameter either. When the playback ends it remains open.

**Comment by hhhorb** [comment]
+1, it's a minor "bug", but I expect the window to close when the playlist is over. It can be confusing if, as I do, one uses the option `fullscreen=yes`. When the playlist is over, your left with a blank screen.

This is a wonderful front-end, thanks for the work, developers!

**Comment by gnome-mpv** [comment]
Looks like the correct solution is to use `--idle=once` instead of `--keep=open=no`. Handling `--keep-open` like mpv would be very confusing for a GUI application (with `--keep-open=no --idle=yes` the program would keep running without an associated window), so I think the current behaviour is appropriate.
