### ISSUE TITLE
 Add missing MIME types to desktop file?

### ISSUE THREAD

**Issue by infinity0** [gnome-mpv/gnome-mpv#236]
Over in [Debian bug 842900](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842900) the reporter has given quite a long list of MIME types that gnome-mpv could declare itself as supporting.

Would be good if you could take a look and add them as appropriate. Thanks!

**Comment by gnome-mpv** [comment]
I added most of the suggested MIME types except the ones below.

AFAIK these are not supported by mpv:
````
application/vnd.ms-wpl
application/x-quicktime-media-link
application/x-quicktimeplayer
application/x-shockwave-flash
application/xspf+xml
audio/x-ms-asx
audio/x-ms-wax
audio/x-pn-realaudio-plugin
audio/x-pn-windows-acm
image/vnd.rn-realpix
misc/ultravox
text/google-video-pointer
text/x-google-video-pointer
video/x-anim
video/x-ms-asf-plugin
video/x-ms-asx
video/x-ms-wvx
x-content/video-svcd
x-content/video-vcd
x-scheme-handler/icy
x-scheme-handler/icyx
````

I didn't add `video/vnd.divx` since it is redundant with `video/divx`, and the [divx website](http://labs.divx.com/book/export/html/16579) recommends using `video/divx`.
