### ISSUE TITLE
Update flatpak install instructions

### ISSUE THREAD

**Issue by moimael** [gnome-mpv/gnome-mpv#237]
Hi,

The commands listed in the README to install gnome mpv via flatpack do not work anymore on Fedora 25. I managed to modify some but I still get a gpg error in the end preventing me to install it.

Thanks !

**Comment by TingPing** [comment]
On Flatpak 0.6.13+ the commands would be:

```sh
flatpak --user remote-add gnome https://sdk.gnome.org/gnome.flatpakrepo
flatpak --user install gnome org.gnome.Platform 3.22

flatpak --user remote-add tingping https://dl.tingping.se/flatpak/tingping.flatpakrepo
flatpak --user install tingping io.github.GnomeMpv
```

As for any GPG issues I cannot reproduce on my end.

**Comment by gnome-mpv** [comment]
@moimael 
Which version of flatpak did you use? With flatpak 0.6.6, I got this error message: `error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)`. Updating to 0.6.13 fixes the problem.
