### ISSUE TITLE
Seeking does not work

### ISSUE THREAD

**Issue by Sesshu** [gnome-mpv/gnome-mpv#241]
Overview Description:
The seek bar is not clickable and the total length isn't displayed. Tested on git master with an MKV with h264.
I was able to identify the mpv commit that causes this mpv-player/mpv@7201fd7d08dd7f240e6f7c2584809bb4a723ab21
This bug is not present with earlier versions of mpv.

gnome-mpv log:
[gnome-mpv.txt](https://github.com/gnome-mpv/gnome-mpv/files/621048/gnome-mpv.txt)

**Comment by wb9688** [comment]
From where (eg. local, SFTP, HTTP, etc) are you playing the media?

**Comment by Sesshu** [comment]
I only tested it with files through file://, so locally.

**Comment by wb9688** [comment]
That's weird, it's probably a broken MPV build, but does it work when you
pass the `--force-seekable` option to MPV?

**Comment by Sesshu** [comment]
It doesn't work even with --force-seekable option.

**Comment by wb9688** [comment]
That's a MPV option, not a GNOME MPV option, so you should pass it as an
option to MPV, iirc in either GNOME MPV's setting there's an option to pass
things to MPV or there's a config file for MPV…

**Comment by Sesshu** [comment]
I meant seeking doesn't work even with that option. I used the settings dialog to pass the option to mpv.

I'm not too familiar with the source but isn't this caused by mpv having removed the length property and gnome-mpv still trying to use the length property to setup the seek bar?
I attached a patch which fixes the bug for the case that the file was just loaded. 
[duration.txt](https://github.com/gnome-mpv/gnome-mpv/files/621125/duration.txt)

**Comment by wb9688** [comment]
I was saying that just in case you've tried something like `gnome-mpv
--force-seekable`. I didn't know MPV removed the `length` property, but I'm
not the developer of this project. Does that patch only work with the
latest MPV or also with earlier versions?
