### ISSUE TITLE
An alternative gtk2 GUI?

### ISSUE THREAD

**Issue by wdlkmpx** [gnome-mpv/gnome-mpv#243]
I know this sounds ridiculous. But mpv is really the next generation media player for linux and is quite simple in design.

This could be an lxde app for example..

**Comment by TingPing** [comment]
- Gtk3 works fine on LXDE
  - There is even an option in preferences to disable client-side decorations so it fits in non-gnome environments
- LXDE is moving towards Qt anyway
- There is no advantage to Gtk2
- It would take a lot of work to make the application worse

**Comment by wdlkmpx** [comment]
Yeah you're right. The gnome guys are loonies
