### ISSUE TITLE
Video size on hidpi screen

### ISSUE THREAD

**Issue by CicoZhang** [gnome-mpv/gnome-mpv#245]
I am using XPS 13 with Ubuntu Gnome 16.10 and touch screen (hidpi). The video is not zoomed in.

Like the screenshot below. Does anyone know how to solve it?

![image](https://cloud.githubusercontent.com/assets/11710225/21603705/7a4d78f2-d19f-11e6-9180-1ffe0839b0ef.png)

**Comment by gnome-mpv** [comment]
Run gnome-mpv like this: `G_MESSAGES_DEBUG=all gnome-mpv` and post the log messages here.

**Comment by CicoZhang** [comment]
$ G_MESSAGES_DEBUG=all gnome-mpv
(gnome-mpv:21535): Gtk-DEBUG: Connecting to session manager
** (gnome-mpv:21535): DEBUG: Applying default option --osd-level=1
** (gnome-mpv:21535): DEBUG: Applying default option --softvol=yes
** (gnome-mpv:21535): DEBUG: Applying default option --force-window=yes
** (gnome-mpv:21535): DEBUG: Applying default option --input-default-bindings=yes
** (gnome-mpv:21535): DEBUG: Applying default option --audio-client-name=gnome-mpv
** (gnome-mpv:21535): DEBUG: Applying default option --title=${media-title}
** (gnome-mpv:21535): DEBUG: Applying default option --autofit-larger=75%
** (gnome-mpv:21535): DEBUG: Applying default option --window-scale=1
** (gnome-mpv:21535): DEBUG: Applying default option --pause=no
** (gnome-mpv:21535): DEBUG: Applying default option --ytdl=yes
** (gnome-mpv:21535): DEBUG: Applying default option --input-cursor=no
** (gnome-mpv:21535): DEBUG: Applying default option --cursor-autohide=no
** (gnome-mpv:21535): DEBUG: Applying default option --softvol-max=100
** (gnome-mpv:21535): DEBUG: Applying default option --config=yes
** (gnome-mpv:21535): DEBUG: Applying default option --screenshot-template=gnome-mpv-shot%n
** (gnome-mpv:21535): DEBUG: Applying default option --config-dir=/home/cico/.config/gnome-mpv
** (gnome-mpv:21535): DEBUG: Setting volume to 100.000000
** (gnome-mpv:21535): DEBUG: Using temporary input config file: /tmp/.TUCJTY
** (gnome-mpv:21535): DEBUG: Applying extra mpv options: hwdec=method,profile=opengl-hq
** (gnome-mpv:21535): DEBUG: Attaching mpv window to wid 0xffffffff
** INFO: The chosen vo is opengl but the display is not X11; forcing --vo=opengl-cb and resetting
** INFO: Terminating mpv
** (gnome-mpv:21535): DEBUG: Applying default option --osd-level=1
** (gnome-mpv:21535): DEBUG: Applying default option --softvol=yes
** (gnome-mpv:21535): DEBUG: Applying default option --force-window=yes
** (gnome-mpv:21535): DEBUG: Applying default option --input-default-bindings=yes
** (gnome-mpv:21535): DEBUG: Applying default option --audio-client-name=gnome-mpv
** (gnome-mpv:21535): DEBUG: Applying default option --title=${media-title}
** (gnome-mpv:21535): DEBUG: Applying default option --autofit-larger=75%
** (gnome-mpv:21535): DEBUG: Applying default option --window-scale=1
** (gnome-mpv:21535): DEBUG: Applying default option --pause=no
** (gnome-mpv:21535): DEBUG: Applying default option --ytdl=yes
** (gnome-mpv:21535): DEBUG: Applying default option --input-cursor=no
** (gnome-mpv:21535): DEBUG: Applying default option --cursor-autohide=no
** (gnome-mpv:21535): DEBUG: Applying default option --softvol-max=100
** (gnome-mpv:21535): DEBUG: Applying default option --config=yes
** (gnome-mpv:21535): DEBUG: Applying default option --screenshot-template=gnome-mpv-shot%n
** (gnome-mpv:21535): DEBUG: Applying default option --config-dir=/home/cico/.config/gnome-mpv
** (gnome-mpv:21535): DEBUG: Setting volume to 100.000000
** (gnome-mpv:21535): DEBUG: Using temporary input config file: /tmp/.5WE3SY
** (gnome-mpv:21535): DEBUG: Applying extra mpv options: hwdec=method,profile=opengl-hq
** INFO: Forcing --vo=opengl-cb
** INFO: Failed to retrieve property "current-vo" as string.
** INFO: Failed to retrieve property "current-vo" as string.
** (gnome-mpv:21535): DEBUG: Initialized opengl-cb
** Message: [opengl-cb] after init_gl: OpenGL error INVALID_OPERATION.
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:21535): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:21535): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:21535): DEBUG: Adding property: CanSeek
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "pause"
** INFO: Loading file (append=FALSE, update=TRUE): <PLAYLIST_ITEMS>
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "track-list"
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "volume"
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "idle"
** (gnome-mpv:21535): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:21535): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:21535): DEBUG: Adding property: CanSeek
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:21535): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:21535): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:21535): DEBUG: Adding property: CanSeek
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "speed"
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "volume"
** (gnome-mpv:21535): DEBUG: Received mpv property change event for "playlist-count"

**Comment by aquatix** [comment]
I have the same issue on Ubuntu-Gnome 16.10 on an XPS 15.

**Comment by gnome-mpv** [comment]
Can you test with 0.10? You can get it from [this PPA](https://launchpad.net/%7Exuzhen666/+archive/ubuntu/gnome-mpv).

**Comment by mmccool** [comment]
I'm seeing a similar problem in rviz, which is just an OpenGL program.   So this does not seem to be specific to video playback.   Also, it worked fine a few weeks ago, so some recent update broke it.

**Comment by aquatix** [comment]
Running gnome-mpv 0.11 on Ubuntu-Gnome 17.04 with Gnome 3.24 I still have the scaling issue: video is still only 1/4th of the screen (bottom left quarter). Still on Wayland.

**Comment by mmccool** [comment]
My problem turned out to be fixable by tweaking the QT5 settings.  The common thread in the applications that were misbehaving was that they were based on QT.   Basically I disable auto-scaling and forced it to use the system dpi (which I scaled to 1.5 in the control panel) and now both the UI elements AND the graphics are getting scaled properly.   (I will update this post with links and details when I can).

**Comment by TingPing** [comment]
> Running gnome-mpv 0.11 on Ubuntu-Gnome 17.04 with Gnome 3.24 I still have the scaling issue: video is still only 1/4th of the screen (bottom left quarter). Still on Wayland.

This fix was recent so that version doesn't have it yet of course.

**Comment by mmccool** [comment]
I know my post was about Qt and OpenGL windows, not video, but I thought it might be helpful since the symptoms seemed similar.   I apologize if my post is off-topic and useless ;)
