### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by KAMiKAZOW** [gnome-mpv/gnome-mpv#247]
Since the formal MPV 0.23 release the seeking bug (already fixed in master) reached regular Gnome MPV users. Although I consider compiling Gnome MPV from git, that is not an option for Joe User. Please make a 0.11 release that packagers pick up and distribute.

**Comment by gnome-mpv** [comment]
71c553ce1af53e607ae6d0ebd6c5e645183cd802
