### ISSUE TITLE
Can't compile v0.11 with Harfbuzz 1.4.x

### ISSUE THREAD

**Issue by elvetemedve** [gnome-mpv/gnome-mpv#248]
Overview Description:
Can't compile Gnome MPV v0.11 with Harfbuzz 1.4.x.

Steps to Reproduce:
1. Download and extract Gnome MPV v0.11
2. Install Harfbuzz 1.4.2
3. Compile the source

Actual Results:
> /usr/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'

Expected Results:
No errors.

Version:
Gnome MPV v0.11
Harfbuzz 1.4.2
Gcc 6.3.1

**Comment by gnome-mpv** [comment]
I can't reproduce this, but from a quick search, it seems that this is caused by harfbuzz's recent ABI change. You probably need to upgrade one or more of gnome-mpv's dependencies that uses harfbuzz.

**Comment by TingPing** [comment]
It is due to infinality being installed.

**Comment by elvetemedve** [comment]
It looks like infinality bundle was responsible for this issue. I removed it, now I can compile Gnome MPV again. Thanks for the help.

For those having the same issue, [here is a step-by-step guide](https://www.ostechnix.com/fix-harfbuzz-infinality-issue-arch-linux/) how to get rid of infinality bundle on Arch Linux. (The process is basically the same if you have other Linux distro.)
