### ISSUE TITLE
Unable to create GL context while in wayland

### ISSUE THREAD

**Issue by duvjones** [gnome-mpv/gnome-mpv#251]
So, for every time that I start gnome-mpv in a wayland session I get this message "Unable to create GL context" and every video that I toss at it will fail and keep from playing. 

I have tried fiddling with the 'mpv options' and have currently found no solution to this problem.  This is an issue that I have seen with both the package provided at RPMfusion.org and the flatpak .

That is really curious is that despite this, mpv proper has been operating fine. Also of note that while under X11, the program is operating fine. So I wonder if it's my system at all that is the cause.

If there is any way that anyone could be of assistance, I would greatly appreciate it.

**Comment by gnome-mpv** [comment]
Do you get the same error on X11 if you put `--vo=opengl-cb` in `Extra MPV options`?

**Comment by duvjones** [comment]
No, I do not. gnome-mpv operates without issue within X11 with that command in `Extra MPV options`

**Comment by gnome-mpv** [comment]
Run `glxinfo | grep OpenGL` and post the output here.

**Comment by duvjones** [comment]
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 13.0.3
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 13.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

**Comment by gnome-mpv** [comment]
>OpenGL version string: 2.1 Mesa 13.0.3

AFAIK GtkGLArea (which is what gnome-mpv use to render videos on Wayland)
requires at least OpenGL 3.2 to work. Your GPU appears to be too old to
support it.

You may still be able to get gnome-mpv to work in a Wayland session by forcing
it to use XWayland. You can do this by setting the env `GDK_BACKEND=x11`. You
may also need to set `--vo=xv` in `Extra MPV options`.

**Comment by duvjones** [comment]
Damn, nice to know
Thank you for the help.

**Comment by jalalsfs** [comment]
I still have the same issue with celluloid-0.20 on gnome 38 on Fedora 33.

**Comment by raingloom** [comment]
That workaround doesn't work for me.  I don't think this issue should have been closed.
