### ISSUE TITLE
Add support for the MPRIS tracklist interface

### ISSUE THREAD

**Issue by TingPing** [gnome-mpv/gnome-mpv#256]
Since `mpv` supports playlists it should map to MPRIS fairly well: https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html

This gnome-shell extension implements it: https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer

**Comment by gnome-mpv** [comment]
I looked at the spec and it seems the playlist interface is for media players that support multiple playlists. AFAIK `mpv` only supports a single playlist. Were you thinking of the [tracklist interface](https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html)?

**Comment by TingPing** [comment]
Err, sorry yea, Tracklist interface, which exposes the mpv playlist.
