### ISSUE TITLE
Settings is not saved

### ISSUE THREAD

**Issue by rilian-la-te** [gnome-mpv/gnome-mpv#26]
I am just build latest master and try to disable CSD and dark theme for this. Before reload it will be light CSD, but after reload it is dark again and with CSD.

**Comment by gnome-mpv** [comment]
I can't reproduce this bug. Can you try running gnome-mpv on the command line and see if there are any errors?

**Comment by rilian-la-te** [comment]
Here: (gnome-mpv:22045): Gtk-WARNING **: Toplevel size doesn't seem to directly depend on the size of the geometry widget from gtk_window_set_geometry_hints(). The geometry widget might not be in the window, or it might not be packed into the window appropriately


Where gnome-mpv is storing settings? Maybe it is a permissions issue...

**Comment by gnome-mpv** [comment]
$XDG_CONFIG_HOME/gnome-mpv/gnome-mpv.conf

**Comment by rilian-la-te** [comment]
I does not have this folder. Mkdir'ed it, all works. So, it is obliviously
a bug.
