### ISSUE TITLE
suggestion for interface about gnome-mpv

### ISSUE THREAD

**Issue by leipero** [gnome-mpv/gnome-mpv#260]
I would like to add few suggestions for gnome-mpv and I apologize if someone already did this and it got rejected. I think the path of "reinventing the wheel" is wrong path in any feild, so that's where I'm coming from in these suggestions.

Volume GUI:
It would be nice if gnome-mpv follow "standard" (de-facto standard) principle of other players, drag over volume and scroll = no need for unnecessary click, but there should stay an option as it is so people who want to click and drag, can do it.
This would be much less important issue if gnome-mpv (same as mpv) does not bind mouse wheel to seek forward-backward by default. I don't know who came up with this idea, but following "standard" for "volume up-down" on mouse wheel is most resonable thing to do.
So, just changing that default setting (without implementation of GUI suggestion above) would significantly improve "first impression" when user tries gnome-mpv, and would impact adoption rate of the player itself in positive manner.

Seek forward-backward:
Same as above, while I have no complain about aestetics of it, again "reinventing the wheel" principle is applied here. When user clicks on say 33rd minute, slider should go there by default, not in steps as it is at the moment. This is actually well done in mpv OSC itsef by default. I don't see valid reason (except maybe technical?) why would anyone want to change that behaviour, sicne fine-seeking is available on teh keyboard shortcuts by default as it should be (left-right arrows and so on).
Here, I also believe this would impact "fist-impression" and adoption rate in positive manner.

Also, another suggestion that can go towards "feature request" would make this player even better and, again, be positive change. Under preferences, option for subtitle encoding is really "a must" feature for users that are not native English speakers. I understand that could be technical challange, and might overcomplicate player, but I had to mention this sicne it would be positive change for player itself as those suggestions above.

Please dont take this as an negative, I think gnome-mpv is great frontend with great potential, and I'm thanful to people who made it and contributed to it. But main thing here is that whole point of GUI frontend is to make things easier for users, and "change for the sake of change" is never a good thing in my view.

Also, I would like to contribute to the translation, and that I will open in separate issue when i get time to do translation itself (no point in opening it now).

Thanks.

**Comment by gnome-mpv** [comment]
> Volume GUI:
> It would be nice if gnome-mpv follow "standard" (de-facto standard) principle of other players, drag over volume and scroll = no need for unnecessary click, but there should stay an option as it is so people who want to click and drag, can do it.

I'm not quite sure what "drag over volume and scroll" means. Do you mean putting the mouse cursor over the volume button and scrolling? That should be the current behavior.

> This would be much less important issue if gnome-mpv (same as mpv) does not bind mouse wheel to seek forward-backward by default. I don't know who came up with this idea, but following "standard" for "volume up-down" on mouse wheel is most resonable thing to do.

389f6a722c03c802ededdd77406f2ec9c368e3d0

>Same as above, while I have no complain about aestetics of it, again "reinventing the wheel" principle is applied here. When user clicks on say 33rd minute, slider should go there by default, not in steps as it is at the moment. This is actually well done in mpv OSC itsef by default. I don't see valid reason (except maybe technical?) why would anyone want to change that behaviour, sicne fine-seeking is available on teh keyboard shortcuts by default as it should be (left-right arrows and so on).

Can you elaborate on what you mean by "steps"? When the user click anywhere on the seek bar, the player should jump to the corresponding location in the file right away.

>Also, another suggestion that can go towards "feature request" would make this player even better and, again, be positive change. Under preferences, option for subtitle encoding is really "a must" feature for users that are not native English speakers. I understand that could be technical challange, and might overcomplicate player, but I had to mention this sicne it would be positive change for player itself as those suggestions above.

I'll consider adding this in the future.

**Comment by leipero** [comment]
> I'm not quite sure what "drag over volume and scroll" means. Do you mean putting the mouse cursor over the volume button and scrolling? That should be the current behavior.
Yes, like it is in majority of players. I thought it wasn't, maybe you should consider changing value to 5 -5 instead? It is 2 -2 it seems, so it's hard to notice. My bad on this one, but it's hard to notice, for this function, maybe it would be better for step to be 5 at minimum, or even 10.

Scrach that, I see you done no osd scroll to 10, that should fix it.

> Can you elaborate on what you mean by "steps"? When the user click anywhere on the seek bar, the player should jump to the corresponding location in the file right away.

Yeah, it does, strange, It got updated few hours ago, so maybe that was older version (from the Arch user repository), for me it did "steps", like, for example, when I click on 33rd minute, instead of seeking directly there, it did "move slider by steps of X minutes" (I don't know exact value, but let's say 1 minute). It works as you said now.

> I'll consider adding this in the future.

Yeah that would be really helpful for the player itself, and people who are not native English speakers and use those non-unicode titles, it is really important feature for those people (me included, i can do it via config, but most people don't bother with it, they search GUI option). I don't know how much would that impact complexity fo the player, but, jsut a suggestion :).

Thanks for fast reply, we can close this "issue" now.
