### ISSUE TITLE
Serbian Translation

### ISSUE THREAD

**Issue by leipero** [gnome-mpv/gnome-mpv#267]
Hello, I would like to contribute to Serbian translation.
Note: Since is dual-script language, if you add, you need to add sr_RS UTF-8  and sr_RS@latin UTF-8 locales. I would translate both.

**Comment by gnome-mpv** [comment]
Thank you. I've added Serbian to Zanata (sr-Cyrl and sr-Latn appear to be the codes used by Zanata). Please follow the instructions [here](https://github.com/gnome-mpv/gnome-mpv#contributing-translations) to start translating. Let me know if you have any questions.

**Comment by leipero** [comment]
Thanks, I wills tart translating as soona s they accept me into group :).

**Comment by gnome-mpv** [comment]
I've just added you directly to the project team, so you should be able to translate now.

**Comment by leipero** [comment]
Thanks, it's no longer locked to me, and they also accepted me in language translation group, so i should be able tos tart working on it now :).

**Comment by gnome-mpv** [comment]
>PS: Text is different compared to current MPV version on English, it also uses "MPV" in small letters "mpv". Will that be in new version?

The first few strings are descriptions for GSettings keys. They've been there for some time now, but they're not directly visible in the GUI. You can see them when using some tools such as `dconf-editor`.

The name "mpv" is officially written in lowercase, but I decided to capitalize them in "GNOME MPV" to be in line with GNOME's guidelines. I'm considering changing "MPV" to lowercase when it is used to refer to just `mpv` though.

**Comment by leipero** [comment]
Yeah, it became evident the further I've gone, ok now it makes sense, theya re descriptions for dconf-editor, your reply will be very heplful to me, since I know what is the purpose of it and I can translate it "in context" and not follow strict/literal translation (would be impossible), but just pass meaning, thanks.

Oh, i see, that is ofc. your choice how you will anme application. Yeah, I jsut run into standard problems when translating names of product/brand. I always stay to the principle of not translating brand name, but instead writting it as author created it, and there are multiple reasons for it, outside of branding, for consistency sake, but there I have mupltiple problems with people translating it in main projects (such as GNOME) so i have to keep that on mind. For example, they translated GNOME to GNOM (ГНОМ), and now there's dilemma, should it be "GNOM MPV" or when changing script "ГНОМ МПВ", or should I keep the name, or mix on Cyrl. script already translated "ГНОМ" with latin "MPV", since it is brand name.
