### ISSUE TITLE
dconf request: toggle use scroll for volume

### ISSUE THREAD

**Issue by mmccoy37** [gnome-mpv/gnome-mpv#274]
Could we get a config option in dconf to allow using scroll for [timeline,volume,none] ?

I think this is a feature that would be beneficial to many people, as VLC does scroll for volume, and some people dont want scoll to affect anything at all.

**Comment by gnome-mpv** [comment]
You can already configure key/mouse bindings using an input configuration file (`input.conf`). For example, you can make scrolling do nothing by putting the following lines in `input.conf`:
````
MOUSE_BTN3 ignore
MOUSE_BTN4 ignore
````

See https://mpv.io/manual/master/#command-interface for more details. You can make gnome-mpv load the file using the preferences dialog.

**Comment by mmccoy37** [comment]
I will look into it, thanks!
