### ISSUE TITLE
Feature Request: Prepaste urls to adress dialogue

### ISSUE THREAD

**Issue by lightonflux** [gnome-mpv/gnome-mpv#276]
When you copy an URL you have to paste it manually into the address dialogue (ctrl + l). 

Other applications like the GTK version of transmission copies the clipboard content automatically, if the URL scheme is right: [github search](https://github.com/transmission/transmission/search?utf8=%E2%9C%93&q=gtr_paste_clipboard_url_into_entry&type=)

**Comment by gnome-mpv** [comment]
In this implementation, all strings are automatically copied to the textbox. The dialog can handle plain paths as well as URLs, so any string is potentially valid.
