### ISSUE TITLE
opening the app shows two windows

### ISSUE THREAD

**Issue by fossfreedom** [gnome-mpv/gnome-mpv#278]
Overview Description:
![ubuntu budgie artful snapshot 1 running - oracle vm virtualbox_021](https://cloud.githubusercontent.com/assets/996240/26026546/2a8ccd4c-37f5-11e7-9d2c-743adecc5ee0.jpg)

Steps to Reproduce:
1. either double clicking in Files or opening from the menu

Actual Results:
opening from the menu shows a second window titled "(unavailable)"

Expected Results:
should just open in one window

If I double click from Files, the video plays in the second window - but the controls are shown in the first window - infact you see two lines of controls.

Version:
Ubuntu 17.10 - v0.11-1
Additional Information:

any thoughts on what is happening here - I must have a misconfiguration of somesort but non-the-wiser.

**Comment by gnome-mpv** [comment]
This may happen when the chosen vo doesn't support embedding. Try setting `vo=opengl-cb` in the config file.

**Comment by gnome-mpv** [comment]
I changed the default value for the `vo` option so that `vo`s that do not support embedding shouldn't be chosen automatically any more. Please re-open the issue if the problem persists.
