### ISSUE TITLE
Option to have static window size

### ISSUE THREAD

**Issue by ElectricGestalt** [gnome-mpv/gnome-mpv#279]
I like to maintain one size for gnome-mpv rather than have the window resize itself depending on the source material's resolution. Would it be possible to add this feature? 

The only issue I have with the player is having to manually resize after every instance I open. My use case is that I often leave the window on top of other windows like my browser, but for that to be usable, I need the window to be small enough to not obstruct the content of the background window.

**Comment by gnome-mpv** [comment]
You can already do that by putting `--autofit=0` in `Extra MPV Options`.

**Comment by ElectricGestalt** [comment]
Ah thank you very much! :)
