### ISSUE TITLE
Add controls for prev/next element?

### ISSUE THREAD

**Issue by terzag** [gnome-mpv/gnome-mpv#280]
Using gnome-mpv 0.11 from the Ubuntu 17.04 repos. Not a bug, rather a request.

Would it be possible to add buttons in the control bar to go to the previous/next item in the playlist? Currently, when in fullscreen, the only way to do it seem to manually move the position slider to the end.

**Comment by gnome-mpv** [comment]
You can do this with shortcuts. Press `<` to go to the previous playlist entry and `>` to go to the next one.

**Comment by terzag** [comment]
Thanks, that's good to know. But I'd still like to be able to do it with the mouse. ;) No plans to add this to the control bar?

**Comment by gnome-mpv** [comment]
No. The control bar is already using all standard icons for playback controls. There is nothing left that could be used for the new buttons.

**Comment by terzag** [comment]
Is that a GNOME widgets limitation? As icon themes provide icons like media-skip-forward/backward symbolics, I'd assume that GNOME would have multimedia widgets for this kind of action.

**Comment by gnome-mpv** [comment]
media-skip-forward/backward are being used for next/previous chapters. The buttons only show up if the file has chapters.

**Comment by terzag** [comment]
Oh, ok. Didn't realize that, I haven't tried a movie with chapters yet.

**Comment by terzag** [comment]
Sorry to bump the report after it's closed but I just noticed that Totem (default GNOME video player) has kind of a solution for this issue: the skip buttons are used for prev movie/chapter and next movie/chapter. I.e. if a video has chapters it'll move to the prev/next one while if it hasn't, the buttons will skip to the prev/next video.

Would this be a design you'd consider for gnome-mpv?

**Comment by gnome-mpv** [comment]
I think that makes it too easy to jump to the next file by mistake. You'll lose the cache for the original file if this happens, so it can take a while to get back to where you were if you're streaming.

I think your problem would be better solved by adding mouse bindings for moving between playlist entries (already possible), or gestures (WIP).

**Comment by terzag** [comment]
Ok. :/
