### ISSUE TITLE
V0.12 Can not scroll video using mouse wheel anymore

### ISSUE THREAD

**Issue by khurshid-alam** [gnome-mpv/gnome-mpv#285]
Overview Description:
Since 0.12 scrolling video using mouse wheel doesn't work anymore. It was default action in 0.11. Now it changes volume which is no use for me. How do I fix it?

Version: 0.12
Os: Ubuntu 17.10

**Comment by gnome-mpv** [comment]
You can use an input config file to rebind the mouse wheel. You can set a file to load in the preferences dialog under the keybindings section.

The following will restore the old behavior.
````
MOUSE_BTN3 no-osd seek -10
MOUSE_BTN4 no-osd seek 10
````

**Comment by khurshid-alam** [comment]
Thanks. That worked!!
