### ISSUE TITLE
Hardware acceleration 

### ISSUE THREAD

**Issue by reno-a** [gnome-mpv/gnome-mpv#287]
Overview Description:
Hello,
SMPlayer (other frontend) can use hardware acceleration (ex. VAAPI), with MPV.
Is it possible with GNOME-MPV? (if yes, How ?)
Thanks

Actual Results:
No difference with MPV alone

Expected Results:
Less CPU usage

Version:
gnome-mpv (0.11-1)

Additional Information:
Debian Stretch

**Comment by gnome-mpv** [comment]
Yes, you can enable hardware acceleration using the mpv option [`--hwdec`](https://mpv.io/manual/master/#options-hwdec). You can set this option either by using an mpv config file or putting the option in `Extra MPV Options`.

**Comment by reno-a** [comment]
Hello @gnome-mpv 
Thanks for your answer and information.
A suggestion, in GNOME usage (Keep it simple, Stupid), would it not be desirable auto activate the hardware acceleration ?

**Comment by TingPing** [comment]
Hardware accel has a lot of variables, type of accel, driver versions, hardware, etc. I believe `mpv` has it disabled by default for that very reason it is guaranteed to work well.

**Comment by reno-a** [comment]
Hello @TingPing,
It's perhaps why is no activate in default. With command line, all is possible.
However SMPlayer can do it and it's work well. If would be nice GNOME-MPV can do also.

**Comment by gnome-mpv** [comment]
I think it would be better to stick with mpv's default. Software decoding is fast enough for most cases, and it's not very difficult to enable hwdec if you really need it.

**Comment by Plasmodino** [comment]
It is always better to use hardware accelaration even if software decoding is fast enough. Software decoding drains the battery much faster on laptops.
