### ISSUE TITLE
Disable MPRIS for video playback

### ISSUE THREAD

**Issue by tdemin** [gnome-mpv/gnome-mpv#288]
MPRIS support is an awesome feature. But, well, if you use GNOME MPV for video playback, you may see something like this in the notification bar (since GNOME 3.22):
![screenshot from 2017-07-06 02-03-11](https://user-images.githubusercontent.com/26599554/27884889-4d4d9b44-61ef-11e7-81a0-fdf6d0719c1e.png)

Maybe it's better to check the media type before reporting data to MPRIS? Or an option to disable MPRIS API completely would be better?

**Comment by TingPing** [comment]
I think it would be better to set a useful title, play/pause are still useful features IMO.

**Comment by tdemin** [comment]
@TingPing that's a good idea, but we have nothing to set in most videos ;)

**Comment by gnome-mpv** [comment]
> Or an option to disable MPRIS API completely would be better?

Added in db5c15efd486af9bca6b17682c8eeaa92f9d89e8.
