### ISSUE TITLE
mpv: Unable to create a GL context

### ISSUE THREAD

**Issue by marcosps** [gnome-mpv/gnome-mpv#290]
Overview Description: After installing MPV from flathub (as described by README), it shows the message "Unable to create a GL context" in the center of the window. 

Steps to Reproduce:
1. Execute MPV flatpak
2.
3.

Actual Results:
Unable to create a GL context message. Can't play any video

Expected Results:
It should be able to play some video

Version:
Current flathub version

Additional Information:

**Comment by TingPing** [comment]
What GPU do you have and what driver?

**Comment by marcosps** [comment]
@TingPing 

odd, in my laptop, it runs nicely:
[marcos@Icarus ~]$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.1.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.1.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

But my desktop has a G33 intel driver, and have llvmpipe as mesa driver... I'll send you the exact information about that machine in a few days.

**Comment by TingPing** [comment]
Hmm G33 is much older so maybe it uses a different Mesa driver that isn't built.

**Comment by marcosps** [comment]
@TingPing here is the OpenGL in my desktop:

[marcos@Osiris ~]$ glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 4.0, 128 bits)
OpenGL version string: 2.1 Mesa 17.1.5
OpenGL shading language version string: 1.30
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 17.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

So, maybe MPV should check for the minimum GL requirements?

**Comment by marcosps** [comment]
More info:
[marcos@Osiris ~]$ flatpak run io.github.GnomeMpv 

(gnome-mpv:2): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.

** (gnome-mpv:2): CRITICAL **: Failed to initialize opengl-cb
** Message: [opengl-cb] glGetString(GL_VERSION) returned NULL.
** Message: [opengl-cb] OpenGL not initialized.

** (gnome-mpv:2): WARNING **: Failed to open scripts directory: /home/marcos/.var/app/io.github.GnomeMpv/config/gnome-mpv/scripts

So this seems to be a problem in mesa?

**Comment by TingPing** [comment]
I don't think `mpv` is the problem. Can you install and run `org.freedesktop.GlxInfo` from flathub?

**Comment by marcosps** [comment]
@TingPing here it is:

[marcos@Osiris ~]$ flatpak run org.freedesktop.GlxInfo  | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 4.0, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.0.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by marcosps** [comment]
@TingPing a new test today in the same machine worked, so I think the issue was solved in flatpak.
