### ISSUE TITLE
Add danish (da) translation

### ISSUE THREAD

**Issue by scootergrisen** [gnome-mpv/gnome-mpv#294]
I can haz danish translation? 🍔

**Comment by gnome-mpv** [comment]
I've added Danish to the repo on [Zanata](https://translate.zanata.org/webtrans/translate?project=gnome-mpv&iteration=master&localeId=da&locale=en-US&dswid=7534#view:doc;doc:gnome-mpv). You can follow the instructions [here](https://github.com/gnome-mpv/gnome-mpv#contributing-translations) to start translating. Let me know if you have any questions.

Thanks!

**Comment by scootergrisen** [comment]
Zanata says read only 😭 guess i'm not on the team.

**Comment by gnome-mpv** [comment]
I just added you to the project directly. You should be able to translate now.
