### ISSUE TITLE
Automatic subtitles loading

### ISSUE THREAD

**Issue by andrii1812** [gnome-mpv/gnome-mpv#295]
Recently I moved to Linux from Windows on my home workstation. On Windows I was using MPC player that had awesome feature: when you pressed D when opened video, player hit opensubtitles api and fetched list of subtitles by file name. 

It looks like that:
![Load screen](http://blog.opensubtitles.website/wp-content/uploads/select-subtitles.jpg)

It was super useful for loading subtitles in different languages for opened video. Now I'm using Gnome-MPV on my workstation and I really miss this feature. What do you think, is it a good feature to include? Maybe someone will come up with some suggestions/existing implementations?

**Comment by gnome-mpv** [comment]
You can do something similar with [Lua plugins](https://github.com/mpv-player/mpv/wiki/User-Scripts). There are a few plugins that can fetch and download online subtitles, e.g. `find_subtitles`, `dessubdb`, and `autosub`.
