### ISSUE TITLE
Random playback

### ISSUE THREAD

**Issue by gsantner** [gnome-mpv/gnome-mpv#297]
Overview Description:
Currently there is no option in UI for random playback.

Steps to Reproduce:
1. Open MPV
2. See no random controls

Actual Results: No Controls
Expected Results: Conrols
Version: 0.12
Additional Information: Maybe below the "Loop" action in context-menu inside playlist

**Comment by gnome-mpv** [comment]
A [pull request](https://github.com/gnome-mpv/gnome-mpv/pull/292) that added a menu item for shuffling the playlist was merged 2 weeks ago. Is this what you have in mind?

**Comment by gsantner** [comment]
exactly :D
Sorry,  searched Issues only
