### ISSUE TITLE
Window-scaling not working with custom key bindings

### ISSUE THREAD

**Issue by trinhno** [gnome-mpv/gnome-mpv#298]
Overview Description: I wanted to change the key bindings for window scaling so it's similar to MPC-HC. But after changing, window scaling doesn't work as expected. Only the video inside is scaled (incorrectly) and the frame outside is not.

Steps to Reproduce:
1. Add custom keybindings to a input.conf file
> Alt+3   set window-scale 0.5
> Alt+4   set window-scale 1.0
> Alt+5   set window-scale 2.0
2. Set it in Preferences.
3. Cycle through window scaling using the default Alt+0-2 and custom Alt+3-5 to see the difference. 

Actual Results: Only the video is scaled for custom bindings, not the window. Sometimes without video or glitches for 1x and 2x.

Expected Results: Default behavior even for custom key bindings.

Version: 0.12

Additional Information: [http://imgur.com/a/EB3KO](url)

**Comment by gnome-mpv** [comment]
Confirmed. As a temporary workaround, you can use this.
````
Alt+3 script-message gmpv-action win.set-video-size(0.5)
Alt+4 script-message gmpv-action win.set-video-size(1.0)
Alt+5 script-message gmpv-action win.set-video-size(2.0)
````

**Comment by trinhno** [comment]
Thanks for the quick reply. Unfortunately the workaround doesn't work on my computer. I'll stick to the default for the time being.
