### ISSUE TITLE
Gnome-mpv doesn't open mpv.conf when you directly double-click a video.

### ISSUE THREAD

**Issue by kaimian** [gnome-mpv/gnome-mpv#299]
Overview Description: As i said on the title.

Steps to Reproduce:
1. Open gnome-mpv and hit CTRL+P, select your mpv.conf location. CLOSE gnome-mpv.
2. Double-click a video on your folder and select a subtitle. You'll see the font isn't the same as the font informed on mpv.conf file.
3. Open gnome-mpv, Hit + and Open. Select the video. Select the subtitle. Everything will work as informed on mpv.conf file, including fonts, hardware acceleration and so on.

Actual Results: Doesn't read mpv.conf file when you double-click a video.

Expected Results: Should read the mpv.conf without needing to open the gnome-mpv before the video itself.

Version: I don't know. Fedora 26 Gnome-shell.

Additional Information: None

**Comment by gnome-mpv** [comment]
I can't reproduce this.

Does the mpv.conf get loaded if you open the file from command line (e.g. `gnome-mpv <filename>`) ?

**Comment by kaimian** [comment]
Yes, when you type "gnome-mpv filename" in the terminal it works. But when you double-click the filename in nautilus, it doesn't.

**Comment by gnome-mpv** [comment]
If you open a video by double-clicking and press `Ctrl+P`, does your `mpv.conf` remain selected in the dialog?

**Comment by kaimian** [comment]
No, if i press CTRL+P when double-click a video it shows some statistics about the video like FPS, resolution, etc. It's not the same window that shows when you simply open the gnome-mpv and press Ctrl+P.

**Comment by kaimian** [comment]
Oh man, i've just installed Debian Stretch so Fedora26 is gone... but i couldn't find the same window when i press Ctrl+P before, i was trying to make the gnome-mpv read the config file but i couldn't find the Ctrl+P window when the video was running.

**Comment by gnome-mpv** [comment]
Is the issue reproducible in Debian Stretch?

**Comment by gnome-mpv** [comment]
What I think happened was that `gnome-mpv` wasn't set as the default video player, so when you double-click a video file in nautilus, totem is launched instead. Pressing `Ctrl+P` in totem shows the statistics you mentioned earlier.

**Comment by kaimian** [comment]
Ohh, so the appearence of the two is the same. I think you may be right. Lol. I'm on debian with KDE right now so i couldn't test it. But, your logic make sense and, if you couldn't reproduce it i think you right. I thought it was a bug, sorry to take your time man.
