### ISSUE TITLE
Unable to run GnomeMPV from .desktop file if DBusActivatable=true

### ISSUE THREAD

**Issue by hubslave** [gnome-mpv/gnome-mpv#312]
**Overview Description:**
Hello friends,

I was not using GnomeMpv for a few days because of the incompatibility of my Nvidia drivers, so I could not reproduce this problem, but before that it seemed that in some point in time (maybe it was after some update, I am not sure) I could not launch GnomeMPV with double clicking on icon from my desktop environment. But from terminal it was working ok. Today, after downloading new nvidia updates and having GnomeMPV working again I was trying to reproduce this problem and I had the same issues as before. When launching GnomeMPV with double clicking on icon (from .desktop file) my mouse cursor went to "working/loading" state but nothing happened. While trying to run GnomeMPV from terminal everything was fine. So I created custom .desktop file, with only bare minimum lines, tried to execute it and it was working... Then I copied the whole content from original GnomeMPV .desktop file and started to comment line by line and everytime launching the application to find out which line is causing the problems. After some trial and error I found out that if I commented out line "DBusActivatable=true" I was able to launch GnomeMPV by double clicking the icon again.

I am not sure what could be the issue, I am not sure if this bug affects multiple users or only I misconfigured something in my system.

But I was looking for some information on the internet and I found this article stating that:

> As of GLib 2.38, it is now possible to have applications launched using D-Bus activation. 

( https://wiki.gnome.org/HowDoI/DBusApplicationLaunching )

While EL7.4 only have GLib 1.2.10 available in EPEL - So maybe it is lacking this feature?

**Steps to Reproduce:**
1. Install GnomeMPV flatpak on EL7.4
2. Try to run it out of the box - it wont work
3. Try to comment out DBusActivatable=true from .desktop file - it should work

**Actual Results:**
Does not launch application out of the box

**Expected Results:**
Should work out of the box

**Version:**
Latest available (stable branch)

**Additional Information:**
Enterprise Linux 7.4, Flatpak 0.8.7, glib 1.2.10

**Comment by hubslave** [comment]
I am not sure if this could be helpful, but it seems that Ubuntu had similar problems with their Font Viewer:

https://askubuntu.com/questions/804639/font-viewer-not-running-in-ubuntu-16-04

**Comment by TingPing** [comment]
> While EL7.4 only have GLib 1.2.10 available in EPEL - So maybe it is lacking this feature?

`glib2` not `glib`. EL7.4 comes with 2.50 which is very up to date and not remotely the problem.

**Comment by TingPing** [comment]
Anyway the problems are either: You use a broken launcher or you don't have a dbus daemon running maybe? Like GNOME-Shell should work fine of course.

**Comment by TingPing** [comment]
Ok I can confirm the problem is in `gnome-mpv` itself. Simply running `gnome-mpv --gapplication-service` never shows the window and exists.

**Comment by hubslave** [comment]
Yes you are right Glib2 is version 2.50. Sorry my bad, I did not know it is different package. :) I ran flatpak update few minutes ago and there came few new delta parts for GnomeMpv. I am not sure if they were related to this bug but at least on my system the issue is still present.

If there is some way how I could be helpful, for example by providing additional information or testing please let me know :)

**Comment by gnome-mpv** [comment]
>Ok I can confirm the problem is in gnome-mpv itself. Simply running gnome-mpv --gapplication-service never shows the window and exits.

Isn't that how it is suposed to work? When the application is started in service mode, it just waits until a DBus message is received that asks it to perform an action (e.g. create a new window). If no message is received after some time, it just exits.

I tested the flag with nautilus, and it seems to behave that way. No window is created, and after about 10 seconds it exits.

**Comment by TingPing** [comment]
Well it isn't exactly useful for launching the application to not do anything.

**Comment by gnome-mpv** [comment]
>Well it isn't exactly useful for launching the application to not do anything.

When an application is launched via DBus, the launcher is supposed to send it an `Activate` signal. After receiving the signal, a window is then created. The flag isn't supposed to be used directly by the user.

In any case, I tried the flatpak from your repo and it seems to work fine for me.

**Comment by hubslave** [comment]
Is there some action required to send the application "Activate" signal? In my case double clicking the icon is still not working.

**Comment by gnome-mpv** [comment]
>Is there some action required to send the application "Activate" signal? In my case double clicking the icon is still not working.

No. It should be completely transparent to the user. Double-clicking should already do that.

**Comment by gnome-mpv** [comment]
>That seems to be accurate but it doesn't work here. gapplication launch io.github.GnomeMpv for example doesn't work and I can confirm it calls activate: https://github.com/GNOME/glib/blob/master/gio/gapplication-tool.c#L365-L381

Strangely, the exact same command seems to work fine on my machine. I tried both flatpak and normal installation, and it works fine for me either way.

**Comment by hubslave** [comment]
@gnome-mpv on which Linux distribution do you test it? Do you use EL7.4 too? Is it possible that I changed some settings which could render gnome-mpv unusable when using this option?

**Comment by TingPing** [comment]
I'm on Fedora 26 btw.

**Comment by hubslave** [comment]
Hmm interesting, so its probably not caused by EL if you get the same behaviour on Fedora. 😐

**Comment by gnome-mpv** [comment]
>@gnome-mpv on which Linux distribution do you test it? Do you use EL7.4 too?

I tested it on Parabola (Arch derivative).

> Is it possible that I changed some settings which could render gnome-mpv unusable when using this DBus option?

I'm not aware of any settings like that.

**Comment by gnome-mpv** [comment]
I tried to reproduce the issue in a Fedora 26 VM without success. It would help a lot if you can try reproducing the issue in a VM and send me the image if you succeed.

**Comment by hubslave** [comment]
Ok I will try. I will post my result as soon as I am finished :) .

**Comment by hubslave** [comment]
By the way what specifically should I test besides double clicking the icon? Maybe the same command as @TingPing tried?

`gapplication launch io.github.GnomeMpv`

Also something else? Is there some way to make it print some verbose message to know what is happening?

**Comment by gnome-mpv** [comment]
@hubslave: Try running `G_MESSAGES_DEBUG=all flatpak run io.github.GnomeMpv --gapplication-service` in one terminal, then, within 10 seconds, run `gapplication launch io.github.GnomeMpv` in another terminal and see what happens.

**Comment by hubslave** [comment]
This is what I get on EL7.4:

1st Terminal:
`$ G_MESSAGES_DEBUG=all flatpak run io.github.GnomeMpv --gapplication-service
(flatpak run:21977): flatpak-DEBUG: No installations directory in /etc/flatpak/installations.d. Skipping
(flatpak run:21977): flatpak-DEBUG: Allowing dri access
(flatpak run:21977): flatpak-DEBUG: Allowing x11 access
(flatpak run:21977): flatpak-DEBUG: Allowing wayland access
(flatpak run:21977): flatpak-DEBUG: Allowing pulseaudio access
(flatpak run:21977): flatpak-DEBUG: Failed to run in transient scope: No systemd user session available, cgroups not available

(flatpak run:21977): flatpak-DEBUG: Running '/usr/libexec/flatpak-bwrap --args 18 /usr/libexec/flatpak-dbus-proxy --fd=15 unix:abstract=/tmp/dbus-ty78yFKBEL,guid=dd55f44d29e2717c38ad620959d7e675 /run/user/1000/.dbus-proxy/session-bus-proxy-CB1W7Y --filter --own=io.github.GnomeMpv --own=io.github.GnomeMpv.* --talk=org.gnome.SettingsDaemon.MediaKeys --talk=ca.desrt.dconf --talk=org.gtk.vfs.* --talk=org.freedesktop.portal.* --talk=org.gtk.vfs --own=org.mpris.MediaPlayer2.GnomeMpv.* --talk=org.gnome.SettingsDaemon'
** INFO: Single instance negotiation is disabled
(gnome-mpv:3): Gtk-DEBUG: Connecting to session manager
(gnome-mpv:3): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(gnome-mpv:3): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
** INFO: Starting GNOME MPV 0.12`

2nd Terminal:
`$ gapplication launch io.github.GnomeMpv
error sending Activate message to application: Timeout was reached`

Nothing happens, GnomeMpv does not start and both commands in both terminal sessions "end" on their own after few seconds.

**Comment by TingPing** [comment]
Ah the `allow-multiple-instances` option seems to be the problem.

**Comment by gnome-mpv** [comment]
>That option setting non-unique is just wrong, all that option should allow is opening multiple windows not multiple instances.

It's a leftover from before `--new-window` was implemented. I'll update it so that it just allow opening multiple windows.

**Comment by hubslave** [comment]
I confirm that it is now working like charm :) thank you very much for fix, I am amazed how fast you found out what was the problem :)
