### ISSUE TITLE
Installing development version

### ISSUE THREAD

**Issue by hubslave** [gnome-mpv/gnome-mpv#313]
**Overview Description:**

Hello friends,

I already have stable branch of GnomeMpv flatpak installed.

Today I wanted to install development version of GnomeMpv flatpak to be able to test in and eventually report found bugs.

I followed this instruction I found in Readme:

Development versions are also packaged:
`flatpak install https://dl.tingping.se/flatpak/gnome-mpv.flatpakref`

But after running this command in terminal I got `error: App io.github.GnomeMpv, branch master is already installed`

Which is strange because I never installed it, I installed just the one from stable branch.

Please I am doing something wrong or is the this flatpakref pointing to the same package as "stable" link or is there some other way how I should install it?

Thank you very much and have a nice day :)

**Steps to Reproduce:**
1. Run `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` and `flatpak install flathub io.github.GnomeMpv` in terminal to install stable branch
2. Run `flatpak install https://dl.tingping.se/flatpak/gnome-mpv.flatpakref` in terminal to install developer branch
3. Get `error: App io.github.GnomeMpv, branch master is already installed` in terminal

**Actual Results:**
Terminal says dev version is already installed (even though I did not install it, I installed only stable)

**Expected Results:**
Install dev version

**Version:**
Development

**Additional Information:**
Enterprise Linux 7.4, Flatpak ver. 0.8.7

**Comment by TingPing** [comment]
Uh, its already installed, so just update?

**Comment by hubslave** [comment]
Well I update frequently, I just though that the command `flatpak install https://dl.tingping.se/flatpak/gnome-mpv.flatpakref` points to another package than `flatpak install flathub io.github.GnomeMpv` (Or at least I understood it that way from reading readme)

Here is the citation from README.md:

**Flatpak**

Flatpak packages support multiple distributions and are sandboxed. Flatpak 0.9.5+ is recommended for best integration.

Stable releases are hosted on Flathub:

`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
`flatpak install flathub io.github.GnomeMpv`

Development versions are also packaged:

`flatpak install https://dl.tingping.se/flatpak/gnome-mpv.flatpakref`

**Comment by hubslave** [comment]
Eh I forgot to mention that I have stable branch installed now, by running these commands: 

`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
`flatpak install flathub io.github.GnomeMpv`

But installing development version by running this command:

`flatpak install https://dl.tingping.se/flatpak/gnome-mpv.flatpakref`

is telling me that `error: App io.github.GnomeMpv, branch master is already installed`

**Comment by TingPing** [comment]
They are different packages, you just have both installed.

`flatpak run io.github.GnomeMpv//master` for the development one
`flatpak run io.github.GnomeMpv//stable` for the stable one

**Comment by hubslave** [comment]
when trying to run `$ flatpak run io.github.GnomeMpv//stable`
I get this:
`error: app/io.github.GnomeMpv/x86_64/stable not installed`

**Comment by hubslave** [comment]
Please dont get me wrong, master is working fine for me, but I think that maybe there is a bug, that both these commands install master package? Even though the first one should install stable one?

**Comment by TingPing** [comment]
> (Even though I installed it the first method mentioned in readme - which should install stable branch)

So what does `flatpak install flathub io.github.GnomeMpv` output?

**Comment by hubslave** [comment]
`$ flatpak install flathub io.github.GnomeMpv`
`Installing: io.github.GnomeMpv/x86_64/stable from flathub`

![serveimage](https://user-images.githubusercontent.com/29800872/31311491-6faf52a6-abad-11e7-8ec2-2c6f18227485.jpg)

I am sorry... All the time I thought that I am using stable package... Or at least that is what I remembered to install... I should probably sleep more, maybe my memory would also improve... :wink:

Thank you very much for clarification. Now I see the commands are working correctly, It was just my mistake.

**Comment by TingPing** [comment]
You found that dbus issue before release so your mistake was for the better =)

**Comment by hubslave** [comment]
😄 Well I must say that the master branch was pretty rock-solid experience for me, this dbus issue was the only small mistake I ever encountered, so I will continue using this branch and report any further bugs I would encounter :)

**Comment by hubslave** [comment]
You guys are doing pretty amazing job. Hats down. I am sorry that I am not able to help with coding, but I am not programmer myself, so I hope I could help a bit at least this way
