### ISSUE TITLE
Broken Text

### ISSUE THREAD

**Issue by hubslave** [gnome-mpv/gnome-mpv#316]
Overview Description:
Hello friends, GnomeMpv flatpak has broken all texts after the last update

![gnomempvscreenshot](https://user-images.githubusercontent.com/29800872/31409968-f18d629c-ae0d-11e7-90af-ac3cf7659b3e.png)

If you need any more information please let me know

Steps to Reproduce:
1. Run EL 7.4
2. Install latest GnomeMpv-master flatpak
3. Run it

Actual Results:
Broken text

Expected Results:
Texts showing properly

Version:
master

Additional Information:
EL 7.4, flatpak 0.8.7

**Comment by TingPing** [comment]
Could be a bad interaction with fontconfig on your host. This should have nothing to do with gnome-mpv though and all Gtk3 flatpaks should be equally broken.

**Comment by hubslave** [comment]
you are right, when I tested another apps all have the same problem. do you think that I misconfigured something or is it bug of gnome-runtime?

**Comment by TingPing** [comment]
I don't know but you can open an issue on flatpak/flatpak over it.

**Comment by hubslave** [comment]
Ok I did, thank you very much for help :)

**Comment by gnome-mpv** [comment]
The problem has been fixed in the gnome 3.24 runtime.
