### ISSUE TITLE
On 0.13, two windows are opened when started via 'gnome-mpv [filename]' and 'Always open new window' has been checked

### ISSUE THREAD

**Issue by smithfred** [gnome-mpv/gnome-mpv#318]
This doesn't happen without a filename parameter, or when a file is opened via e.g. Nautilus (possibly to do with D-Bus being used in that case?)

**Comment by smithfred** [comment]
Thanks for the rapid fix! Chance of a 0.13.1 release? 😁

**Comment by gnome-mpv** [comment]
We don't do point releases. I suggest building from source if you want to have the fix quickly, or you can wait a bit for @TingPing to update the flatpak for development versions.

**Comment by smithfred** [comment]
Fair enough, didn't hurt to try 😉

Thanks for the suggestion re. BFS/Flatpak, but build from source means foregoing distro updates (e.g. backported security fixes), and Flatpak generally is a completely different trust/maintenance proposition compared to distro packages as well.

Out of interest, what's the rationale for "no point releases" (specifically, bug-fixes on current release until release+1 is out)? Not enough development resource? Don't agree with the principle/distro model?

**Comment by gnome-mpv** [comment]
> Out of interest, what's the rationale for "no point releases" (specifically, bug-fixes on current release until release+1 is out)? Not enough development resource?

Yes, I'm just trying to keep the maintenance workload down. If a release is so broken that it's unusable, it's still possible to just make a usual release at any time.

**Comment by smithfred** [comment]
In case anyone comes across this in the meantime, a workaround in 0.13 to always get new windows, without the blank extra windows, is:

* copy the GNOME MPV launcher from `/usr/share/applications` to `~/.local/share/applications` (or `/usr/local/share/applications`), and edit the following in the *copy*:
    * change `Exec=gnome-mpv %U` to `Exec=gnome-mpv --no-existing-session %U`
    * change `DBusActivatable=true` to `DBusActivatable=false`
* untick "Always open new window" in GNOME MPV's prefs
