### ISSUE TITLE
Problems with compilation.

### ISSUE THREAD

**Issue by Tracinha** [gnome-mpv/gnome-mpv#32]
I have this erro from autoconf.

configure.ac:19: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:19: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

ps: Sorry for my bad english.

**Comment by gnome-mpv** [comment]
Are you running Fedora? If so, try installing `glib2-devel`.

**Comment by Tracinha** [comment]
I'm running Arch.
I have instaled glib2 and can't find glib2-devel or glib2-dev

**Comment by gnome-mpv** [comment]
Have you tried using one of the AUR package?
* https://aur.archlinux.org/packages/gnome-mpv
* https://aur.archlinux.org/packages/gnome-mpv-git

**Comment by Tracinha** [comment]
Yes from AUR...
I use gnome-mpv-git.

**Comment by Tracinha** [comment]
Thank you for your attention.

Package from gnome-mpv works fine, solved my problem.
