### ISSUE TITLE
Volume button very large

### ISSUE THREAD

**Issue by momoe** [gnome-mpv/gnome-mpv#322]
Majaro:Deepin (rolling release)
gnome-mpv: v0.13

Issue: volume icon seems to be using  the 48 px scaled folder while the rest of the buttons are using the smaller scale; resulting in enlarged lower window bar. 

Please have the UI point to the same volume resource folder as said buttons instead of the larger counterpart.

**Comment by gnome-mpv** [comment]
This is probably caused by a bug in Deepin's theme. It works fine with Adwaita (and also "flattr").

**Comment by momoe** [comment]
I can confirm it's an issue with the Deepin icon set, after removing the /usr/share/icons/Deepin/48/share/.. volume icons. gnome-mpv now displays only a missing icon instead of falling back on the smaller icons instead. 

Does gnome-mpv source the biggest main icon possible and if so, can it be pointed to use one of the smaller ones in the icon pack?

**Comment by gnome-mpv** [comment]
> Does gnome-mpv source the biggest main icon possible and if so, can it be pointed to use one of the smaller ones in the icon pack?

No. For the volume button, it's using gtk's standard widget GtkVolumeButton. The default value for the icon size is [`GTK_ICON_SIZE_SMALL_TOOLBAR`](https://developer.gnome.org/gtk3/stable/gtk3-Themeable-Stock-Images.html#GtkIconSize), which is supposed to be 16px.

**Comment by momoe** [comment]
volume button has been fixed after an update today. Thank you for your assistance.
