### ISSUE TITLE
Option to use forward button as next playlist item

### ISSUE THREAD

**Issue by Whisprin** [gnome-mpv/gnome-mpv#326]
Hello,
I found #280, which states that for design reasons there won't be a previous / next playlist item button in the UI.

Since I don't have any use for the "Rewind" and "Forward" buttons (skipping 10s of video), which are shown unconditionally, I was wondering
a) how useful they are to others and
b) if we could introduce a user interface setting to replace those buttons by next / previous playlist item.

In the same way I can think of overwriting the next and previous chapter button with a next and previous playlist item.

Taking it further: Another idea would be to allow a secondary mouse button click for UI buttons, e.g.:
a) Previous -> previous playlist item 
b) Forward -> next playlist item
c) Play/Pause -> next frame
d) Stop -> previous frame
e) Volume -> Mute

**Comment by gnome-mpv** [comment]
I think b) is a good solution; we can have a new setting to make the chapter buttons control the playlist instead.

**Comment by Whisprin** [comment]
Sounds good. Shall I create a new feature request ticket or re-purpose this one?

**Comment by gnome-mpv** [comment]
It's okay to re-purpose this one.
