### ISSUE TITLE
when play .rmvb, always show some error

### ISSUE THREAD

**Issue by warmsun0220** [gnome-mpv/gnome-mpv#33]
when open  rmvb file, 
"rm: Invalid stream index 2 for index at pos 1442681866"
![Uploading 2015-05-17 13-12-56屏幕截图.png…]()

when Fast Forward,
rv40: Invalid decoder state: B-frame without reference data.
![2015-05-17 13-10-31](https://cloud.githubusercontent.com/assets/5374125/7669160/ffac03d2-fc95-11e4-8713-0cba466b0ece.png)

**Comment by warmsun0220** [comment]
![2015-05-17 13-12-56](https://cloud.githubusercontent.com/assets/5374125/7669181/760a7ac2-fc96-11e4-9d08-5438d68dc8a9.png)

**Comment by gnome-mpv** [comment]
Can you try playing the file using just `mpv` and see if the error occurs there too?

**Comment by warmsun0220** [comment]
No, when playing the file by mpv, no error occurs.

**Comment by warmsun0220** [comment]
$mpv  '/home/sun/视频/【木星上行】【高清720P版BD-RMVB.中英双 字 /【Jupiter Ascending】【高清720P版BD-RMVB.中英双字】.rmvb' 
Playing: /home/sun/视频/【木星上行】【高清720P版BD-RMVB.中英双字】/【Jupiter Ascending】【高清720P版BD-RMVB.中英双字】.rmvb
[ffmpeg/demuxer] rm: Invalid stream index 2 for index at pos 1442681866
 (+) Video --vid=1 (rv40)
 (+) Audio --aid=1 (aac)
File tags:
 Comment: 
 Title: ���õ�Ӱ��
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:00:11 / 02:07:34 (0%) A-V:  0.000
[ffmpeg/video] rv40: Invalid decoder state: B-frame without reference data.
Error while decoding frame!
AV: 00:00:26 / 02:07:34 (0%) A-V:  0.000


Exiting... (Quit)

**Comment by warmsun0220** [comment]
Maybe gnome-mpv outputs some error messages of ffmpeg?

**Comment by gnome-mpv** [comment]
Yes. The error comes from `mpv`, which also prints errors from `ffmpeg`. If the file plays correctly, you can suppress the error message using the mpv option `--msg-level`. You might also want file a bug report with `mpv`.

**Comment by warmsun0220** [comment]
the file plays well, and in fact mpv only show these error information in terminal. so I think gnome mpv could hide these messages in default.

**Comment by gnome-mpv** [comment]
I changed the default `msg-level` to fatal in 87abff0. Let me know if it fixes the problem.

**Comment by warmsun0220** [comment]
I didn't meet this issue by other media player(smplayer), so I still think this is an exception handling problem of  gnome-mpv.
Because of https://github.com/gnome-mpv/gnome-mpv/issues/35 , I cannot test gnome-mpv now. Thank you and this issue will be closed.

**Comment by gnome-mpv** [comment]
By design, gnome-mpv prints out all messages `mpv` sends to it so as to allow users to choose what kind of messages they want to receive. Though I guess it would have been less confusing if only fatal error messages were shown by default.

**Comment by warmsun0220** [comment]
output all messages to a file,if some fatal error fatal happens just exit and tell users to check this file. I am not sure, but I think more work need to do.

**Comment by warmsun0220** [comment]
The commit https://github.com/gnome-mpv/gnome-mpv/commit/87abff0bc4a5f0ca9733a367a6c886d6b97d6ef8 doesn‘t solve my problem.

**Comment by gnome-mpv** [comment]
You can try disabling messages from ffmpeg entirely using `--msg-level=ffmpeg=no`.

**Comment by warmsun0220** [comment]
I still can see these error message through i adds  --msg-level=ffmpeg=no in gnome-mpv .
After adding these commond in mpv, these messages are disabled.

**Comment by warmsun0220** [comment]
[sun@sun-laptop ~]$ mpv --msg-level=ffmpeg=no '/home/sun/视频/【木星上行】【高清720P版BD-RMVB.中英双字】/木星上行.rmvb' 
Playing: /home/sun/视频/【木星上行】【高清720P版BD-RMVB.中英双字】/木星上行.rmvb
 (+) Video --vid=1 (rv40)
 (+) Audio --aid=1 (aac)
File tags:
 Comment: 
 Title: ���õ�Ӱ��
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:00:06 / 02:07:34 (0%) A-V:  0.000
Error while decoding frame!
AV: 00:00:15 / 02:07:34 (0%) A-V: -0.000
Error while decoding frame!
AV: 00:00:25 / 02:07:34 (0%) A-V:  0.000
Error while decoding frame!
AV: 00:00:31 / 02:07:34 (0%) A-V: -0.000


Exiting... (Quit)

**Comment by gnome-mpv** [comment]
Looks like `--msg-level` has no effect when using client API, so I'll have to handle this manually in gnome-mpv.

**Comment by warmsun0220** [comment]
OK, Thanks!

**Comment by gnome-mpv** [comment]
`--msg-level` should be working now (54e13ac).

**Comment by warmsun0220** [comment]
I test it, and it works well now, thank you.
