### ISSUE TITLE
No preferences menu on Fedora 

### ISSUE THREAD

**Issue by steevithak** [gnome-mpv/gnome-mpv#333]
Overview Description:
I've seen references to a "preferences" menu in the documentation but I'm unable to see the menu item on Fedora. I'm running gnome-mpv 0.13 on Fedora 25. On my system MPV has two menus on the title bar, one is a "+" and has the options "open" and "open location", the other menu is a "hamburger menu" icon (the three horizontal lines) and has several playlist, track, and size options. But neither menu has a "preferences" item. Is this a bug or old documentation about a removed menu item? 

Steps to Reproduce:
1. Install MPV on Fedora
2.Start MPV
3. Look for "preferences" menu

Actual Results:
No preferences menu found

Expected Results:
preference menu present

Version:
0.13

Additional Information:

**Comment by gnome-mpv** [comment]
It should be in the [App Menu](https://wiki.gnome.org/Design/OS/AppMenu).

**Comment by TingPing** [comment]
In Fedora 27 if you dislike that you can now disable it in `gnome-tweak-tool` in *Top Bar*. (Sidenote Fedora 25 is end of life next week and you should upgrade).

**Comment by steevithak** [comment]
Wow, that's insanely non-intuitive to put some of the menus on the program menu tree but hide one menu in some other part of the OS. It would never even occur to me to look for part of the program's menu structure outside of the program itself! But thanks, good to know. Yes, already running Fedora 27 on one of my computers and will be updating the other one soon. If I turn it off "top bar" in the gnome tweak tool, will the preferences menu vanish altogether or just move back onto menu tree in the program where the other menu items are?

**Comment by TingPing** [comment]
> Wow, that's insanely non-intuitive to put some of the menus on the program menu tree but hide one menu in some other part of the OS. It would never even occur to me to look for part of the program's menu structure outside of the program itself! But thanks, good to know.

Yea, hopefully GNOME will get rid of it in the not so distant future.

> If I turn it off "top bar" in the gnome tweak tool, will the preferences menu vanish altogether or just move back onto menu tree in the program where the other menu items are?

It will move into a button in the application. GNOME-MPV itself also has an option to disable client-side decorations so you get a full menu bar.
