### ISSUE TITLE
Prevent autoplay of next file in playlist

### ISSUE THREAD

**Issue by teohhanhui** [gnome-mpv/gnome-mpv#334]
With mpv it's possible to pause playback at the end of each file in a playlist by using the [`--keep-open=always` option](https://mpv.io/manual/stable/#options-keep-open). This does not work with gnome-mpv even though I have the same option in the mpv.conf and have loaded it.

**Comment by gnome-mpv** [comment]
I can't reproduce this. The option seems to work as you as you described for me.

Can you post log messages here?

**Comment by teohhanhui** [comment]
Yeah, I think you're right. It works as expected.
