### ISSUE TITLE
Compatibility with mpv input.conf

### ISSUE THREAD

**Issue by teohhanhui** [gnome-mpv/gnome-mpv#335]
For example, I have `CTRL+ENTER cycle fullscreen` in my mpv input.conf and have loaded it. I'd expect that gnome-mpv should do the sensible thing and translate that into `CTRL+ENTER script-message gmpv-action win.toggle-fullscreen`.

**Comment by gnome-mpv** [comment]
As of 0c46503be9fc09275cfb74e83a9d0eeac4e1f06d, there should be no command (except the ones that have no `mpv` counterpart) that can only be used via `gmpv-action`, so I think this can be closed.
