### ISSUE TITLE
Support GVFS locations in file chooser

### ISSUE THREAD

**Issue by smithfred** [gnome-mpv/gnome-mpv#336]
At the moment the (GTK+) file chooser doesn't show bookmarks of GVFS locations (i.e. anything other than file:// locations in ~/.config/gtk-3.0/bookmarks). For example, sftp:// locations aren't shown.

**Comment by TingPing** [comment]
That would be an issue to report to Gtk.

**Comment by smithfred** [comment]
Not AFAICS - there's a non-default param that needs to be set to include GVFS/GIO locations: https://lazka.github.io/pgi-docs/Gtk-3.0/classes/FileChooser.html#Gtk.FileChooser.set_local_only

**Comment by TingPing** [comment]
Ah, that does indeed show more but `mpv` doesn't use `gvfs` so it can't actually read most of those resources.

**Comment by gnome-mpv** [comment]
I think `gvfs` can create FUSE mount points for applications that don't support GIO, so this shouldn't be a problem; `mpv` will just see the mount point in `/run`.
