### ISSUE TITLE
mouse cursor not hide automaticaly

### ISSUE THREAD

**Issue by dikasetyaprayogi** [gnome-mpv/gnome-mpv#337]
Overview Description:
mouse cursor always visible in gnome-mpv video window

Steps to Reproduce:
place cursor in video window

Actual Results:
the cursor persist when the video playing, getting in the user way or force him to move cursor somewhere else

Expected Results:
the good design principles looking from original mpv and some common media player is to autohide mouse cursor after a brief of time whenever it gets in video playing area and show them again only when mouse motion is triggered

Version:
0.11 (git)

**Comment by TingPing** [comment]
> 0.11 (git)

Current version is 0.13, so very old git build?

**Comment by dikasetyaprayogi** [comment]
sorry, build it from arch aur made me always assume that is the latest version

retested on 0.13-2 version both on kde and gnome wayland session, the problem still persist

**Comment by gnome-mpv** [comment]
The cursor is currently only being hidden in fullscreen mode. I'll add an option to do that in windowed mode as well.
