### ISSUE TITLE
gnome mpv crashed

### ISSUE THREAD

**Issue by SolarAquarion** [gnome-mpv/gnome-mpv#338]
(gnome-mpv:12491): GLib-GIO-ERROR **: Settings schema 'io.github.GnomeMpv' does not contain a key named 'use-skip-buttons-for-playlist'

Thread 1 "gnome-mpv" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff61685a2 in ?? () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff61685a2 in  () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff616964d in g_log_default_handler () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff61698ef in g_logv () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff6169a70 in g_log () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff679bc1a in  () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff679c28c in  () at /usr/lib/libgio-2.0.so.0
#6  0x00007ffff67a1d23 in g_settings_bind_with_mapping () at /usr/lib/libgio-2.0.so.0
#7  0x00007ffff67a228b in g_settings_bind () at /usr/lib/libgio-2.0.so.0
#8  0x000055555556af58 in initialize_gui (app=0x555555911190) at ../src/gmpv_application.c:139
#9  0x00007ffff643cc0d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff6450b10 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff64597c6 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff645a200 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#13 0x000055555556abde in open_handler (gapp=0x555555911190, files=0x7fffffffc250, n_files=1, hint=<optimized out>, data=0x555555911190)
    at ../src/gmpv_application.c:216
#14 0x00007ffff07791c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#15 0x00007ffff0778c2a in ffi_call () at /usr/lib/libffi.so.6
#16 0x00007ffff643d43b in g_cclosure_marshal_generic () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff643cc0d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff6450b10 in  () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff64597c6 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff645a200 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#21 0x000055555556b2cf in command_line_handler (gapp=0x555555911190, cli=0x5555557cb9c0, data=0x555555911190)
    at ../src/gmpv_application.c:314
#22 0x00007ffff07791c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#23 0x00007ffff0778c2a in ffi_call () at /usr/lib/libffi.so.6
#24 0x00007ffff643d43b in g_cclosure_marshal_generic () at /usr/lib/libgobject-2.0.so.0
#25 0x00007ffff643cc0d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#26 0x00007ffff6450b10 in  () at /usr/lib/libgobject-2.0.so.0
#27 0x00007ffff6459151 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#28 0x00007ffff645a200 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#29 0x00007ffff6726bc7 in  () at /usr/lib/libgio-2.0.so.0
#30 0x00007ffff67292a1 in  () at /usr/lib/libgio-2.0.so.0
#31 0x00007ffff6729472 in g_application_run () at /usr/lib/libgio-2.0.so.0
#32 0x000055555556227c in main (argc=2, argv=0x7fffffffcc58) at ../src/gmpv_main.c:35

**Comment by TingPing** [comment]
How did you install it? Somehow you are running against outdated schemas.

**Comment by SolarAquarion** [comment]
I installed it via arch
