### ISSUE TITLE
Gnome MPV does not start after last update of gnome platform and freedesktop platform

### ISSUE THREAD

**Issue by bugreport0** [gnome-mpv/gnome-mpv#339]
**Overview Description:**
Hello, today I updated org.gnome.Platform and org.freedesktop.Platform and Gnome MPV does not start. It was working fine before. When trying to run it from terminal ( `flatpak run io.github.GnomeMpv` ) i get these errors:

```
Non-C locale detected. This is not supported.
Call 'setlocale(LC_NUMERIC, "C");' in your code.
```

**Steps to Reproduce:**
1. Start Linux machine
2. Execute `flatpak run io.github.GnomeMpv`
3. Get the errors

**Actual Results:**
When running `flatpak run io.github.GnomeMpv` I get:

```
Non-C locale detected. This is not supported.
Call 'setlocale(LC_NUMERIC, "C");' in your code.
```

**Expected Results:**
Gnome MPV works. :)

**Version:**
Latest stable

**Additional Information:**
Enterprise Linux 7.4

**Comment by TingPing** [comment]
I can reproduce but this is probably worth reporting here: https://github.com/flatpak/freedesktop-sdk-images

**Comment by TingPing** [comment]
Actually this isn't a runtime regression this is an `mpv` regression: https://github.com/mpv-player/mpv/blob/244cc1f018fcdb31fc24ac7e30a1ee9beb734966/player/client.c#L485-L494

**Comment by TingPing** [comment]
Hmm, Actually that was a bit rash, that locale check has been there for multiple releases.

**Comment by TingPing** [comment]
Anyway I've pushed an update forcing `LC_NUMERIC=C`. Not sure how it worked before?

**Comment by bugreport0** [comment]
I'm not really sure how it worked before, I usually start GnomeMPV by clicking icon, not running it from terminal, but even yesterday it worked without flaw (and I update all my flatpaks everyday). It just stopped working today, but today there were only updates for platforms not for GnomeMpv itself. Is there anything what I can try to help to resolve this issue?

**Comment by TingPing** [comment]
There have not been any interesting runtime updates:
https://github.com/flatpak/freedesktop-sdk-images/commits/1.6  
https://github.com/GNOME/gnome-sdk-images/commits/gnome-3-26

The code looks like it was always meant to fail.. maybe @gnome-mpv will have more insight.

**Comment by gnome-mpv** [comment]
`setlocale()` is already being called [here](https://github.com/gnome-mpv/gnome-mpv/blob/master/src/gmpv_application.c#L333) but it's not working in flatpak for some reason.

**Comment by TingPing** [comment]
Adding some debug prints something *after* startup is changing the locale:

```
startup locale: en_US.UTF-8
set locale: C
Non-C locale detected. This is not supported.
Call 'setlocale(LC_NUMERIC, "C");' in your code.
```

**Comment by TingPing** [comment]
@gnome-mpv This can be closed. While I never found out the root problem it was worked around.

**Comment by gnome-mpv** [comment]
@TingPing: With 4c0d055f603b3a1d4fba93c248d742b89a008656, the env override added in https://github.com/flathub/io.github.GnomeMpv/commit/8e82a47fdeafa6133c3451387af32cd7cf81ea8c shouldn't be necessary any more. Can you confirm this?

**Comment by TingPing** [comment]
@gnome-mpv Works fine. The actual cause was found by @grawity though, a fontconfig regression that is fixed in git: https://github.com/behdad/fontconfig/commit/98eaef69af1350e459bf9c175476d3b772968874
