### ISSUE TITLE
[flatpak] drag and drop does not work

### ISSUE THREAD

**Issue by glaubersm** [gnome-mpv/gnome-mpv#340]
Overview Description:
drag and drop works with gnome-mpv installed on Arch Linux from AUR but fails with flatpak build installed on the same system.
Steps to Reproduce:
1. install flatpak build
2. drag a file from your file manager to gnome-mpv window
3.

Actual Results:
error message "Playback was terminated abnormally. Reason: loading failed."
Expected Results:
gnome-mpv plays the file.
Version: 0.13

Additional Information:
Tested on Gnome 3.26.2 under both Wayland and X11 sessions.

**Comment by TingPing** [comment]
This was brought up in #300 and as it links already has a tracking issue upstream.

**Comment by glaubersm** [comment]
thank you TinPing.
I will wait for a fix in flatpak.
