### ISSUE TITLE
Alt+0/1/2 keys need to press twice

### ISSUE THREAD

**Issue by parkmino** [gnome-mpv/gnome-mpv#344]
Overview Description: Half/Normal/Double size key bindings do not work properly

Steps to Reproduce:
1. Press Alt+0/1/2
2.
3.

Actual Results: Screen broken at first press, OK at second press.

Expected Results: Resize to Half/Normal/Double.

Version: 0.14

Additional Information:

**Comment by gnome-mpv** [comment]
Can't reproduce. Can you post a screenshot of the screen being broken and [log messages](https://github.com/gnome-mpv/gnome-mpv/blob/master/.github/CONTRIBUTING.md)?

**Comment by parkmino** [comment]
I'm using Ubuntu 16.04.3 LTS
 
1. Alt+0@Normal Size (Quarter size)
![2018-02-24-075827_997x456_scrot](https://user-images.githubusercontent.com/12131158/36620927-c8b1dac4-1938-11e8-887e-ccd4b5548f24.png)

2. Alt+1@Half Size (Broken screen)
![2018-02-24-075850_636x253_scrot](https://user-images.githubusercontent.com/12131158/36620968-0d78776c-1939-11e8-956f-07c50a4b32c0.png)

3. Alt+2@Normal Size (Blank)
![2018-02-24-075859_997x456_scrot](https://user-images.githubusercontent.com/12131158/36620980-1f0970da-1939-11e8-9d43-e67df99ef64f.png)

**Comment by gnome-mpv** [comment]
You forgot to attach a log file.

**Comment by parkmino** [comment]
[gnome-mpv.log](https://github.com/gnome-mpv/gnome-mpv/files/1754254/gnome-mpv.log)

**Comment by gnome-mpv** [comment]
>** INFO: Using mpv 0.26.0

You need to update mpv to version 0.27.0 or newer. Older versions are affected by this [mpv bug](https://github.com/mpv-player/mpv/issues/4784), which is probably what's causing the behavior you're seeing.

**Comment by gnome-mpv** [comment]
>I'm using the latest mpv 0.28.0 git1 via Ubuntu PPA and no problem in mpv.

It's using 0.26.0 according to the log. On Ubuntu, you need to update package called `libmpv1`.

>Gnome-mpv 0.13 was fine either.

gnome-mpv 0.13 and earlier used to use it's own mechanism to handle window scaling. In 0.14, it was changed to use values from mpv's `window-scale` property directly so that it can be controlled more easily from `input.conf`. See https://github.com/gnome-mpv/gnome-mpv/issues/298.

**Comment by parkmino** [comment]
MPV and Libmpv packages are separate in Ubuntu PPA and I don't find the latest Libmpv in it.
Now I see the root cause and it will be resolved once upgrade to Ubuntu 18.04 which includes libmpv1 0.27.
I don't want to build libmpv1 and double key input works anyway on my side.

**Comment by TingPing** [comment]
You could install [the Flatpak](https://beta.flathub.org/apps/details/io.github.GnomeMpv) which comes with libmpv 0.28.

**Comment by parkmino** [comment]
Yeah, it works flawlessly!
