### ISSUE TITLE
 (gnome-mpv:4022): GLib-GIO-ERROR **: Settings schema 'org.gnome-mpv' is not installed

### ISSUE THREAD

**Issue by warmsun0220** [gnome-mpv/gnome-mpv#35]
[sun@sun-laptop ~]$ gnome-mpv

(gnome-mpv:4022): GLib-GIO-ERROR **: Settings schema 'org.gnome-mpv' is not installed

Trace/breakpoint trap

**Comment by gnome-mpv** [comment]
How did you install gnome-mpv? This error can happen if you use https://aur.archlinux.org/packages/gnome-mpv-git/ right now. It needs to be updated to install the gsettings schema introduced in b720b95. Manual installation explained in the readme should work fine though. You should also be able to fix the problem by running `glib-compile-schemas /usr/share/glib-2.0/schemas` as root.

**Comment by warmsun0220** [comment]
sorry I install it by yaourt. I will test tonight. thankyou.

**Comment by warmsun0220** [comment]
sorry I install it by yaourt. I will test tonight. thankyou.
