### ISSUE TITLE
Youtube playlists not expanded

### ISSUE THREAD

**Issue by luispabon** [gnome-mpv/gnome-mpv#350]
Overview Description:
Sending a playlist link to mpv only seems to add the first video (the one on the URL) to gnome mpv's playlist

Steps to Reproduce:
1. Add https://www.youtube.com/watch?v=Gf1WT8VEZxk&list=RDGf1WT8VEZxk to gnome mpv (drag and drop, open location)

Actual Results:
First video plays only, gnome mpv playlist only contains said video

Expected Results:
Youtube playlist expanded into individual videos within gnome mpv playlist, and first video (the one on the URL) playing.

Version:
mpv 0.26.0-3ubuntu1
gnome-mpv 0.12-1
Ubuntu 17.10

**Comment by TingPing** [comment]
Probably a problem on `youtube-dl`'s end.

**Comment by gnome-mpv** [comment]
`youtube-dl` doesn't expand the playlist if the given URL refers to both a playlist and a video unless you set the `--yes-playlist` option (put `ytdl-raw-options=yes-playlist=` in the config file).

I'll make this a default option.

**Comment by luispabon** [comment]
Thank you :+1:

**Comment by luispabon** [comment]
Which config file would that be though?

**Comment by luispabon** [comment]
So I've created a mpv config file at `~/.config/gnome-mpv/config.conf` containing `ytdl-raw-options=yes-playlist` (I've tried with and without the equal sign at the end) and selected it on gnome-mpv's preferences. So far it's had no effect - I've tried gnome-mpv 0.12 (ubuntu artful) but also 0.13 and 0.14 from this repository https://launchpad.net/~xuzhen666/+archive/ubuntu/gnome-mpv/+packages

So far it hasn't worked. if I simply `youtube-dl PLAYLIST_ABOVE` I can see it downloading all the videos on that playlist by default without passing the --yes-playlist flag.

**Comment by luispabon** [comment]
Also `--yes-playlist` takes no values, I don't think it should have an equal sign at the end if you're concatenating it with something else

**Comment by gnome-mpv** [comment]
>So I've created a mpv config file at ~/.config/gnome-mpv/config.conf containing ytdl-raw-options=yes-playlist (I've tried with and without the equal sign at the end) and selected it on gnome-mpv's preferences. So far it's had no effect - I've tried gnome-mpv 0.12 (ubuntu artful) but also 0.13 and 0.14 from this repository https://launchpad.net/~xuzhen666/+archive/ubuntu/gnome-mpv/+packages

Does it work if you set the flag in the `Extra MPV Options` textbox in the bottom of the preferences dialog instead (change the option string to `--ytdl-raw-options=yes-playlist=`) ?

>So far it hasn't worked. if I simply youtube-dl PLAYLIST_ABOVE I can see it downloading all the videos on that playlist by default without passing the --yes-playlist flag.

The flag seems to be needed when `youtube-dl` is used through `mpv`.

>Also --yes-playlist takes no values, I don't think it should have an equal sign at the end if you're concatenating it with something else

`mpv` requires the equal sign to be there.

**Comment by luispabon** [comment]
It works when adding it to extra MPV options :+1: playlist is expanded and I can see the video names slowly resolving on the playlist. Thank you :+1:
