### ISSUE TITLE
Fails on both vaapi and vdpau on Gnome-wayland

### ISSUE THREAD

**Issue by biswasab** [gnome-mpv/gnome-mpv#356]
Overview Description:
Running Gnome-mpv on gnome wayland either with hwdec=vaapi or hwdec=vdpau on a radeon GPU fails

Steps to Reproduce:
1. Switch/login to Gnome wayland
2. Run Any h.264 file with gnome-mpv with --hwdec=vdpau/hwdec=vaapi
3. Notice cpu usage and check the logs

Actual Results:
Gnome-mpv fails to do hw dec on wayland

Expected Results:
It should do both vaapi and vdpau as mpv does through xwayland

Version:
GNOME MPV 0.14 Fedora

Additional Information:
Logs:
>>>>>(gnome-mpv:4063): Gtk-DEBUG: Connecting to session manager
** INFO: Starting GNOME MPV 0.14
** INFO: Failed to retrieve property "idle-active" using mpv format 3. Reason: core not uninitialized.
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "CanQuit"
** (gnome-mpv:4063): DEBUG: Adding property "CanSetFullscreen"
** (gnome-mpv:4063): DEBUG: Adding property "CanRaise"
** (gnome-mpv:4063): DEBUG: Adding property "Fullscreen"
** (gnome-mpv:4063): DEBUG: Adding property "HasTrackList"
** (gnome-mpv:4063): DEBUG: Adding property "Identity"
** (gnome-mpv:4063): DEBUG: Adding property "DesktopEntry"
** (gnome-mpv:4063): DEBUG: Adding property "SupportedUriSchemes"
** (gnome-mpv:4063): DEBUG: Adding property "SupportedMimeTypes"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "PlaybackStatus"
** (gnome-mpv:4063): DEBUG: Adding property "Rate"
** (gnome-mpv:4063): DEBUG: Adding property "Metadata"
** (gnome-mpv:4063): DEBUG: Adding property "Volume"
** (gnome-mpv:4063): DEBUG: Adding property "MinimumRate"
** (gnome-mpv:4063): DEBUG: Adding property "MaximumRate"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoNext"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoPrevious"
** (gnome-mpv:4063): DEBUG: Adding property "CanPlay"
** (gnome-mpv:4063): DEBUG: Adding property "CanPause"
** (gnome-mpv:4063): DEBUG: Adding property "CanSeek"
** (gnome-mpv:4063): DEBUG: Adding property "CanControl"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "PlaybackStatus"
** (gnome-mpv:4063): DEBUG: Adding property "CanSeek"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "CanGoPrevious"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoNext"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Rate"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** INFO: Failed to retrieve property "path" as string.
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Metadata"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Volume"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Tracks"
** (gnome-mpv:4063): DEBUG: Adding property "CanEditTracks"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.TrackList
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Tracks"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.TrackList
** INFO: Failed to retrieve property "time-pos" using mpv format 5. Reason: core not uninitialized.
** (gnome-mpv:4063): DEBUG: Applying default option --vo=opengl,vdpau,vaapi,xv,x11,opengl-cb,
** (gnome-mpv:4063): DEBUG: Applying default option --osd-level=1
** (gnome-mpv:4063): DEBUG: Applying default option --softvol=yes
** (gnome-mpv:4063): DEBUG: Applying default option --force-window=immediate
** (gnome-mpv:4063): DEBUG: Applying default option --input-default-bindings=yes
** (gnome-mpv:4063): DEBUG: Applying default option --audio-client-name=io.github.GnomeMpv
** (gnome-mpv:4063): DEBUG: Applying default option --title=${media-title}
** (gnome-mpv:4063): DEBUG: Applying default option --autofit-larger=75%
** (gnome-mpv:4063): DEBUG: Applying default option --window-scale=1
** (gnome-mpv:4063): DEBUG: Applying default option --pause=yes
** (gnome-mpv:4063): DEBUG: Applying default option --ytdl=yes
** (gnome-mpv:4063): DEBUG: Applying default option --load-scripts=no
** (gnome-mpv:4063): DEBUG: Applying default option --osd-bar=no
** (gnome-mpv:4063): DEBUG: Applying default option --input-cursor=no
** (gnome-mpv:4063): DEBUG: Applying default option --cursor-autohide=no
** (gnome-mpv:4063): DEBUG: Applying default option --softvol-max=100
** (gnome-mpv:4063): DEBUG: Applying default option --config=no
** (gnome-mpv:4063): DEBUG: Applying default option --config-dir=/home/akarshan/.config/gnome-mpv
** (gnome-mpv:4063): DEBUG: Applying default option --watch-later-directory=/home/akarshan/.config/gnome-mpv/watch_later
** (gnome-mpv:4063): DEBUG: Applying default option --screenshot-template=gnome-mpv-shot%n
** (gnome-mpv:4063): DEBUG: Using temporary input config file: /tmp/.9OCDIZ
** (gnome-mpv:4063): DEBUG: Applying extra mpv options: --vo=vdpau --hwdec=vdpau
** (gnome-mpv:4063): DEBUG: Applying option: --vo=vdpau
>>>>>>** (gnome-mpv:4063): DEBUG: Applying option: --hwdec=vdpau
>>>>>>** INFO: Forcing --vo=opengl-cb
>>>>>>** INFO: Failed to retrieve property "current-vo" as string.
** INFO: Using mpv 0.27.2
** (gnome-mpv:4063): DEBUG: Initialized opengl-cb
** (gnome-mpv:4063): DEBUG: Setting volume to 100.000000
** INFO: Failed to retrieve property "time-pos" using mpv format 5. Reason: property unavailable.
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "aid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "vid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "sid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "PlaybackStatus"
** (gnome-mpv:4063): DEBUG: Adding property "CanSeek"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "idle-active"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "PlaybackStatus"
** (gnome-mpv:4063): DEBUG: Adding property "CanSeek"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "CanGoPrevious"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoNext"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "fullscreen"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "pause"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "loop"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "playlist"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "playlist-count"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "CanGoPrevious"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoNext"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "speed"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Rate"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "track-list"
** INFO: Loading file (append=FALSE): file:///<videofile>
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "vo-configured"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Tracks"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.TrackList
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "idle-active"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "PlaybackStatus"
** (gnome-mpv:4063): DEBUG: Adding property "CanSeek"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "pause"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "media-title"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Tracks"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.TrackList
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "playlist"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "playlist-count"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "CanGoPrevious"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoNext"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "playlist-pos"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "CanGoPrevious"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoNext"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "volume"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "Volume"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "window-scale"
** INFO: Failed to retrieve property "dwidth" using mpv format 4. Reason: property unavailable.
** INFO: Failed to retrieve property "dheight" using mpv format 4. Reason: property unavailable.
** INFO: Failed to retrieve property "dwidth" using mpv format 4. Reason: property unavailable.
** INFO: Failed to retrieve property "dheight" using mpv format 4. Reason: property unavailable.
** INFO: Forcing --vo=null
** INFO: Failed to retrieve property "current-vo" as string.
** INFO: Using mpv 0.27.2
** (gnome-mpv:4063): DEBUG: Queuing <videofile> for metadata fetch
** INFO: Loading file (append=TRUE): <videofile>
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "track-list"
** (gnome-mpv:4063): DEBUG: Fetched metadata for <videofile>
** INFO: Terminating mpv
** (gnome-mpv:4063): DEBUG: Retrieved option --window-scale=1.000000
** (gnome-mpv:4063): DEBUG: Retrieved option --autofit-larger=75%x0
** (gnome-mpv:4063): DEBUG: Retrieved option --window-scale=1.000000
** (gnome-mpv:4063): DEBUG: Retrieved option --autofit-larger=75%x0
** (gnome-mpv:4063): DEBUG: Retrieved option --window-scale=1.000000
** (gnome-mpv:4063): DEBUG: Retrieved option --autofit-larger=75%x0
** (gnome-mpv:4063): DEBUG: Retrieved option --window-scale=1.000000
** (gnome-mpv:4063): DEBUG: Retrieved option --autofit-larger=75%x0
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "aid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "vid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "sid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "chapters"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "duration"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "PlaybackStatus"
** (gnome-mpv:4063): DEBUG: Adding property "CanSeek"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "metadata"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "track-list"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "vo-configured"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "window-scale"
** (gnome-mpv:4063): DEBUG: Set mouse location to (917, 317)
** (gnome-mpv:4063): DEBUG: Set mouse location to (933, 307)
** (gnome-mpv:4063): DEBUG: Set mouse location to (948, 305)
** (gnome-mpv:4063): DEBUG: Set mouse location to (971, 309)
** (gnome-mpv:4063): DEBUG: Set mouse location to (993, 318)
** (gnome-mpv:4063): DEBUG: Set mouse location to (996, 319)
** (gnome-mpv:4063): DEBUG: Set mouse location to (997, 323)
** (gnome-mpv:4063): DEBUG: Set mouse location to (997, 324)
** (gnome-mpv:4063): DEBUG: Set mouse location to (975, 265)
** (gnome-mpv:4063): DEBUG: Set mouse location to (978, 186)
** (gnome-mpv:4063): DEBUG: Set mouse location to (989, 134)
** (gnome-mpv:4063): DEBUG: Set mouse location to (1000, 103)
** (gnome-mpv:4063): DEBUG: Set mouse location to (1000, 100)
** (gnome-mpv:4063): DEBUG: Set mouse location to (993, 102)
** (gnome-mpv:4063): DEBUG: Set mouse location to (927, 130)
** (gnome-mpv:4063): DEBUG: Set mouse location to (468, 356)
** (gnome-mpv:4063): DEBUG: Set mouse location to (290, 446)
** (gnome-mpv:4063): DEBUG: Set mouse location to (265, 452)
** (gnome-mpv:4063): DEBUG: Set mouse location to (198, 507)
** (gnome-mpv:4063): DEBUG: Set mouse location to (156, 543)
** (gnome-mpv:4063): DEBUG: Set mouse location to (136, 558)
** (gnome-mpv:4063): DEBUG: Set mouse location to (131, 562)
** (gnome-mpv:4063): DEBUG: Set mouse location to (130, 564)
** (gnome-mpv:4063): DEBUG: Set mouse location to (130, 565)
** (gnome-mpv:4063): DEBUG: Set mouse location to (129, 566)
** (gnome-mpv:4063): DEBUG: Set mouse location to (122, 571)
** (gnome-mpv:4063): DEBUG: Set mouse location to (116, 575)
** (gnome-mpv:4063): DEBUG: Retrieved option --window-scale=0.533054
** (gnome-mpv:4063): DEBUG: Retrieved option --autofit-larger=75%x0
** (gnome-mpv:4063): DEBUG: Retrieved option --window-scale=0.533054
** (gnome-mpv:4063): DEBUG: Retrieved option --autofit-larger=75%x0
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "aid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "vid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "sid"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "chapters"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "PlaybackStatus"
** (gnome-mpv:4063): DEBUG: Adding property "CanSeek"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "idle-active"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "PlaybackStatus"
** (gnome-mpv:4063): DEBUG: Adding property "CanSeek"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "CanGoPrevious"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoNext"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "pause"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "duration"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "media-title"
** INFO: Failed to retrieve property "metadata" using mpv format 6. Reason: property unavailable.
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "metadata"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "playlist"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "playlist-count"
** (gnome-mpv:4063): DEBUG: Preparing property change event
** (gnome-mpv:4063): DEBUG: Adding property "CanGoPrevious"
** (gnome-mpv:4063): DEBUG: Adding property "CanGoNext"
** (gnome-mpv:4063): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "playlist-pos"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "track-list"
** (gnome-mpv:4063): DEBUG: Received mpv property change event for "vo-configured"
** (gnome-mpv:4063): DEBUG: Set mouse location to (336, 376)
** (gnome-mpv:4063): DEBUG: Set mouse location to (437, 296)
** (gnome-mpv:4063): DEBUG: Set mouse location to (586, 195)
** (gnome-mpv:4063): DEBUG: Set mouse location to (650, 154)
** (gnome-mpv:4063): DEBUG: Set mouse location to (707, 129)
** (gnome-mpv:4063): DEBUG: Set mouse location to (738, 114)
** (gnome-mpv:4063): DEBUG: Set mouse location to (761, 89)
** (gnome-mpv:4063): DEBUG: Set mouse location to (795, 57)
** (gnome-mpv:4063): DEBUG: Set mouse location to (853, 12)
** INFO: Terminating mpv
** (gnome-mpv:4063): DEBUG: Uninitializing opengl-cb

System information
OS: Fedora 27
kernel:4.16.3-200.fc27.x86_64
libva version: 1.8.3.5.fc27
GPU: AMD Radeon RX550 series/AMD Radeon R5 series(radeonsi)

IMO this is the best media player Linux can get.

**Comment by gnome-mpv** [comment]
Does it work if you run `GDK_BACKEND=x11 gnome-mpv`?

**Comment by biswasab** [comment]
It got errored with GDK_BACKEND=x11 gnome-mpv! I don't know why it tries to open "libvdpau_nvidia.so" in an AMD radeon GPU. But works with VDPAU_DRIVER=radeonsi GDK_BACKEND=x11 gnome-mpv

**Comment by gnome-mpv** [comment]
>It got errored with GDK_BACKEND=x11 gnome-mpv! I don't know why it tries to open "libvdpau_nvidia.so" in an AMD radeon GPU. But works with VDPAU_DRIVER=radeonsi GDK_BACKEND=x11 gnome-mpv

It seems that `libvdpau` uses the Nvidia driver by default unless something else is explicitly chosen. I get similar error with `mpv` on my Intel box if I try to use `vdpau` with `VDPAU_DRIVER` unset.

**Comment by biswasab** [comment]
Okay vaapi works too with x11 backend. But I'm not going to use that unless f28 is released which would come with libva2. So the main solution here is running gmpv under x11 backend.
