### ISSUE TITLE
Suggestion to add a repeat button to the interface?

### ISSUE THREAD

**Issue by orschiro** [gnome-mpv/gnome-mpv#360]
Dear all, 

I love gnome-mpv, thanks so much for your work on it! 

Just a suggestion. I not a very heavy mpv user and cannot get my head around all these shortcuts easily. 

Example is repeat. Triggered by Shift + L. Somehow doesn't easily stick to my brain and I constantly forget about it. 

I deem repeat quite a mundane feature. Do you find it useful to add a repeat button to the interface for newcomers like me to easily reach this feature? :-)

Thank you if possible!

![image](https://user-images.githubusercontent.com/170947/40267622-f6e1f1ea-5b5f-11e8-973d-168f7c03f141.png)

**Comment by gnome-mpv** [comment]
You can already toggle looping (repeat) from the right-click menu in the playlist, but I guess it makes more sense to have a button in the controls. There's no standard icon for looping just a single file though, so we can only add a button for looping the entire playlist.

**Comment by orschiro** [comment]
Hey!

Thanks so much for your positively-responsive reply! :-) 

> so we can only add a button for looping the entire playlist.

Yes, sounds good to me!

**Comment by orschiro** [comment]
@Easyghost195 @gnome-mpv much appreciate the commit!

**Comment by Easyghost195** [comment]
No problem @orschiro
And I want to apologize to @gnome-mpv because of the no answer and the no modification...
Thank you so much for integrate my commit and  edit it!
