### ISSUE TITLE
Show file name instead of "Unknown artist" in mpris interface?

### ISSUE THREAD

**Issue by orschiro** [gnome-mpv/gnome-mpv#361]
Dear all, 

I played the following file with gnome-mpv: `Ori and the Blind Forest OST - 01 - Ori, Lost In the Storm (feat. Aeralie Brighton)-j-Fhx2IEztw.mp3`

The name of the file is shown in the gnome-mpv application window as its title but the mpris interface shows this rather unuseful "Unknown artist". Could we maybe show the file name instead? :-)

The screenshot below was taken on Fedora 28 with a running GNOME. 

Thanks!

![image](https://user-images.githubusercontent.com/170947/40278083-cc807e28-5c2a-11e8-8afa-2caccc528100.png)

**Comment by gnome-mpv** [comment]
This is something that should be handled by the MPRIS client; the file name is already available via the `xesam:url` property. I don't think putting the file name in the artist or title field is a good solution since MPRIS clients won't be able to detect when these properties are unavailable.

**Comment by orschiro** [comment]
> I suggest filing a bug report with gnome-shell if you want this implemented.

I will consider this, thanks for explaining me a bit the backgrounds of this issue!
