### ISSUE TITLE
[feature request] auto-switch mpv profile for AC/battery

### ISSUE THREAD

**Issue by enihcam** [gnome-mpv/gnome-mpv#362]
Overview Description:
Please support automatic switching mpv profile for AC/battery. Laptop users would love this.

Steps to Reproduce:
1.
2.
3.

Actual Results:
Manually change mpv.conf

Expected Results:
Auto switch

Version:

Additional Information:

**Comment by gnome-mpv** [comment]
This is better handled in `mpv`. and there's actually already a [Lua script](https://gist.github.com/ElegantMonkey/04924e899648e84f2e18) for it.
