### ISSUE TITLE
Video playback is stuck in reverse after pressing frame back

### ISSUE THREAD

**Issue by jb817566** [gnome-mpv/gnome-mpv#365]
Overview Description:
During playback of ~~H.265 HEVC~~ video, player is stuck playing the video/audio in reverse

EDIT: observed with AVC as well, so may be a general issue. Also observed incorrect timecode when skipping frame back, eventually causing the playbar to advanced until this happens
![screenshot from 2018-06-24 11-44-26](https://user-images.githubusercontent.com/9065420/41820717-0e3f49e0-77a4-11e8-9b6d-3c2ec73395ed.png)

Steps to Reproduce:
1. Play example file at http://jell.yfish.us/media/jellyfish-3-mbps-hd-hevc.mkv
2. Press the frame backwards key while playing or paused
3. Resume playback

Actual Results:
Plays backwards under the conditions above
Expected Results:
Play media forwards after skipping back any number of frames

Version:
0.13-1ubuntu1

Additional Information:
Pop!_OS 18.04

[jellyfish_mediainfo.txt](https://github.com/gnome-mpv/gnome-mpv/files/2130919/jellyfish_mediainfo.txt)

I don't observe this in `mpv`.

**Comment by gnome-mpv** [comment]
I can't reproduce this.

The screenshot you posted looks a lot like [Totem](https://en.wikipedia.org/wiki/GNOME_Videos). Are you sure you're using gnome-mpv?

**Comment by jb817566** [comment]
Nope, this is `gnome-mpv`. I got a suggestion that it may be my ffmpeg version. Mine is current 3.4.2-2

**Comment by gnome-mpv** [comment]
Can you run `G_MESSAGES_DEBUG=all gnome-mpv`, reproduce the bug, and post the result here?

Also, post the output of `mpv --version`.
