### ISSUE TITLE
Gnome-mpv does not honor mpv.conf despite told to

### ISSUE THREAD

**Issue by Beardedgeek72** [gnome-mpv/gnome-mpv#367]
Overview Description:
Despite telling Gnome-mpv in preferences to load a specific mpv.conf, the program happily ignores the file.
If I during playback go into settings and just close it again, it suddenly runs the ongoing playback according to the mpv.conf, but it has forgotten it by the time the next video is played.

Steps to Reproduce:
1. create mpv.conf
2. point gnome-mpv to load that file.
3. Watch it obviously ignore it (window placement, window size, hardware rendering all ignored).

Actual Results:
gnome-mpv runs on default settings at all times

Expected Results:
gnome-mpv should run according to mpv.conf (start with video size x 2 unless that result in bigger than 75% of screen height, always start in the middle of screen even when resized).

Version:
0.14-2

Additional Information:
Manjaro repositories. I have not tried the AUR version (which is older, it seems, version 0.13)

**Comment by gnome-mpv** [comment]
Can you post your config file here?

**Comment by Beardedgeek72** [comment]
Here's my very short and to the point mvp.conf. It works perfectly in mpv on the same machine:

geometry=50%:50%
window-scale=2
autofit-larger=100%x75%
video-sync=display-resample
cache-default=153600

**Comment by gnome-mpv** [comment]
Looks like the config file is being loaded, but the windowing-related options are not being handled correctly. Other options should work fine though.

**Comment by Beardedgeek72** [comment]
Any idea why?

**Comment by gnome-mpv** [comment]
Probably a bug in the code that handles these options. I'll look into it later.

**Comment by Beardedgeek72** [comment]
Thank you.
I prefer players with an MPV base generally. In the meantime I'll just use plain MPV. Your UI is just the perfect ammount which I why I would prefer it.

**Comment by gnome-mpv** [comment]
Fixed in cd1636ed9c20b2f6b5696767833072eccdd8c883 and 4b7ba0afd588bb700003f46367d63265a2e66b7c.

**Comment by teohhanhui** [comment]
Seems like it's not working as expected.

Here's my mpv.conf: https://gist.github.com/teohhanhui/1cbb218e206a8927169b93079b08a8de

With `mpv`, it opens at the center of the screen, while with `gnome-mpv`, it opens very much off-center towards the top left instead.

**Comment by gnome-mpv** [comment]
Looks like `--geometry` is broken again. Other options seem to be working fine though.

**Comment by gnome-mpv** [comment]
Actually, it's only broken because `gtk_window_move()` doesn't work for toplevel windows on Wayland. On X11, the option works as expected.

**Comment by teohhanhui** [comment]
> most window managers ignore requests for initial window positions (instead using a user-defined placement algorithm) and honor requests after the window has already been shown.

https://developer.gnome.org/gtk4/stable/GtkWindow.html#gtk-window-move

Not sure if relevant.

**Comment by gnome-mpv** [comment]
It won't work on Wayland even after the window is shown. From my understanding, it's not possible to position toplevel windows on Wayland because global coordinates are not available.

**Comment by teohhanhui** [comment]
If I understand correctly, mpv uses `wl_egl_window_resize`, which I also find in gdkwindow-wayland.c: https://gitlab.gnome.org/GNOME/gtk/blob/3.24.8/gdk/wayland/gdkwindow-wayland.c

**Comment by teohhanhui** [comment]
I'm really curious how mpv does it on Wayland... But I don't understand enough about how any of this works. 😂

**Comment by gnome-mpv** [comment]
>If I understand correctly, mpv uses `wl_egl_window_resize`

That's for resizing, not moving. `gdk_window_wayland_move_resize()` handles moving, and it only moves the window [if it's not toplevel](https://gitlab.gnome.org/GNOME/gtk/blob/3.24.8/gdk/wayland/gdkwindow-wayland.c#L3293).

>I'm really curious how mpv does it on Wayland

I think mpv uses XWayland, but I might be wrong.

**Comment by teohhanhui** [comment]
Okay, I get it now. It seems like it's an explicit decision on Wayland's part to not support that.

**Comment by teohhanhui** [comment]
Hmm... https://stackoverflow.com/questions/35633817/how-do-i-set-the-x-y-coordinates-of-a-window-in-wayland#comment59356595_35633817

**Comment by gnome-mpv** [comment]
@teohhanhui 
>set my windows to fullscreen output dimensions with a transparent background, then offset my content within the full screen

Sounds like it would break things in gnome-shell, e.g. the window might appear very small in overview because the transparent window size would much larger than the real window.
