### ISSUE TITLE
all linux distro (arch,ubuntu and fedora , black screen and only sound)

### ISSUE THREAD

**Issue by garynych** [gnome-mpv/gnome-mpv#368]
garynych commented on 2018-07-28 10:54
video no (blacksreen) only sound present this on arch repo, my comment https://aur.archlinux.org/packages/gnome-mpv-git 

if above there is a comment and if you follow the link that gave the user **semen** and return back all that is indicated on github (mpv: Delay setting force-window until after initialization) then and video and soound work
forgive my English, this Google translate

**Comment by garynych** [comment]
PS. and also.. without libmpv-dev & libmpv1 is not build, if you install them and before compilation is going to but the video is not, if you build mpv with the key --enable-libmpv-shared the video and sound is, but breaks here as in the video, that is through time https://youtu.be/38FfJXGkf-M

**Comment by Sesshu** [comment]
Same problem here.
I've made a debug log file with the newest commit. [gnome_mpv_debug.txt](https://github.com/gnome-mpv/gnome-mpv/files/2240958/gnome_mpv_debug.txt)
Also the AUR user's name is symen (not semen).

**Comment by garynych** [comment]
PS2. this problem was not previously
it appeared on the last
Ubuntu  18.04.1 ( linuxmint-19-cinnamon),Fedora 28 (RFRemix-Workstation ),arch (manjaro-cinnamon-17.1.8-stable and antergos-18.7)

**Comment by gnome-mpv** [comment]
I can't reproduce this, but I'll revert the commit for now.

Does this happen if you launch gnome-mpv first, then drag-and-drop the file onto it?
