### ISSUE TITLE
Segfault with msg-level= in mpv.conf

### ISSUE THREAD

**Issue by halocaridina** [gnome-mpv/gnome-mpv#370]
Overview Description: gnome-mpv will not start and segfaults with following core dump:

`Aug 10 06:05:14 thinkpad-x201 kernel: gnome-mpv[30171]: segfault at 557600000044 ip 00007f9362c7b36d sp 00007fff554ea6c0 error 4 in libglib-2.0.so.0.5600.1[7f9362c41000+115000]`
`Aug 10 06:05:14 thinkpad-x201 systemd[1]: Started Process Core Dump (PID 30186/UID 0).`
`Aug 10 06:05:17 thinkpad-x201 systemd-coredump[30187]: Process 30171 (gnome-mpv) of user 1000 dumped core.`
                                                       
                                                       Stack trace of thread 30171:
                                                       #0  0x00007f9362c7b36d g_hash_table_iter_next (libglib-2.0.so.0)
                                                       #1  0x00005576d01fe60c n/a (gnome-mpv)
                                                       #2  0x00005576d01ff015 n/a (gnome-mpv)
                                                       #3  0x00007f9362f67a4d g_closure_invoke (libgobject-2.0.so.0)
                                                       #4  0x00007f9362f7ae40 n/a (libgobject-2.0.so.0)
                                                       #5  0x00007f9362f836f6 g_signal_emit_valist (libgobject-2.0.so.0)
                                                       #6  0x00007f9362f84130 g_signal_emit (libgobject-2.0.so.0)
                                                       #7  0x00007f9362f6c076 n/a (libgobject-2.0.so.0)
                                                       #8  0x00007f9362f6e50a g_object_notify (libgobject-2.0.so.0)
                                                       #9  0x00005576d01fb64d n/a (gnome-mpv)
                                                       #10 0x00005576d01fd6db n/a (gnome-mpv)
                                                       #11 0x00005576d01fa056 n/a (gnome-mpv)
                                                       #12 0x00007f9362f67a4d g_closure_invoke (libgobject-2.0.so.0)
                                                       #13 0x00007f9362f7ae40 n/a (libgobject-2.0.so.0)
                                                       #14 0x00007f9362f836f6 g_signal_emit_valist (libgobject-2.0.so.0)
                                                       #15 0x00007f9362f8460c g_signal_emit_by_name (libgobject-2.0.so.0)
                                                       #16 0x00005576d02049db n/a (gnome-mpv)
                                                       #17 0x00007f93641ebbfc n/a (libgtk-3.so.0)
                                                       #18 0x00007f9364339512 n/a (libgtk-3.so.0)
                                                       #19 0x00007f9362f67a4d g_closure_invoke (libgobject-2.0.so.0)
                                                       #20 0x00007f9362f7a9d3 n/a (libgobject-2.0.so.0)
                                                       #21 0x00007f9362f83081 g_signal_emit_valist (libgobject-2.0.so.0)
                                                       #22 0x00007f9362f84130 g_signal_emit (libgobject-2.0.so.0)
                                                       #23 0x00007f9364346503 n/a (libgtk-3.so.0)
                                                       #24 0x00007f936434f893 n/a (libgtk-3.so.0)
                                                       #25 0x00007f93641eac0a gtk_main_do_event (libgtk-3.so.0)
                                                       #26 0x00007f9363cfa526 n/a (libgdk-3.so.0)
                                                       #27 0x00007f9363d0abcb n/a (libgdk-3.so.0)
                                                       #28 0x00007f9363d0be29 n/a (libgdk-3.so.0)
                                                       #29 0x00007f9363d0c029 n/a (libgdk-3.so.0)
                                                       #30 0x00007f9362f67a4d g_closure_invoke (libgobject-2.0.so.0)
                                                       #31 0x00007f9362f7ae40 n/a (libgobject-2.0.so.0)
                                                       #32 0x00007f9362f836f6 g_signal_emit_valist (libgobject-2.0.so.0)
                                                       #33 0x00007f9362f84130 g_signal_emit (libgobject-2.0.so.0)
                                                       #34 0x00007f9363d03c5a n/a (libgdk-3.so.0)
                                                       #35 0x00007f9363cee843 n/a (libgdk-3.so.0)
                                                       #36 0x00007f9362c8dcb3 n/a (libglib-2.0.so.0)
                                                       #37 0x00007f9362c8d1d6 g_main_context_dispatch (libglib-2.0.so.0)
                                                       #38 0x00007f9362c8d5b1 n/a (libglib-2.0.so.0)
                                                       #39 0x00007f9362c8d63e g_main_context_iteration (libglib-2.0.so.0)
                                                       #40 0x00007f936325097e g_application_run (libgio-2.0.so.0)
                                                       #41 0x00005576d01e93cc main (gnome-mpv)
                                                       #42 0x00007f936236f003 __libc_start_main (libc.so.6)
                                                       #43 0x00005576d01e940a n/a (gnome-mpv)
                                                       
                                                       Stack trace of thread 30176:
                                                       #0  0x00007f93624411ed syscall (libc.so.6)
                                                       #1  0x00007f9362cd452d g_cond_wait_until (libglib-2.0.so.0)
                                                       #2  0x00007f9362c5f903 n/a (libglib-2.0.so.0)
                                                       #3  0x00007f9362cb6436 n/a (libglib-2.0.so.0)
                                                       #4  0x00007f9362cb5a2a n/a (libglib-2.0.so.0)
                                                       #5  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #6  0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30180:
                                                       #0  0x00007f936244149b __mprotect (libc.so.6)
                                                       #1  0x00007f93623ce37c sysmalloc (libc.so.6)
                                                       #2  0x00007f93623cf4f6 _int_malloc (libc.so.6)
                                                       #3  0x00007f93623d08ba malloc (libc.so.6)
                                                       #4  0x00007f936297830a n/a (libmpv.so.1)
                                                       #5  0x00007f9362978a71 n/a (libmpv.so.1)
                                                       #6  0x00007f9362978d35 n/a (libmpv.so.1)
                                                       #7  0x00007f936297930f n/a (libmpv.so.1)
                                                       #8  0x00007f93628dd3bd n/a (libmpv.so.1)
                                                       #9  0x00007f93628d3651 n/a (libmpv.so.1)
                                                       #10 0x00007f93628d3ace n/a (libmpv.so.1)
                                                       #11 0x00007f93628e8d5f n/a (libmpv.so.1)
                                                       #12 0x00007f93628e8e1d n/a (libmpv.so.1)
                                                       #13 0x00007f93628dadb0 n/a (libmpv.so.1)
                                                       #14 0x00007f93628dbc3d mpv_get_property (libmpv.so.1)
                                                       #15 0x00007f93628f226e n/a (libmpv.so.1)
                                                       #16 0x00007f9356eb0025 n/a (liblua5.2.so.5.2)
                                                       #17 0x00007f9356ebbbe5 n/a (liblua5.2.so.5.2)
                                                       #18 0x00007f9356eb034e n/a (liblua5.2.so.5.2)
                                                       #19 0x00007f9356eac38b lua_callk (liblua5.2.so.5.2)
                                                       #20 0x00007f93628f076f n/a (libmpv.so.1)
                                                       #21 0x00007f9356eb0025 n/a (liblua5.2.so.5.2)
                                                       #22 0x00007f9356eb0342 n/a (liblua5.2.so.5.2)
                                                       #23 0x00007f9356eac38b lua_callk (liblua5.2.so.5.2)
                                                       #24 0x00007f9356ec72c7 n/a (liblua5.2.so.5.2)
                                                       #25 0x00007f9356eb0025 n/a (liblua5.2.so.5.2)
                                                       #26 0x00007f9356ebbbe5 n/a (liblua5.2.so.5.2)
                                                       #27 0x00007f9356eb034e n/a (liblua5.2.so.5.2)
                                                       #28 0x00007f9356eac38b lua_callk (liblua5.2.so.5.2)
                                                       #29 0x00007f93628f1b87 n/a (libmpv.so.1)
                                                       #30 0x00007f93628f1c8b n/a (libmpv.so.1)
                                                       #31 0x00007f9356eb0025 n/a (liblua5.2.so.5.2)
                                                       #32 0x00007f9356eb0342 n/a (liblua5.2.so.5.2)
                                                       #33 0x00007f9356eaf97f n/a (liblua5.2.so.5.2)
                                                       #34 0x00007f9356eb05b1 n/a (liblua5.2.so.5.2)
                                                       #35 0x00007f9356eac451 lua_pcallk (liblua5.2.so.5.2)
                                                       #36 0x00007f93628f3966 n/a (libmpv.so.1)
                                                       #37 0x00007f9356eb0025 n/a (liblua5.2.so.5.2)
                                                       #38 0x00007f9356eb0342 n/a (liblua5.2.so.5.2)
                                                       #39 0x00007f9356eaf97f n/a (liblua5.2.so.5.2)
                                                       #40 0x00007f9356eb05b1 n/a (liblua5.2.so.5.2)
                                                       #41 0x00007f9356eac451 lua_pcallk (liblua5.2.so.5.2)
                                                       #42 0x00007f93628f3e5c n/a (libmpv.so.1)
                                                       #43 0x00007f93628fafca n/a (libmpv.so.1)
                                                       #44 0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #45 0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30178:
                                                       #0  0x00007f936243b991 __poll (libc.so.6)
                                                       #1  0x00007f935730e673 n/a (libpulse.so.0)
                                                       #2  0x00007f93572ff990 pa_mainloop_poll (libpulse.so.0)
                                                       #3  0x00007f93572fffe0 pa_mainloop_iterate (libpulse.so.0)
                                                       #4  0x00007f9357300091 pa_mainloop_run (libpulse.so.0)
                                                       #5  0x00007f935730e5ae n/a (libpulse.so.0)
                                                       #6  0x00007f93499d99fc n/a (libpulsecommon-12.2.so)
                                                       #7  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #8  0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30181:
                                                       #0  0x00007f930342a3fa n/a (i965_dri.so)
                                                       #1  0x00007f930342fa7f n/a (i965_dri.so)
                                                       #2  0x00007f930347e73f n/a (i965_dri.so)
                                                       #3  0x00007f930343e3fb n/a (i965_dri.so)
                                                       #4  0x00007f9303440f50 n/a (i965_dri.so)
                                                       #5  0x00007f9303441f59 n/a (i965_dri.so)
                                                       #6  0x00007f93034ec5d3 n/a (i965_dri.so)
                                                       #7  0x00007f93034fad2e n/a (i965_dri.so)
                                                       #8  0x00007f93034fd23a n/a (i965_dri.so)
                                                       #9  0x00007f9302fca812 n/a (i965_dri.so)
                                                       #10 0x00007f9302fcc8c8 n/a (i965_dri.so)
                                                       #11 0x00007f9302fcf74d n/a (i965_dri.so)
                                                       #12 0x00007f9362952619 n/a (libmpv.so.1)
                                                       #13 0x00007f9362944c08 n/a (libmpv.so.1)
                                                       #14 0x00007f936295859c n/a (libmpv.so.1)
                                                       #15 0x00007f9362956d09 n/a (libmpv.so.1)
                                                       #16 0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #17 0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30184:
                                                       #0  0x00007f9360b7a426 do_futex_wait.constprop.1 (libpthread.so.0)
                                                       #1  0x00007f9360b7a528 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
                                                       #2  0x00007f936296e569 n/a (libmpv.so.1)
                                                       #3  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #4  0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30173:
                                                       #0  0x00007f936243b991 __poll (libc.so.6)
                                                       #1  0x00007f9362c8d523 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f9362c8d8e2 g_main_loop_run (libglib-2.0.so.0)
                                                       #3  0x00007f936327e348 n/a (libgio-2.0.so.0)
                                                       #4  0x00007f9362cb5a2a n/a (libglib-2.0.so.0)
                                                       #5  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #6  0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30177:
                                                       #0  0x00007f93624411ed syscall (libc.so.6)
                                                       #1  0x00007f9362cd452d g_cond_wait_until (libglib-2.0.so.0)
                                                       #2  0x00007f9362c5f903 n/a (libglib-2.0.so.0)
                                                       #3  0x00007f9362cb6436 n/a (libglib-2.0.so.0)
                                                       #4  0x00007f9362cb5a2a n/a (libglib-2.0.so.0)
                                                       #5  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #6  0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30175:
                                                       #0  0x00007f9360b77aec pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                       #1  0x00007f93628c47b6 n/a (libmpv.so.1)
                                                       #2  0x00007f93628f753a n/a (libmpv.so.1)
                                                       #3  0x00007f93628f9d42 n/a (libmpv.so.1)
                                                       #4  0x00007f93628da679 n/a (libmpv.so.1)
                                                       #5  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #6  0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30179:
                                                       #0  0x00007f93648feac2 do_lookup_x (ld-linux-x86-64.so.2)
                                                       #1  0x00007f93648ff63f _dl_lookup_symbol_x (ld-linux-x86-64.so.2)
                                                       #2  0x00007f9364903e57 _dl_fixup (ld-linux-x86-64.so.2)
                                                       #3  0x00007f936490a7b7 _dl_runtime_resolve_fxsave (ld-linux-x86-64.so.2)
                                                       #4  0x00007f9356ebdf45 luaL_checknumber (liblua5.2.so.5.2)
                                                       #5  0x00007f93628f2bd9 n/a (libmpv.so.1)
                                                       #6  0x00007f9356eb0025 n/a (liblua5.2.so.5.2)
                                                       #7  0x00007f9356ebbbe5 n/a (liblua5.2.so.5.2)
                                                       #8  0x00007f9356eb034e n/a (liblua5.2.so.5.2)
                                                       #9  0x00007f9356eac38b lua_callk (liblua5.2.so.5.2)
                                                       #10 0x00007f93628f1c66 n/a (libmpv.so.1)
                                                       #11 0x00007f9356eb0025 n/a (liblua5.2.so.5.2)
                                                       #12 0x00007f9356eb0342 n/a (liblua5.2.so.5.2)
                                                       #13 0x00007f9356eaf97f n/a (liblua5.2.so.5.2)
                                                       #14 0x00007f9356eb05b1 n/a (liblua5.2.so.5.2)
                                                       #15 0x00007f9356eac451 lua_pcallk (liblua5.2.so.5.2)
                                                       #16 0x00007f93628f3966 n/a (libmpv.so.1)
                                                       #17 0x00007f9356eb0025 n/a (liblua5.2.so.5.2)
                                                       #18 0x00007f9356eb0342 n/a (liblua5.2.so.5.2)
                                                       #19 0x00007f9356eaf97f n/a (liblua5.2.so.5.2)
                                                       #20 0x00007f9356eb05b1 n/a (liblua5.2.so.5.2)
                                                       #21 0x00007f9356eac451 lua_pcallk (liblua5.2.so.5.2)
                                                       #22 0x00007f93628f3e5c n/a (libmpv.so.1)
                                                       #23 0x00007f93628fafca n/a (libmpv.so.1)
                                                       #24 0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #25 0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30172:
                                                       #0  0x00007f936243b991 __poll (libc.so.6)
                                                       #1  0x00007f9362c8d523 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f9362c8d63e g_main_context_iteration (libglib-2.0.so.0)
                                                       #3  0x00007f9362c8d692 n/a (libglib-2.0.so.0)
                                                       #4  0x00007f9362cb5a2a n/a (libglib-2.0.so.0)
                                                       #5  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #6  0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30174:
                                                       #0  0x00007f936243b991 __poll (libc.so.6)
                                                       #1  0x00007f9362c8d523 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f9362c8d63e g_main_context_iteration (libglib-2.0.so.0)
                                                       #3  0x00007f933a2dcf4e n/a (libdconfsettings.so)
                                                       #4  0x00007f9362cb5a2a n/a (libglib-2.0.so.0)
                                                       #5  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #6  0x00007f9362446823 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 30185:
                                                       #0  0x00007f9360b77aec pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                       #1  0x00007f930307f1a4 n/a (i965_dri.so)
                                                       #2  0x00007f930307ee98 n/a (i965_dri.so)
                                                       #3  0x00007f9360b71a8d start_thread (libpthread.so.0)
                                                       #4  0x00007f9362446823 __clone (libc.so.6)`

when following `msg-level=` option is included in mpv.conf:

``msg-level=af=fatal:ffmpeg=fatal:ao=warn:cplayer=warn:statusline=status:demux=status``

Steps to Reproduce:
1. include following two options in mpv.conf:
`msg-color`
`msg-level=af=fatal:ffmpeg=fatal:ao=warn:cplayer=warn:statusline=status:demux=status`

2. gnome-mpv segfaults and core dumps on startup
3. comment `msg-color`, start gnome-mpv and segfault/core dump occurs
4. uncomment `msg-color`  and comment `msg-level=af=fatal:ffmpeg=fatal:ao=warn:cplayer=warn:statusline=status:demux=status` , start gnome-mpv and segfault/core dump DOES NOT occur

Actual Results: gnome-mpv consistently segfault/core dump when `msg-level=`  option included in mpv.conf

Expected Results: gnome-mpv should not segfault/core dump or should warn of unsupported option `msg-level=`  and quit rather than segfault/core dump.

Version: 
`community/gnome-mpv 0.14-2 (120.7 KiB 476.0 KiB) (Installed: 0.13-1)`
   `Simple GTK+ frontend for mpv`
`antergos/gnome-mpv 0.13-1 (129.0 KiB 742.0 KiB) (Installed)`
    `A simple GTK+ frontend for mpv.`

Additional Information:

**Comment by gnome-mpv** [comment]
Confirmed.

For some reason, this only happens if `meson` was run with `--buildtype=release` during build.
