### ISSUE TITLE
Keep the same window size when showing/hiding playlist when tiled

### ISSUE THREAD

**Issue by smithfred** [gnome-mpv/gnome-mpv#381]
Currently when tiled left/right, showing/hiding the playlist grows/shrinks the window, and exhibits buggy behaviour.

* When tiled left, the window grows or shrinks in size, but retains its "tiled" border (no corner radius etc.)
* When switching to another window afterwards, GNOME MPV's window changes back to being 50% width again.
* When trying to grab the window edge afterwards, it snaps momentarily back to 50% width then to the wider/narrower size it had as a result of the playlist.
* When tiled right, the playlist goes off-screen.

**Comment by smithfred** [comment]
Thanks for the quick patch! But I think this set of problems will still exist if the user has the new "enable resizing" pref set - all of the above issues will still manifest then, and so GNOME MPV will still be buggy in that case, unless I'm missing something?

Is it not possible to detect if the window is tiled, and conditionally not resize the window then?

**Comment by gnome-mpv** [comment]
>Is it not possible to detect if the window is tiled

AFAIK that's not possible.

**Comment by gnome-mpv** [comment]
fa6a166eeaffb05b8580dfedd8be3e98b8fe8b38
