### ISSUE TITLE
--rtsp-transport=udp --deinterlace  >> 'unknown option(s)' with gnome-mpv? mpv works 

### ISSUE THREAD

**Issue by J0Ar** [gnome-mpv/gnome-mpv#382]
**Overview Description:**
I installed _gnome-mpv 0.13-1ubuntu1_ and _mpv 0.27.2-1ubuntu1_ from the distribution repositories (elementaryOS 5.0 juno, so Ubuntu 18.04) and i noticed, _gnome-mpv_ does not start with the command line options as seen in the screenshot.
Then i tried the newest versions as mentioned in the ReadMe and Wikis, but this also did not work :/ Whats the problem here...why _gnome-mpv_ do not accept the given options in command line...but _mpv_ works? Is there a problem with the libmpv?
I'm just a user with little technical skills...*going for cover *

**Actual Results:**
gnome-mpv does not start with option _--rtsp-transport=udp_ or _--deinterlace_ 
> unknown option --rtsp-transport=udp

![gnome-mpv do not work](https://user-images.githubusercontent.com/23266409/46005812-640db180-c0b6-11e8-862d-95ab6eb5b498.png)

**Expected Results:**
gnome-mpv starts like mpv does, with the options mentioned above
![mpv works](https://user-images.githubusercontent.com/23266409/46005817-696afc00-c0b6-11e8-9993-35601bf41fdb.png)

**Version:** tried with _0.13-1ubuntu1_ and _0.15-1~bionic1_

**Additional Information:**
```
System:    Host: home Kernel: 4.15.0-34-generic x86_64 bits: 64 gcc: 7.3.0
           Desktop: Gnome  (Gtk 3.22.30-1ubuntu1) dm: lightdm Distro: elementary OS 5.0 Juno
CPU:       Quad core AMD Ryzen 3 2200G with Radeon Vega Graphics (-MCP-) arch: Zen rev.0 cache: 2048 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 27947
           clock speeds: min/max: 1600/3500 MHz 1: 1568 MHz 2: 1445 MHz 3: 1486 MHz 4: 1584 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480]
           bus-ID: 01:00.0 chip-ID: 1002:67df
           Display Server: x11 (X.Org 1.19.6 ) drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa,radeon)
           Resolution: 1600x900@60.00hz
           OpenGL: renderer: AMD Radeon RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-34-generic, LLVM 6.0.0)
           version: 4.5 Mesa 18.0.5 (compat-v: 3.0) Direct Render: Yes
```

**Comment by gnome-mpv** [comment]
There's no way to pass mpv options from the command line yet. Instead, you can set mpv options with a config file.

**Comment by J0Ar** [comment]
Thanks for your quick reply. 
What i would like to do is...create a separate gnome-mpv.desktop file to open a playlist with gnome-mpv and the mentioned the options. There is a [german site](https://linuxundich.de/gnu-linux/fritzbox-tv-mit-gnome-mpv-alternative-zu-vlc/) where the author get it working, i think...look here...
![bildschirmfoto von 2018-09-25 11-59-42](https://user-images.githubusercontent.com/23266409/46007626-d1234600-c0ba-11e8-8563-98b2d925d675.png)

...maybe i'm doing something wrong in my understanding? 
```
[Desktop Entry]
Version=1.0
Name[de_DE]=Fritz!TV
Name=GNOME MPV
Comment[de_DE]=TV mit Gnome-MPV
Comment=GTK+ frontend for mpv
Exec=gnome-mpv /home/jar_el/Videos/1_tvsd.m3u --rtsp-transport=udp --deinterlace
Icon=/home/jar_el/.local/share/icons/Fritz!TV.png
Terminal=false
Type=Application
StartupNotify=true
DBusActivatable=true
Categories=GTK;GNOME;Player;Video;TV;AudioVideo;
MimeType=application/mpeg4-iod;application/mpeg4-muxcodetable;application/mxf;application/ogg;application/ram;application/sdp;application/streamingmedia;application/vnd.apple.mpegurl;application/vnd.ms-asf;application/vnd.rn-realmedia;application/vnd.rn-realmedia-vbr;application/x-extension-m4a;application/x-extension-mp4;application/x-flac;application/x-flash-video;application/x-matroska;application/x-ogg;application/x-streamingmedia;audio/3gpp;audio/3gpp2;audio/aac;audio/ac3;audio/amr;audio/amr-wb;audio/basic;audio/dv;audio/eac3;audio/flac;audio/m4a;audio/midi;audio/mp1;audio/mp2;audio/mp3;audio/mp4;audio/mpeg;audio/mpegurl;audio/mpg;audio/ogg;audio/opus;audio/scpls;audio/vnd.dolby.heaac.1;audio/vnd.dolby.heaac.2;audio/vnd.dolby.mlp;audio/vnd.dts;audio/vnd.dts.hd;audio/vnd.rn-realaudio;audio/wav;audio/webm;audio/x-aac;audio/x-aiff;audio/x-ape;audio/x-flac;audio/x-gsm;audio/x-it;audio/x-m4a;audio/x-matroska;audio/x-mod;audio/x-mp1;audio/x-mp2;audio/x-mp3;audio/x-mpeg;audio/x-mpegurl;audio/x-mpg;audio/x-ms-asf;audio/x-ms-wma;audio/x-musepack;audio/x-pn-aiff;audio/x-pn-au;audio/x-pn-realaudio;audio/x-pn-wav;audio/x-real-audio;audio/x-realaudio;audio/x-s3m;audio/x-scpls;audio/x-shorten;audio/x-speex;audio/x-tta;audio/x-vorbis;audio/x-vorbis+ogg;audio/x-wav;audio/x-wavpack;audio/x-xm;video/3gp;video/3gpp;video/3gpp2;video/divx;video/dv;video/fli;video/flv;video/mp2t;video/mp4;video/mp4v-es;video/mpeg;video/mpeg-system;video/msvideo;video/ogg;video/quicktime;video/vnd.mpegurl;video/vnd.rn-realvideo;video/webm;video/x-avi;video/x-flc;video/x-fli;video/x-flv;video/x-m4v;video/x-matroska;video/x-mpeg;video/x-mpeg-system;video/x-mpeg2;video/x-ms-asf;video/x-ms-wm;video/x-ms-wmv;video/x-ms-wmx;video/x-msvideo;video/x-nsv;video/x-ogm+ogg;video/x-theora;video/x-theora+ogg;x-content/audio-cdda;x-content/audio-player;x-content/video-dvd;x-scheme-handler/mms;x-scheme-handler/mmsh;x-scheme-handler/rtmp;x-scheme-handler/rtp;x-scheme-handler/rtsp;
X-KDE-Protocols=ftp,http,https,mms,rtmp,rtsp,sftp,smb
Actions=new-window;
X-GNOME-FullName[de_DE]=Fritz!TV
NoDisplay=false
Path=
X-GNOME-UsesNotifications=false

[Desktop Action new-window]
Name[de_DE]=Neues Fenster
Name=New Window
Exec=gnome-mpv --new-window
```

**Comment by gnome-mpv** [comment]
I don't know how the author got it working; it doesn't seem like that desktop file would work to me.

You can do what you want by removing the command line options, installing [this Lua plugin](https://raw.githubusercontent.com/wiiaboo/mpv-scripts/master/auto-profiles.lua), and adding this profile to your config file:

````
[playlist]
profile-desc=cond:p.path=='/home/jar_el/Videos/1_tvsd.m3u'
rtsp-transport=udp
deinterlace
````

**Comment by J0Ar** [comment]
Ok i found another solution...
- First i made a [file-specified configuration file]( https://mpv.srsfckn.biz/manual.pdf#%5B%7B%22num%22%3A259%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C62.69291%2C213.8236%2C0%5D ) with the name _1_tvsd.m3u.conf_ which loads the options
```
rtsp-transport=udp
deinterlace
```
- Then in gnome-mpv settings i add the option --use-filedir-conf ![bildschirmfoto von 2018-09-25 18-35-37](https://user-images.githubusercontent.com/23266409/46028813-dbad0200-c0f1-11e8-91c3-dcb08272e195.png)
- and last...the Fritz!TV.desktop file with AppEditor... ![bildschirmfoto von 2018-09-25 18-39-13](https://user-images.githubusercontent.com/23266409/46028999-6aba1a00-c0f2-11e8-8535-9e1be11ffaf8.png)
**Anyway, thank you very much for your help/hints and all the work on the best player 8)**
