### ISSUE TITLE
Volume muted after "Unrecognized file format" dialog

### ISSUE THREAD

**Issue by Flurrywinde** [gnome-mpv/gnome-mpv#383]
Overview Description: If there's a bad file in the playlist (i.e. the Unrecognized file format dialog popup is triggered), the volume is muted for the next video.

Steps to Reproduce:
1. Load some videos from the command line with at least one bad one: `gnome-mpv *.mp4`
2. Wait for the Unrecognized file format dialog to appear, and click Ok
3. Volume is muted when it wasn't before

Actual Results: Volume is muted

Expected Results: Volume should be the same as before

Version: 0.9

Additional Information:

I am on Ubuntu 16.04, so v.0.9 is the latest, correct?

Is there a way to skip right on past bad video files without bringing up the error dialog box? And if so, will the next video still begin paused? I'd like it not to be.

I tried to compile the latest git master branch, but I got:

```
# ./autogen.sh 
configure.ac:30: error: AX_APPEND_COMPILE_FLAGS is not defined. Is autoconf-archive installed?
configure.ac:27: GM_CHECK_MACRO is expanded from...
configure.ac:30: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
```
Then, with meson:

```
WARNING: -Wl,-z,relro looks like a linker argument, but has_argument and other similar methods only support checking compiler arguments. Using them to check linker arguments are never supported, and results are likely to be wrong regardless of the compiler you are using. has_link_argument or other similar method can be used instead.
Compiler for C supports arguments -Wl,-z,relro: YES
WARNING: -Wl,-z,now looks like a linker argument, but has_argument and other similar methods only support checking compiler arguments. Using them to check linker arguments are never supported, and results are likely to be wrong regardless of the compiler you are using. has_link_argument or other similar method can be used instead.
Compiler for C supports arguments -Wl,-z,now: YES
Checking for function "setlocale": YES
Program generate_authors.py found: YES (/home/kanon/util/gnome-mpv/src/generate_authors.py)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gtk+-3.0 found: NO found '3.18.9' but need: '>= 3.20'

src/meson.build:49:0: ERROR:  Invalid version of dependency, need 'gtk+-3.0' ['>= 3.20'] found '3.18.9'.
```

**Comment by gnome-mpv** [comment]
I can't reproduce this.

>I am on Ubuntu 16.04, so v.0.9 is the latest, correct?

You can install a newer version using [Flatpak](https://github.com/gnome-mpv/gnome-mpv#flatpak).

>Is there a way to skip right on past bad video files without bringing up the error dialog box? And if so, will the next video still begin paused? I'd like it not to be.

Not at this time.

**Comment by gnome-mpv** [comment]
Feel free to reopen if you can reproduce this with v0.15 or git master.
