### ISSUE TITLE
App-menu get’s lost in full-screen

### ISSUE THREAD

**Issue by fbruetting** [gnome-mpv/gnome-mpv#386]
#### Overview Description:

When you have the app-menu set to appear in the header bar (by Gnome Tweaks), the application icon get’s lost when you switch to full-screen.

#### Steps to Reproduce:

1. Deactivate the application menus in the headerbar section of Gnome tweaks.
2. Open a video in Gnome-MPV.
3. Switch to full-screen.

#### Actual Results:

App-icon is missing and app-menu isn’t accessible.

#### Expected Results:

App-icon and app-menu present, like shown here (maximized windo, not full-screen):

![bildschirmfoto von 2018-10-13 19-31-26](https://user-images.githubusercontent.com/10520767/46908161-ccfe8180-cf1e-11e8-9f20-6678952d1bad.png)

#### Version:

v0.15-Flatpak

**Comment by TingPing** [comment]
On a related note it should probably remove the appmenu this cycle anyway as GNOME is removing it anyway.

**Comment by gnome-mpv** [comment]
Appmenu has been removed (c96f9be84812e51be00bbc27ebaf343071e0361f).
