### ISSUE TITLE
mpris should use different service for each window

### ISSUE THREAD

**Issue by TingPing** [gnome-mpv/gnome-mpv#388]
Overview Description:

Since gnome-mpv supports multiple windows in one instance each window should have a separate mpris service.

I tried to fix this simply by appending a window id to each mpris service and indeed that makes each window have one. My confusion following though was that they conflicted with each other; The metadata from the second instance overwrote the first and playback controls always went to the first window. This didn't make sense at a glance since each window has its own Controller and each Mpris service is made with a different Controller. Maybe I missed something obvious.

Steps to Reproduce:
1. Open two windows playing media
2. Control each window via mpris separately

**Comment by JasonLG1979** [comment]
I was looking into this while I was testing out a method to connect Mpris interfaces to their respective application windows, for use in my mpris gnome extension. It's works very well with VLC since they use Instance<pid> (as suggested by the mpris spec) for all instances after the 1st. But it does not work at all with multiple instances of gnome-mpv.

Anyway, currently as you said there is only ever one mpris interface. Looking at the system monitor even if the pid was used I don't think it would matter since they don't seem to be true separate instances. I only show one gnome-mpv process even when I have more than one window open. That may be part of the problem? Do your mpris interfaces have different name owners or are they both pointing to the same name?

**Comment by JasonLG1979** [comment]
And all windows have the same pid according to shell-app.get_windows... So yep, not true unique instances.

**Comment by TingPing** [comment]
@JasonLG1979 PIDs are useless in a Flatpak'd world since they run in a pid namespace you get duplicates.

**Comment by TingPing** [comment]
And yes also multiple `gnome-mpv` windows are in one process. I think we should decouple that. This does mean we need a new way to associate windows to mpris but that will probably be via some x11/wayland specific id if that exists.

**Comment by JasonLG1979** [comment]
The connection owner name (the ::<i>random number</i> name not the busName) is the same for all interfaces created by the apps. DBus activatable app window also have a gtk_unique_bus_name prop that corresponds to that connection owner name. If they were true separate instances that number would be different.

**Comment by JasonLG1979** [comment]
I think the most straight forward solution is to actually spawn a new instance.

**Comment by JasonLG1979** [comment]
Here's all the props I can get from a window:
https://github.com/GNOME/mutter/blob/fa1add2ee6d440020a6ef866b6ce2c310ef84239/src/core/window.c#L159-L183

**Comment by JasonLG1979** [comment]
My main reason for trying to connect a mpris instance to it's window is a what I would consider a bug in Shellapp's. As far as GNOME shell is concerned there is no distinction between instances. There are just apps and windows. If for example I have 2 instances of VLC in my mpris extension and I try to raise one with ShellApp.activate(), regardless of which one I want to raise the Shell will just raise the last VLC window that was interacted with. There's also no way to directly minimize a player via mpris nor ShellApp to do that I need to get a hold of the window.

**Comment by JasonLG1979** [comment]
Just tested comparing the owner name of the mpris interface and gtk_unique_bus_name to grab the Flatpak version of Pithos' window and it works seamlessly. 

```js
    _getNewAppWindow() {
        for (let w of this._app.get_windows()) {
            if (!w.skip_taskbar && w.window_type === Meta.WindowType.NORMAL
                && (w.get_pid() === this._pid || w.gtk_unique_bus_name === this._nameOwner)) {
                return w;
            }
        }
        return null;
    }
```
The pid's don't match like you said ofc. That's really the best I can come up with.

**Comment by TingPing** [comment]
> I think the most straight forward solution is to actually spawn a new instance.

The problem with that is gapplication's bus name ownership. `io.github.GnomeMpv` can only be owned by one instance.

**Comment by JasonLG1979** [comment]
> The problem with that is gapplication's bus name ownership. `io.github.GnomeMpv` can only be owned by one instance.

Well that sounds like a bug if you can't create real multiple instances.

**Comment by JasonLG1979** [comment]
You can't have the 1st, and thus primary instance own ```io.github.GnomeMpv``` and other instances after that own ```io.github.GnomeMpv.Instance<random number>```? Is there not a concept of real transient children instances in  gapplication? If not there should be.

**Comment by TingPing** [comment]
> You can't have the 1st, and thus primary instance own io.github.GnomeMpv and other instances after that own io.github.GnomeMpv.Instance<random number>? 

You could. You lose things like DBus activation at that point but it might be ok.

> Is there not a concept of real transient children instances in gapplication? If not there should be.

Nope.

**Comment by JasonLG1979** [comment]
Btw: With what I'm working on I've been able to fix not being able to raise the Spotify Flatpak via my extension. Not only can I raise it but I can also minimize it because I can get ahold of the window.

**Comment by TingPing** [comment]
> With what I'm working on I've been able to fix not being able to raise the Spotify Flatpak via my extension. Not only can I raise it but I can also minimize it because I can get ahold of the window.

Cool, please reach out to the Plasma folks to implement the same fix. They hardcode that desktop-id == mpris-id (which I plan on changing for Pithos/GNOME-MPV) but its not reliable at all.

**Comment by JasonLG1979** [comment]
> Cool, please reach out to the Plasma folks to implement the same fix. They hardcode that desktop-id == mpris-id (which I plan on changing for Pithos/GNOME-MPV) but its not reliable at all.

Do you mean setting the mprist "Identity" prop to the same thing as the "Identity" prop?

If so don't do that, it's wrong. Identity is suppose to be just the name of the player primarily for display purposes. DesktopEntry is suppose to be for getting a hold of the player, the name of the desktop entry file minus .desktop.

**Comment by JasonLG1979** [comment]
> Even worse they do this: https://cgit.kde.org/plasma-desktop.git/tree/applets/taskmanager/package/contents/ui/main.qml?h=v5.12.0&id=d3e7a1985b7fd769514e1cbd8cf54dafa26863ae#n186
> 
> Which afaict is indeed absolutely incorrect.

It looks like they're trying to fixup apps that send an absolute path to the .desktop file as the DesktopEntry prop?

```io.github.GnomeMpv``` would still be ```io.github.GnomeMpv``` after ```split('/').pop().replace(".desktop", "")```

**Comment by TingPing** [comment]
Oh you are right, but somewhere it is failing to associate the spotify mpris with the spotify window.

**Comment by JasonLG1979** [comment]
That's not their fault. It's because the Flatpak'd desktop desktop entry doesn't match what spotify is sending as a desktop entry over mpris. The same reason I was unable to raise it with ```app.activate();```

The only way to fix that would be to either somehow intercept what's being sent in the flatpak and change it to the correct value or have Spotify package their own flatpak and change it themselves.

**Comment by JasonLG1979** [comment]
I workaround it by looking for desktop entries with a startup wm class that matches the Identity prop if I can't find a desktop entry that matches the DesktopEntry prop.

**Comment by TingPing** [comment]
> The only way to fix that would be to either somehow intercept what's being sent in the flatpak and change it to the correct value or have Spotify package their own flatpak and change it themselves.

Thats true, I did consider writing a proxy service just to rewrite that...

**Comment by JasonLG1979** [comment]
OK, I found something useful that could be used to tie a window to a MPRIS interface.

The window's gtk_window_object_path prop will give me the object path of the window (duh, right,lol!!!)

So ```/io/github/GnomeMpv/window/1``` and ```/io/github/GnomeMpv/window/2``` and so on.

If each MPRIS interface Instance number matched it's window number it would simply be a matter of a little regex magic to match them up.

So ```org.mpris.MediaPlayer2.GnomeMpv.instance1``` =  ```/io/github/GnomeMpv/window/1``` and so on.

**Comment by JasonLG1979** [comment]
If that were the case something like this would do the trick.

```js
this._instanceNum = this._getNumbersFromTheEndOf(busName);
.....

    _getNumbersFromTheEndOf(someString) {
        let matches = someString.match(/[0-9]+$/);
        if (matches) {
            return parseInt(matches[0], 10);
        }
        return null;
    }

    _getNormalAppWindows() {
        // We don't want dialogs or what not...
        return Array.from(this._app.get_windows()).filter(w =>
            !w.skip_taskbar && w.window_type === Meta.WindowType.NORMAL
        );
    }

    _getNewAppWindow() {
        // Try to get a hold of an actual window...
        let windows = this._getNormalAppWindows();
        if (windows.length) {
            // Check for multiple instances and flatpak'd apps. (may also work for snaps?)
            for (let w of windows) {
                if (this._instanceNum && w.gtk_window_object_path) {
                    let windowNum = this._getNumbersFromTheEndOf(w.gtk_window_object_path);
                    if (this._instanceNum === windowNum) {
                        return w;
                    }
                    
                }
                if (w.get_pid() === this._pid || w.gtk_unique_bus_name === this._nameOwner) {
                    return w;
                }
            }
            // If all else fails
            // return the 1st window
            // for single instance
            // apps it will be the
            // app's main window.
            return windows[0];
        }
        return null;
    }
```

**Comment by TingPing** [comment]
> So org.mpris.MediaPlayer2.GnomeMpv.instance1 = /io/github/GnomeMpv/window/1 and so on.

It is a good start but that falls apart once you have multiple actual instances.

**Comment by JasonLG1979** [comment]
> It is a good start but that falls apart once you have multiple actual instances.

How so? So far only gapplications have gtk_window_object_path for a real separate instance the pid's would match.

**Comment by TingPing** [comment]
Test running multiple `gnome-mpv --no-existing-session`

**Comment by JasonLG1979** [comment]
Yep, not only do I now get 2 fully functional MPRIS interfaces but I have no problem tying the instances to their windows because they are real seperate instance and the connections pid matches the windows pid. Like I said...

**Comment by JasonLG1979** [comment]
Is ```--no-existing-session``` a commonly used flag or is it mainly used for debugging?

**Comment by JasonLG1979** [comment]
I see what you're saying though with ```--no-existing-session``` you end up with 2 instances with the same window path. In that case  ```org.mpris.MediaPlayer2.GnomeMpv.instance1``` = ```/io/github/GnomeMpv/window/1``` kinda falls apart.

**Comment by TingPing** [comment]
Its undocumented for `gnome-mpv` so users shouldn't rely on it.

**Comment by JasonLG1979** [comment]
Even from a media keybinding standpoint an app is suppose to send it's app id to the keybinding interface. That really does no good when you have multiple windows. There really needs to be some kind of hard distinction between windows. You should be able to specify which window in a standard way other fudging the app id.

**Comment by JasonLG1979** [comment]
A better way for mediakeys would be to be to set up matching window actions and just be able to tell the mediakeys interface "here bind to this window's mediakeys actions" and "unbind this window" instead of grabbing and ungrabbing the keys and listening in a handler.

**Comment by TingPing** [comment]
> Even from a media keybinding standpoint an app is suppose to send it's app id to the keybinding interface. 

The GNOME mediakey service will go away at some point. They want MPRIS to replace it.

**Comment by JasonLG1979** [comment]
> The GNOME mediakey service will go away at some point. They want MPRIS to replace it.

That is a huge mistake IMHO. And they'll for sure need to find a way to tell which window of a fake instance is focused.

**Comment by TingPing** [comment]
Once it has a time focused property I honestly don't see any downside. Associating the window is, as discussed, harder and more likely to have edge cases.

**Comment by TingPing** [comment]
It probably isn't impossible for you or I to become maintainers of the spec.

**Comment by JasonLG1979** [comment]
Ya think,lol...

**Comment by smithfred** [comment]
In case you go down that road: https://community.kde.org/MPRIS#Features_for_MPRIS_3.0

The "player type" feature would definitely be useful.

**Comment by gnome-mpv** [comment]
`gnome-shell` still doesn't redirect MPRIS commands to the last active window, but that's something that needs to be fixed from their side.

**Comment by JasonLG1979** [comment]
> `gnome-shell` still doesn't redirect MPRIS commands to the last active window, but that's something that needs to be fixed from their side.

To clarify:

They direct MPRIS commands to the MPRIS instance with the exception of raise. In their MPRIS client implementation they use activate to raise the player instead of the raise method provided by the player's MPRIS interface. The problem with that is that the underlying Shell App System makes no distinction between your windows and simply raises the one with the highest user_time, the window that was last interacted with because as far as the Shell App System is concerned both of your instances are the same app. This is not just a problem for GApplications but also for players that spawn true separate instances. The same thing happens with VLC for example which does have true separate instances.

**Comment by TingPing** [comment]
@JasonLG1979 Since you are knowledgeable about this could you please report that bug to gnome-shell?

**Comment by JasonLG1979** [comment]
> Since you are knowledgeable about this could you please report that bug to gnome-shell?

I will.

Also it still doesn't work correctly. As far as I can tell you are initializing the MPRIS Interface before the windows and initializing the interface without a DesktopEntry or Identity prop for the 1st window.

**Comment by JasonLG1979** [comment]
I'm not sure what's going wrong but I'd say don't initialize the respective MPRIS interface until the window is mapped.

And after further investigation you're putting up an MPRIS interface without a DesktopEntry or Identity prop at all. Identity is a required prop and in theory DesktopEntry is optional and a client can connect to a prop-changed signal to get updated but none that I know of do. Identity and DesktopEntry should be calculated before the interface is brought up.

**Comment by JasonLG1979** [comment]
Well my bad turns out the 1st issue about the when to initialize the window was bogus. It was a problem with my codes logic and I managed to work around the 2nd issue of not having a DesktopEntry or Identity prop and all seems to work pretty well now.

[My Extension](https://github.com/JasonLG1979/gnome-shell-extensions-mpris-indicator-button) seems to work pretty well. Although it still doesn't work very well with the stock GNOME Shell MPRIS Client.

@TingPing give it a shot.
