### ISSUE TITLE
"Use floating controls in windowed mode" makes controls appear twice

### ISSUE THREAD

**Issue by robertgzr** [gnome-mpv/gnome-mpv#393]
Overview Description:
gnome-mpv shows two control bars (one static, one floating) if "Use floating controls in windowed mode" is enabled in the preferences.

![screenshot](https://i.imgur.com/cHPdJ5y.png)

Version: 0.14

Additional Information:
Setting 'View > Toggle Controls' removes the extra bar.

**Comment by gnome-mpv** [comment]
Confirmed. Only happens when CSD is disabled.

**Comment by robertgzr** [comment]
thx for the quick fix. 

Just as a heads up (I am still on v0.14) but it also happens with CSD enabled

![screenshot](https://i.imgur.com/0embCl0.png)
