### ISSUE TITLE
Remove playlist entries

### ISSUE THREAD

**Issue by robertgzr** [gnome-mpv/gnome-mpv#394]
Currently there is not way to remove playlist entries after adding them
It would also be nice to have a way to clear the entire playlist at once...

**Comment by gnome-mpv** [comment]
>Currently there is not way to remove playlist entries after adding them

You can remove an entry by either right-clicking it and clicking delete, or selecting it and pressing the delete key.

**Comment by robertgzr** [comment]
right-click delete doesn't work. delete key does

might be an issue with sway/wayland

**Comment by robertgzr** [comment]
btw removing an entry and adding the same track again in the same instance (not closing gnome-mpv) I see the track twice on the playlist

**Comment by gnome-mpv** [comment]
>right-click delete doesn't work

Can't reproduce with sway 1.0-beta.1. Can you post the [log](https://github.com/gnome-mpv/gnome-mpv/blob/master/.github/CONTRIBUTING.md)?

>btw removing an entry and adding the same track again in the same instance (not closing gnome-mpv) I see the track twice on the playlist

Confirmed.

**Comment by robertgzr** [comment]
> Can't reproduce with sway 1.0-beta.1. Can you post the [log](https://github.com/gnome-mpv/gnome-mpv/blob/master/.github/CONTRIBUTING.md)?
> 
I mean that I don't even see the option if I right click an entry. As in the right-click menu is identical to when I click on the empty playlist.
I just get:
- Add
- Add location...
- Shuffle
- Loop File
- Loop Playlist

**Comment by gnome-mpv** [comment]
>I mean that I don't even see the option if I right click an entry. As in the right-click menu is identical to when I click on the empty playlist.

Are you using v0.15?

**Comment by robertgzr** [comment]
ahh I see that is a new feature in 0.15 - Solus is still on 0.14 :man_facepalming: 

thx anyways...
