### ISSUE TITLE
Play/Pause/Next/Previous buttons are not the correct color

### ISSUE THREAD

**Issue by ainola** [gnome-mpv/gnome-mpv#40]
For the dark variant, white icons should be used to contrast properly.

![screenshot from 2015-06-28 20-39-46](https://cloud.githubusercontent.com/assets/5383525/8400084/1c694afa-1dd6-11e5-8ddd-2f576d6fdf54.png)

I adore the work you've put into this very simple yet elegant player. Thank you!

**Comment by gnome-mpv** [comment]
Does 282f76a fix the problem?

**Comment by ainola** [comment]
Almost. Play/Pause are still gray.
![screenshot from 2015-06-29 21-23-47](https://cloud.githubusercontent.com/assets/5383525/8423373/2d26a232-1ea5-11e5-9cd0-e08a866159cd.png)

**Comment by ainola** [comment]
To clarify, it does work with Adwaita, but other icons seem to have issues, such as Faba, Faenza, and Moka. Is it possible that all three of those themes have the same fault?

**Comment by gnome-mpv** [comment]
The problem was that I didn't explicitly use the symbolic version of play/pause/next/previous icons, but Adwaita uses symbolic version by default anyway so the problem doesn't show up for Adwaita users.

Anyway, e4da231 should fix the problem.

**Comment by ainola** [comment]
Yer a wizard!

**Comment by shotgunshine** [comment]
The  volume button has the same problem since cb6012d , the icon names should end with `-symbolic`.

https://github.com/celluloid-player/celluloid/blob/aecc0f33bebab922f5687153b73182ad6355283b/src/celluloid-control-box.c#L685-L690

**Comment by gnome-mpv** [comment]
@shotgunshine Fixed in 3bc705b1f0e38f5df5c6c3629a068dd80cae735f.
