### ISSUE TITLE
[Question] A way to make media buttons bigger?

### ISSUE THREAD

**Issue by tannisroot** [gnome-mpv/gnome-mpv#401]
Hi, I just want to ask if it's somehow possible to make media control buttons (the ones at the bottom) bigger in size?
Personally, I have trouble using them in their current default small size. It's probably because I have minor issues with sensitivity in my hands, and it's usually not an issue for me as Gnome 3 follows the theme of having pretty large elements and using gestures, but Gnome MPV stands out from all other apps as it doesn't really follow that design.
Would appreciate all kind of feedback!

**Comment by gnome-mpv** [comment]
One way to do this would be to increase button size using CSS.

For example, you can put this in `~/.config/gnome-mpv/share/themes/Foo/gtk-3.0/gtk.css`:
````
@import url("resource:///org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css");

button.flat
{
	padding: 10px;
}
````

Then launch `gnome-mpv` like this:
````
GTK_DATA_PREFIX=~/.config/gnome-mpv GTK_THEME=Foo gnome-mpv
````

**Comment by tannisroot** [comment]
Thanks! That worked perfectly.
Tbh it also looks much nicer, would be cool if it was the default size.
