### ISSUE TITLE
Arch Linux link out of date

### ISSUE THREAD

**Issue by kode54** [gnome-mpv/gnome-mpv#404]
Overview Description:
The Arch Linux stable version link is out of date. Arch Linux has accepted the current stable version into the `community` repository.

Steps to Reproduce:
1. Query `pacman -Ss gnome-mpv`

Actual Results:
Observe that gnome-mpv is now in the `community` repository.

Expected Results:
That's what I was expecting when I saw that the package link on the gnome-mpv site pointed to a nice 404 error.

Version:
0.15-1

Additional Information:
This is a main site issue, not a software bug. The link can be corrected to:

`https://archlinux.org/packages/gnome-mpv`

Which will show that the package is available for x86_64.

**Comment by gnome-mpv** [comment]
Fixed: https://github.com/gnome-mpv/gnome-mpv.github.io/commit/c92709c0fae2afa94629ca59b87736a65171c4fc
