### ISSUE TITLE
Croatian language

### ISSUE THREAD

**Issue by muzena** [gnome-mpv/gnome-mpv#410]
Can you add Croatian language to Zanata?

**Comment by gnome-mpv** [comment]
I added Croatian (hr) to [Zanata](https://translate.zanata.org/webtrans/translate?project=gnome-mpv&iteration=master&localeId=hr&locale=en-US&dswid=-8172#view:doc;doc:gnome-mpv). You can follow instructions [here](https://github.com/gnome-mpv/gnome-mpv#contributing-translations) to start translating.  Let me know if you have any questions.

Thanks!
