### ISSUE TITLE
Translation to Turkish

### ISSUE THREAD

**Issue by TeknoMobil** [gnome-mpv/gnome-mpv#414]
Hello
What to do to create a Turkish translation
Cannot create new language in zanata.

Respects

**Comment by gnome-mpv** [comment]
I added Turkish (tr) to [Zanata](https://translate.zanata.org/webtrans/translate?project=gnome-mpv&iteration=master&localeId=tr&locale=en-US&dswid=9410#view:doc;doc:gnome-mpv). You can follow instructions [here](https://github.com/gnome-mpv/gnome-mpv#contributing-translations) to start translating. Let me know if you have any questions.

Thanks!

**Comment by TeknoMobil** [comment]
Thank you
Turkish translation ready to Zanata
