### ISSUE TITLE
Bad fullscreen controls on multiple monitors

### ISSUE THREAD

**Issue by Harenome** [gnome-mpv/gnome-mpv#45]
The size and the position of fullscreen controls are not correct when using multiple monitors.

Here follow some example screenshots:

![capture du 2015-08-11 16-13-40](https://cloud.githubusercontent.com/assets/676776/9201683/9a69c160-404e-11e5-8079-a11f1cf9d4b5.png)
![capture du 2015-08-11 16-14-21](https://cloud.githubusercontent.com/assets/676776/9201684/9a880062-404e-11e5-8f17-a2dbd43b262e.png)
![capture du 2015-08-11 17-15-03](https://cloud.githubusercontent.com/assets/676776/9201685/9aaf397a-404e-11e5-9ec6-76910cc83146.png)

**Comment by gnome-mpv** [comment]
I merged your pull request. Thank you for your contribution.
