### ISSUE TITLE
Fedora 22: ./configure: line 5982: syntax error near unexpected token `-O0'

### ISSUE THREAD

**Issue by fastrizwaan** [gnome-mpv/gnome-mpv#55]
checking for xgettext... (cached) /usr/bin/xgettext
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
./configure: line 5982: syntax error near unexpected token `-O0'
./configure: line 5982: `	AX_APPEND_COMPILE_FLAGS(-O0 -g -fsanitize=address)'

**Comment by TingPing** [comment]
Install autoconf-archive.

Can add some checks for cleaner errors when it is missing though.

**Comment by gnome-mpv** [comment]
I added some checks for autoconf-archive macros in 6f0e7cc.
