### ISSUE TITLE
Cannot play Youtube videos

### ISSUE THREAD

**Issue by zoqaeski** [gnome-mpv/gnome-mpv#56]
Trying to open Youtube videos (regardless of whether they are HTTP or HTTPS URIs) fails with an error message popup "[Stream] Failed to open <URI>" followed by "[cplayer] Failed to recognise file format."

This occurs when I open videos by Open Location, drag-and-drop, and command line. I don't get any issues opening videos with mpv or downloading them with youtube-dl.

**Comment by zoqaeski** [comment]
Just rebuilt and updated. and it works, but only if I disable the `mpv.conf` in preferences, otherwise I get an empty dialog box that pops up with just "[Error]". For the record, my mpv config looks like this:

    vo=opengl-hq,opengl,xv,
    ao=pulse,
    
    # Screenshots
    screenshot-format=png
    screenshot-template="%F-%P"
    screenshot-directory="/home/althea/pictures/screenshots/"
    
    ## CACHING
    # Use a 128 MB cache for network streams
    cache-default=131072
    cache-initial=16384
    # Prefetch up to a minute's worth of data
    cache-secs=60
    
    # Youtube configuration
    ytdl-format="bestvideo[height <=? 720]+bestaudio/best"

Could it be the DASH stream format specification?

**Comment by gnome-mpv** [comment]
Does the video start playing if you close the dialog and wait a little bit?

**Comment by zoqaeski** [comment]
> Does the video start playing if you close the dialog and wait a
> little bit?
Sometimes after a while, but other times another dialog will pop up
with the same error message as the first.

**Comment by gnome-mpv** [comment]
With e532997, the dialog box should no longer be empty. Let me know what error messages you see with the latest commits.
