### ISSUE TITLE
Missing "Preferences" menu outside the Gnome-Shell

### ISSUE THREAD

**Issue by tista500** [gnome-mpv/gnome-mpv#62]
Dear developers,

On some desktop-sessions (i.e. Budgie-Desktop, Pantheon etc..), we can't see "Preferences" menu in anywhere because those desktop-environments didn't have "AppMenu" feature that Gnome-Shell has.

This may happen if these things were True at the same time:
 * users run CSD-enabled gnome-mpv outside the gnome-shell 
 * `gsettings get org.gnome.settings-daemon.plugins.xsettings overrides` returns `{'Gtk/ShellShowsAppMenu': <0>}`

It would be nice "Preferences" menuitem was included into MainMenu on GtkWindow in that case.

Regards.

**Comment by gnome-mpv** [comment]
Usually, when the desktop environment doesn't support app menu, gtk will automatically create a new menu button in the title bar containing all the items that would have been in the app menu. Do you see this button at all? It is usually the leftmost button with the application's icon.

**Comment by tista500** [comment]
@gnome-mpv,

You mean the WM's "menu" button?
![screenshot from 2015-09-22 00-12-21](https://cloud.githubusercontent.com/assets/6073622/9995836/14282c2c-60bf-11e5-9fa8-be378596c951.jpg)

No, I meant this:
![screenshot from 2015-09-22 00-14-29](https://cloud.githubusercontent.com/assets/6073622/9995860/32f8bb58-60bf-11e5-8a87-701b8ffd860c.jpg)

Epiphany actually could convert the "Preferences" menuitem into MainMenu placed in Header-Bar though...

Regards.

**Comment by gnome-mpv** [comment]
Preferences should be in the first menu button.
![2015-09-21-142252_1280x720_scrot](https://cloud.githubusercontent.com/assets/8312231/9996165/07b77402-60b0-11e5-9c5c-87da0a936573.png)

**Comment by tista500** [comment]
@gnome-mpv,

Thanks for your image.
Hmm, so sad... :( Because we usually apply the button-layout as `close:maximize` on Pantheon shell.

Regards.
