### ISSUE TITLE
video panel background is transparent when no video loaded

### ISSUE THREAD

**Issue by infinity0** [gnome-mpv/gnome-mpv#63]
When I open gnome-mpv on the command line, the place where the video would normally go, is transparent so that I can see the windows behind it. There is no left border either. This is a pretty weird behaviour for apps to have. (I'm using xfwm4 with compositing, if that helps.)

~~~~
+---------------------------------------+
|               GNOME MPV               |
+------------------------------+--------+
                               |        |
                               |        |
                               |        |
     (e.g. firefox tab)        |  play  |
                               |  list  |
                               |        |
                               |        |
                               |        |
+------------------------------+--------+
|                play bar               |
+---------------------------------------+
~~~~

**Comment by gnome-mpv** [comment]
I can't reproduce this with xfwm 4.12.3.

**Comment by TingPing** [comment]
What mpv options do you use for `vo` and `hwdec`?

**Comment by gnome-mpv** [comment]
`vo=opengl-hq`
`hwdec=no`

**Comment by infinity0** [comment]
I don't have any specific config for mpv.conf. But it seems to be something to do with my GTK3 themes - I can reproduce it on one computer, and not on a different one, both with xfwm4.12.3. Will continue investigating and get back to you.

**Comment by infinity0** [comment]
Thanks, I've switched to a standard GTK3 theme and it's working now too, but I'll test the fix out against (my old, incomplete theme) next time. You can consider this issue fixed though, I don't think most users will run into this. :)
