### ISSUE TITLE
resolve directories without "playing" them when playlist is open

### ISSUE THREAD

**Issue by breunigs** [gnome-mpv/gnome-mpv#66]
Consider I have this folder structure:
```
X/A/one.mp4
X/B/two.mp4
```

Pointing gnome-mpv to `X/` will result in a playlist that looks like this:
```
one
B
```

It would be nice if gnome-mpv would resolve the items independently of the current file being played.

**Comment by wm4** [comment]
That's probably just what mpv does. It resolves directories only when attempting to play them. (At this point it sees that it's not actually a file.)

**Comment by breunigs** [comment]
Using mpv 0.18.0 (or higher, I presume) directories are resolved directly when opened/queued.
