### ISSUE TITLE
popups with warnings

### ISSUE THREAD

**Issue by suedi** [gnome-mpv/gnome-mpv#68]
Is there a way to tell gnome-mpv to only output warnings to console and not in popups
like mpv does?

i.e some sort of --silent command switch or a even better an option in configfile.

Alternatively could you give me some pointer to where in code they are created
so I can compile a copy without them?

*EDIT*

found the lines in mpv.c 396-399

```c
if(!iter || (message->log_level <= level->level))
{
show_error_dialog(ctx, message->prefix, message->text);
}
```

I commented them out and recompiled and got wanted behaviour.

However is there a way to set log level here so I do not have to comment out?

*EDIT2*

tried combinations of commands controlling mpv log/error messages in preferences-->Extra mpv options

The options detailed here
http://mpv.io/manual/master/#options-really-quiet

What am I missing?

*EDIT3*
If I input in  preferences-->Extra mpv options
```bash
--really-quiet
```
gnome-mpv wants to send 
```bash
--really-quiet=yes
```

and that doesn't work

How to pass --really-quiet

*EDIT4*

it may be possible to pass 

```bash
--really-quiet --
```

Still shows all errors in popups though

any input?

**Comment by gnome-mpv** [comment]
It is not possible to redirect log messages to console at the moment. I plan to work on this later.

You can disable all log messages with `--msg-level=all=no`.

**Comment by suedi** [comment]
sounds good man

I will comment out popup code for know
and look forward to next version with support
for this.

keep up the good work

**Comment by suedi** [comment]
looks like you didn't fix it, why did you close the issue?

**Comment by gnome-mpv** [comment]
There should be an option to redirect log messages to console in the preferences dialog now. When the option is enabled, popup warnings won't be shown for mpv log messages.

**Comment by suedi** [comment]
That looks so good. Was checking your repo on my phone 
so my bad.

God Job, thank you
