### ISSUE TITLE
Open resets the playlist

### ISSUE THREAD

**Issue by gnarula** [gnome-mpv/gnome-mpv#69]
Opening a file resets the playlist to one containing only the opened file. A better behaviour would be to append the file in the playlist and play it immediately.

**Comment by gnome-mpv** [comment]
I'm not sure this is a good idea. The playlist would keep growing larger unless the user periodically cleans it.

**Comment by gnarula** [comment]
The current behaviour kind of forces the user to either

* Queue all the files on the first open
* Append them to the playlist by drag and drop

The resetting of playlist is quite counter intuitive when the user has say, queued n videos in a collection and opening the n + 1 resets the playlist.

If not making it the default behaviour for "Open File", how about adding another option to append item to the playlist? (Maybe something like right click and add file to playlist...)

**Comment by gnome-mpv** [comment]
>If not making it the default behaviour for "Open File", how about adding another option to append item to the playlist?

I think this would be a better option.

**Comment by gnome-mpv** [comment]
d51e711
