### ISSUE TITLE
Deb and rpm

### ISSUE THREAD

**Issue by ai** [gnome-mpv/gnome-mpv#7]
We need `deb` and `rpm` builds for Ubuntu and Fedora.

**Comment by wealth** [comment]
Any progress on that? Looks like there's no libmpv in rpmfusion for fedora 21, and mpv is 0.7.

**Comment by gnome-mpv** [comment]
Not much progress so far. I'm currently looking into https://build.opensuse.org/ to see if it's possible to set up a repo for gnome-mpv there, though I think it might be better if someone else handles packaging for Ubuntu and Fedora as I'm not very familiar with those distros' packaging procedures.

**Comment by xuzhen** [comment]
I created a PPA for ubuntu 14.10 & 15.04
https://launchpad.net/~xuzhen666/+archive/ubuntu/gnome-mpv

**Comment by gnome-mpv** [comment]
Thank you. I added the link for the PPA to the readme file.

**Comment by ainola** [comment]
I've created an AUR package that intends to follow the release schedule of this program (rather than the existing git package):

https://aur.archlinux.org/packages/gnome-mpv/

**Comment by gnome-mpv** [comment]
@ainola: Thanks. I added the link to the readme file.

**Comment by sergioad** [comment]
Hello @gnome-mpv can you create a RPM package for fedora creating before if a COPR repository for making it avaliable for install and future updates?

**Comment by gnome-mpv** [comment]
@sergioad I found a Fedora/OpenSUSE package here.
https://build.opensuse.org/package/show/home:mermoldy:multimedia/gnome-mpv

**Comment by sergioad** [comment]
@gnome-mpv thank you very much :smile:

**Comment by gnome-mpv** [comment]
Now that we have packages for both Ubuntu and Fedora, I think this issue can be closed.

**Comment by region51** [comment]
*Hi, for Fedora 22 users you could install latest gnome-mpv player from russianfedora repository*
```
su -c 'dnf install --nogpgcheck http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/russianfedora-free-release-stable.noarch.rpm http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/russianfedora-nonfree-release-stable.noarch.rpm'
```
*and look*
```
[maxim@localhost ~]$ su -
Пароль: 
[root@localhost ~]# dnf info gnome-mpv
Last metadata expiration check performed 0:00:36 ago on Tue Aug 18 19:45:38 2015.
Доступные пакеты
Имя         : gnome-mpv
Архитектура : x86_64
Эпоха       : 0
Версия      : 0.5
Релиз       : 1.fc22.R
Размер      : 74 k
Репозиторий : russianfedora-free-updates
Краткое опи : A simple GTK+ frontend for mpv
URL         : https://github.com/gnome-mpv/gnome-mpv
Лицензия    : GPLv3+
Описание    : GNOME MPV interacts with mpv via the client API exported by libmpv,
            : allowing access to mpv's powerful playback capabilities.


```

**Comment by region51** [comment]
*Copr (Cool Other Package Repo) https://copr.fedoraproject.org/coprs/region51/gnome-mpv/*

**Comment by region51** [comment]
@gnome-mpv please delete link Copr

**Comment by gnome-mpv** [comment]
@region51: 62df6b4

**Comment by region51** [comment]
@gnome-mpv add link koji 
_Fedora (russianfedora): http://ru.fedoracommunity.org/repository or [koji](http://koji.russianfedora.pro/koji/packageinfo?packageID=155)_

**Comment by gnome-mpv** [comment]
@region51: cad734e

**Comment by region51** [comment]
@gnome-mpv http://ru.fedoracommunity.org/repository???

**Comment by gnome-mpv** [comment]
I think it's better to link directly to the package. It should already be easy to find http://ru.fedoracommunity.org/repository by looking up russianfedora in a search engine, but finding the package is not so obvious. This is consistent with the other links.

**Comment by region51** [comment]
OK.
