### ISSUE TITLE
"[cplayer] Failed to Recognize File Format" Popup Error

### ISSUE THREAD

**Issue by rushsteve1** [gnome-mpv/gnome-mpv#76]
The error occurs in the Debian Testing version when any video type is opened is opened. The video plays like normal regardless of the error.
Screenshot: 
![screenshot from 2015-11-04 14-00-50](https://cloud.githubusercontent.com/assets/5970439/10948679/c3fea996-82fc-11e5-969d-f2f1a8008232.png)

**Comment by gnome-mpv** [comment]
Can you check if this still happens with the git version?

**Comment by rushsteve1** [comment]
autogen.sh gives me a pkg-config error stating that MPV is not installed even when it is.

However after a reinstall of the version in the repos and a bit more testing i found that the error is not thrown when using the 'open' dialog from gnome-mpv itself. It is only thrown when opening from the command line or opening the file directly from the file browser.

**Comment by gnome-mpv** [comment]
>autogen.sh gives me a pkg-config error stating that MPV is not installed even when it is.

In Debian, you'll need to install libmpv-dev to compile.

>However after a reinstall of the version in the repos and a bit more testing i found that the error is not thrown when using the 'open' dialog from gnome-mpv itself. It is only thrown when opening from the command line or opening the file directly from the file browser.

Then it is likely that the issue has been fixed recently in 8c4a85f. Loading files multiple times too quickly seems to trigger that error message in mpv.

**Comment by rushsteve1** [comment]
That must have been the issue. After installing libmpv-dev it compiled and installed and the error is no longer present. That must mean that the package in Debian Testing is slightly out of date.
Thanks for the help.
