### ISSUE TITLE
Major accelerator key changes / breaks in almost all translations

### ISSUE THREAD

**Issue by Arthur2e5** [gnome-mpv/gnome-mpv#83]
In #82, the accel keys are broken by Chinese characters, or *kanjis*, that require an IM to input. Only out of curiosity to if see similar things are done in other languages, I got:

```PO
#  cs_CZ, not that serious as keyboards still work
#: ../src/main.c:441 ../src/common.c:415
msgid "_About"
msgstr "_O programu"

#  fr_FR, same as cs_CZ
msgid "_About"
msgstr "_À propos"

#  de_DE, same as above
#: ../src/main.c:512 ../src/common.c:454
msgid "_Preferences"
msgstr "_Einstellungen"

#  ja, as bad as zh (and actually kanjis again!)
#: ../src/main.c:440 ../src/common.c:384
msgid "_Preferences"
msgstr "_設定"
```

And so on. Those 'not that serious' ones doesn't break functionality since keyboards for that locale may still be able to type those characters in an Alt+Accel combination -- they only make tutorials more confusing.

**Comment by Arthur2e5** [comment]
Well, I can try fixing this, the only potential problem being I can speak none of these languages…

**Comment by gnome-mpv** [comment]
Looking at other projects (eg. gnome-terminal, gedit, nautilus), it seems that accel key changes are common, so I don't think it's a problem. Now that the kanji accel keys have been fixed, I think this issue can be closed.
