### ISSUE TITLE
Request: Resuming files from last played position.

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#85]
*Resuming files from last played position in GNOME-MPV.*
*I would like to see this feature in a given player.*

*PS. I'm sorry for my bad english.*

**Comment by gnome-mpv** [comment]
Quitting by pressing shift+Q should already do this.

**Comment by region51** [comment]
@gnome-mpv 
>Quitting by pressing shift+Q should already do this.

gnome-mpv-0.6 -> does not work

**Comment by gnome-mpv** [comment]
Can't reproduce. Do you have any external config files loaded?

Note that `gnome-mpv` won't start playing the last file automatically, you have to open the file first, then playback will resume at the last position.

**Comment by region51** [comment]
>Do you have any external config files loaded?

no

>then playback will resume at the last position.

it does not occur

**Comment by gnome-mpv** [comment]
Does shift+Q work if you use mpv directly?

**Comment by region51** [comment]
shift+Q close
then playback will resume at the last position -> it does not occur

**Comment by gnome-mpv** [comment]
>shift+Q -> close
>then playback will resume at the last position -> it does not occur
So shift+Q does not work even when you're using vanilla mpv? Are there any error messages in the console?

**Comment by region51** [comment]
this only works if you open the file from menu-open
if you open a file on a straight line, then it does not work

**Comment by region51** [comment]
it should not be

**Comment by gnome-mpv** [comment]
>if you open a file on a straight line, then it does not work

I'm not sure what opening a file on a straight line mean.

**Comment by region51** [comment]
@gnome-mpv I do not understand you.

**Comment by gnome-mpv** [comment]
@region51 Neither do I. :)

**Comment by region51** [comment]
if the file is opened from the nautilus, then "Resuming files from last played position" does not work

If opened from menu gnome-mpv - open, then "Resuming files from last played position" working

**Comment by gnome-mpv** [comment]
I see. In 0.6, resume does not work correctly when the file is opened from nautilus or on the command line due to a bug that causes the file to be internally loaded twice. This is fixed in 8c4a85f, so if you update to the latest git version the problem should be fixed.

**Comment by region51** [comment]
well, I will wait gnome-mpv-0.7

**Comment by region51** [comment]
It is working with git.
