### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by NikoofDeath** [gnome-mpv/gnome-mpv#86]
Whether I set them through load mpv configuration or through command line options, none of my settings work in gnome-mpv. For example, my screenshot directory setting (which I've confirmed working on mpv standalone) doesn't work, simply using the default setting.

I'm using the gnome-mpv ebuild from the lxde-gtk3 overlay for gentoo.

**Comment by gnome-mpv** [comment]
Fixed in a5870b6 and bc02d6c.
