### ISSUE TITLE
Option to disable embedded subtitles

### ISSUE THREAD

**Issue by GreyAsteroid** [gnome-mpv/gnome-mpv#93]
You can currently switch between embedded subtitles and select external subtitles, but cannot deselect subtitles.

**Comment by gnome-mpv** [comment]
It's already possible to toggle subtitle visibility by pressing 'v', but I'll add menu items so that you can do this with a mouse as well.

**Comment by esdegan50000** [comment]
can we disable subtitle by default? press "v" will always load subtitle again when we reopen the player.

**Comment by gnome-mpv** [comment]
> can we disable subtitle by default? press "v" will always load subtitle again when we reopen the player.

Putting `--sid=no` in `Extra MPV Options` will disable subtitle by default. If you also want to block `v` from displaying subtitle, you can unbind the key using `input.conf`.
