### ISSUE TITLE
Build (packaging) error with existing po

### ISSUE THREAD

**Issue by mc4man** [gnome-mpv/gnome-mpv#95]
Don't know anything concerning translations so more a query as to best fix. 
Using libmpv-0.14 & gnome-mpv master, package builds fail concerning ' translations in src/menu.c but not used'
Adding src/menu.c to POTFILES.in solves, is that correct or should it go in POTFILES.skip?

**Comment by gnome-mpv** [comment]
> Adding src/menu.c to POTFILES.in solves, is that correct or should it go in POTFILES.skip?
That's correct. I forgot to add menu.c to POTFILES.in.
