### ISSUE TITLE
[Feature request]: Use Transifex to coordinate localisation

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#96]
https://www.transifex.com/
With it translators can be promptly notified when there's something to be done and the job can also be done via a web interface.

example lollypop https://www.transifex.com/gnumdk/lollypop/

**Comment by TingPing** [comment]
This was discussed some in #82

**Comment by gnome-mpv** [comment]
362ec1f

I opted for Zanata since Transifex is proprietary.
