### ISSUE TITLE
Add a new language

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#98]
>If you'd like to add a new language, open an issue on GitHub.

Please add the Russian language, I will translate
https://translate.zanata.org/zanata/iteration/view/gnome-mpv/master

**Comment by gnome-mpv** [comment]
Added.

**Comment by region51** [comment]
@gnome-mpv hi, I do not understand in zanata, how to begin to translate?

**Comment by gnome-mpv** [comment]
Follow the tutorial here: http://docs.zanata.org/en/release/user-guide/translator-guide/

**Comment by region51** [comment]
zanata a nightmare, I'm sorry, but I will not be there to translate. if you want, you can remove the Russian language.

**Comment by gnome-mpv** [comment]
I didn't know it's that bad. I'll consider other options.

**Comment by region51** [comment]
Yes, I just got used to Transifex. I try to get used to Zanata

**Comment by region51** [comment]
@gnome-mpv hi, add please russian translation in git, LINGUAS ...

**Comment by gnome-mpv** [comment]
f453a56

**Comment by region51** [comment]
:+1:

**Comment by region51** [comment]
@gnome-mpv hi, where this translation???
>Error
>>Failed to apply one or more MPV options.

```
Extra MPV options: a-bla-bla
Дополнительные опции MPV: a-bla-bla
```
![2016-01-07 22-00-15](https://cloud.githubusercontent.com/assets/13280183/12179852/40f39f00-b58a-11e5-9fc0-e284014eef73.png)

**Comment by gnome-mpv** [comment]
It's in `mpv.c` but I forgot to add the file to POTFILES.in. The string should be in Zanata now.

**Comment by region51** [comment]
@gnome-mpv nice, ERROR translation???
![2016-01-08 12-53-08](https://cloud.githubusercontent.com/assets/13280183/12195270/ebe98204-b606-11e5-98a8-1276a8fab481.png)

**Comment by gnome-mpv** [comment]
Missed that. It's marked for translation now.

**Comment by region51** [comment]
@gnome-mpv I translated
```
Error
Ошибка
```
![2016-01-08 13-07-02](https://cloud.githubusercontent.com/assets/13280183/12195530/de27f93c-b608-11e5-8019-95822e7d7d19.png)

where translation ???

**Comment by region51** [comment]
@gnome-mpv ping ^^^

**Comment by gnome-mpv** [comment]
It's supposed to be there but it isn't. I'm looking into it.

**Comment by gnome-mpv** [comment]
Seems to work fine here. Try reinstalling and/or restarting X.
![screenshot](https://cloud.githubusercontent.com/assets/8312231/12196303/3fae7056-b630-11e5-83f0-50bfb6549886.png)

**Comment by region51** [comment]
@gnome-mpv 
>or restarting X

![2016-01-08 13-54-16](https://cloud.githubusercontent.com/assets/13280183/12196432/95e86830-b60f-11e5-9b49-22c104523457.png)

**Comment by region51** [comment]
Now do the last commit

**Comment by region51** [comment]
@gnome-mpv Thank you
![2016-01-08 14-22-30](https://cloud.githubusercontent.com/assets/13280183/12196913/7dbb2802-b613-11e5-9295-bff0b24ddbeb.png)

gnome-mpv commit edae5f662531dafd67d21fd84ab209acccf1d897
please update russian translation of Zanata in git 
for https://github.com/RussianFedora/gnome-mpv/blob/gnome-mpv-git/gnome-mpv.spec

**Comment by gnome-mpv** [comment]
Done.

**Comment by region51** [comment]
:+1:

**Comment by region51** [comment]
@gnome-mpv please update russian translation of Zanata in git
and probably should be removed
>Whether or not to redirect mpv log messages to console

**Comment by gnome-mpv** [comment]
Done.

**Comment by region51** [comment]
@gnome-mpv please update russian translation of Zanata in git

**Comment by gnome-mpv** [comment]
@region51: Done

**Comment by region51** [comment]
@gnome-mpv please sync last translation of Zanata in git
