### ISSUE TITLE
RFC: Which localization platform should we use?

### ISSUE THREAD

**Issue by gnome-mpv** [gnome-mpv/gnome-mpv#99]
This was discussed a little in #82. Based on the suggestions, I decided to opt for Zanata as Transifex is proprietary. However, it seems Zanata might be more difficult (#98) to use than Transifex. Doing a quick research, I found two other alternatives: Weblate and Pootle. Only Weblate seems to have a public instance. From looking around quickly, it also appears to be reasonably easy to use. Suggestions/comments welcome.

**Comment by region51** [comment]
let it be Zanata

**Comment by gnome-mpv** [comment]
Let's stay with Zanata for now.
